import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyBrowser} from './browser-guards.mjs';
const root='artifacts/task-validation/426-room-actions',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,'')),sha=b=>createHash('sha256').update(b).digest('hex'),app=read('frozen-release-source.json').applicationCommit;
assert.equal(execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),app);
const before=read('root-rerun4/source-before.json'),after=read('root-rerun4/source-after.json');assert.deepEqual(before,after);assert.equal(after.head,app);assert.equal(after.status,'');assert.deepEqual(after.untracked,[]);assert.equal(after.files.length,1539);
const qaBytes=readFileSync(root+'/independent-qa4/artifact-manifest.json'),qa=JSON.parse(qaBytes);assert.equal(qa.head,app);assert.match(readFileSync(root+'/independent-qa4/validation-report.md','utf8'),/^QA Verdict: READY FOR CODEX QA$/m);
for(const f of qa.files)assert.equal(sha(readFileSync(root+'/independent-qa4/'+f.path)),f.sha256);
const qBefore=read('independent-qa4/source-before.json'),qAfter=read('independent-qa4/source-after.json');assert.equal(qBefore.head,app);assert.equal(qAfter.head,app);assert.deepEqual(qBefore.files,qAfter.files);assert.equal(qBefore.status,'');assert.deepEqual(qBefore.untracked,[]);
assert.deepEqual(before.files.map(f=>f.path),qBefore.files.map(f=>f.path));const normalization=[];
for(let i=0;i<before.files.length;i++){const a=before.files[i],b=qBefore.files[i];if(a.sha256===b.sha256)continue;const own=readFileSync(a.path),other=readFileSync('C:/w-426-qa4/'+a.path),text=new TextDecoder('utf-8',{fatal:true});assert.equal(sha(own),a.sha256);assert.equal(sha(other),b.sha256);assert.equal(text.decode(own).replaceAll('\r\n','\n'),text.decode(other).replaceAll('\r\n','\n'));normalization.push({path:a.path,policy:'strict UTF-8 CRLF-to-LF only'});}
const pre=read('root-rerun4/pre-run.json');assert.equal(pre.applicationCommit,app);assert.equal(pre.qaManifestSha256,sha(qaBytes));
for(const r of pre.records){assert.equal(sha(readFileSync(root+'/root-rerun4/recipes/'+r.name)),r.sha256);assert.equal(sha(readFileSync(root+'/independent-qa4/recipes/'+r.name)),r.sha256);}
const plan=read('browser-plan.json');let cases=0;
for(const item of plan){assert.ok(pre.records.some(r=>r.name===item.recipe));const current=read('root-rerun4/'+item.folder+'/test-results/browser-results.json'),independent=read('independent-qa4/'+item.folder+'/test-results/browser-results.json');verifyBrowser(current,app,item.cases);verifyBrowser(independent,app,item.cases);assert.deepEqual(current.outcomes,independent.outcomes);cases+=item.cases;}
for(const folder of ['root-rerun4','independent-qa4']){
 const commands=read(folder+'/commands01/command-results.json');assert.deepEqual(commands.newFailures,[]);
 for(const r of commands.records){if(r.name==='full-regression'){assert.equal(r.tests,1267);assert.equal(r.pass,1255);assert.equal(r.fail,12);assert.deepEqual(r.failures,commands.baselineFailures);}else{assert.equal(r.exit,0);if(r.name==='focused'){assert.equal(r.tests,24);assert.equal(r.pass,24);assert.equal(r.fail,0);}}}
 assert.deepEqual(read(folder+'/security01/comparison.json').newFindings,[]);
}
assert.equal(read('root-rerun4/server-stop.json').listenerFree,true);assert.equal(read('independent-qa4/lane-handoff.json').browserLane,'RELEASED');
const failed=[];for(const [folder,expected,count]of [['failed-independent-qa-07','7a7ee7ff2f48dde6ba453771441f753634dcdd6d13583b9c32219a51a86d2f7d',105],['failed-independent-qa2-143','214ebae4bdc1cced6455897772fc0acca255488c91cb95b74a2b0a6055dafe29',100],['failed-independent-qa3-922','133014ded7ed582f34b38f615551b8ab66ca1509407e6a1a99150d7fbfbf7c58',140]]){const bytes=readFileSync(root+'/'+folder+'/artifact-manifest.json'),m=JSON.parse(bytes);assert.equal(sha(bytes),expected);assert.equal(m.files.length,count);for(const f of m.files)assert.equal(sha(readFileSync(root+'/'+folder+'/'+f.path)),f.sha256);failed.push({folder,manifestSha256:expected,files:count,verdict:'FAILED VALIDATION retained, not waived'});}
const receipt={applicationCommit:app,decision:'AUTHORIZED SCOPED APPLICATION PROMOTION',authority:'Explicit human authorization plus NEW independent QA4 and root byte-identical source-bound replay',originalCriteriaPassed:4,independentBrowserCases:cases,rootIndependentRerun:cases,sourceSha256:after.sourceSha256,independentRawSourceSha256:qAfter.sourceSha256,sourceFiles:1539,qaManifestSha256:sha(qaBytes),immutableQaFiles:qa.files.length,normalization,focusedEach:24,fullEach:{tests:1267,pass:1255,exactBaselineFailures:12,newFailures:0},productionPatientTestMutations:0,scope:read('frozen-release-source.json').completeScope,failedAttempts:failed,hardwareClaim:'Chromium viewport/emulation only, not actual hardware/AT',persistenceClaim:'Before-wire stateful mock reload only; NO realDB or live deletion claim',remainingReleaseGates:['Exact production deployment','Compiled online acceptance','Completed CI baseline comparison','Canonical privacy and pinned public GitHub proof'],at:new Date().toISOString()};
writeFileSync(root+'/release-gate-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({decision:receipt.decision,applicationCommit:app,cases,sourceFiles:1539}));
