import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyCanonical} from './canonical-blobs.mjs';
const root='artifacts/task-validation/426-room-actions',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,'')),app=read('frozen-release-source.json').applicationCommit,branch='codex/bug-426-room-actions',sha=b=>createHash('sha256').update(b).digest('hex');
const configured=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:100e6});assert.equal(r.status,0,'Git proof check failed safely');return r.stdout.trim();};
const gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',maxBuffer:30e6,env:{...process.env,GH_TOKEN:configured.GITHUB_TOKEN||configured.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const proof=git(['rev-parse','HEAD']),publication=read('publication-manifest.json'),gate=read('release-gate-receipt.json'),deployment=read('deployment-receipt.json'),online=read('compiled-online/online-receipt.json');
assert.equal(online.applicationCommit,app);assert.equal(online.cases,22);assert.equal(gate.originalCriteriaPassed,4);assert.equal(gate.independentBrowserCases,22);assert.equal(gate.rootIndependentRerun,22);assert.equal(publication.applicationCommit,app);assert.equal(publication.originalIndependentManifestFrozen,true);
assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof+'\\s'));assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+app+'\\s'));assert.ok(git(['diff','--name-only',app,proof]).split('\n').every(p=>p.startsWith(root+'/')));verifyCanonical(publication.files,proof);
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${root}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${root}`,images=read('public-images.json'),verified=[];
for(const {label,path}of images){assert.ok(label&&path.startsWith('compiled-online/'));const r=await fetch(raw+'/'+path);assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(sha(bytes),sha(readFileSync(root+'/'+path)));verified.push({path,http:200,sha256:sha(bytes)});}
assert.equal(verified.length,4);
const blocked=existsSync(root+'/ci-blocker-receipt.json'),ci=read(blocked?'ci-blocker-receipt.json':'ci-comparison.json');assert.equal(ci.applicationCommit,app);
assert.match(readFileSync(root+'/validation-report.md','utf8'),blocked?/## Final Decision\s+BLOCKED(?:\s|$)/:/## Final Decision\s+CLOSED — VERIFIED(?:\s|$)/);
if(!blocked){const check=spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',root],{encoding:'utf8'});assert.equal(check.status,0);writeFileSync(root+'/check-closure.log',check.stdout+check.stderr);}
const original=read('independent-qa4/original-issue.json').issue.body,issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/426']));assert.equal(issue.body,original);assert.equal(issue.state,'open');
const comments=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/426/comments','--paginate','--slurp'])).flat(),actor=JSON.parse(gh(['api','user'])).login;assert.ok(actor);
writeFileSync(root+'/github-publication-policy.json',JSON.stringify({decision:blocked?'AUTHORIZED PINNED PARTIAL COMMENT/BLOCKED LABEL ONLY':'AUTHORIZED PINNED VERIFIED COMMENT/ISSUE CLOSURE',authority:'Explicit human authorization plus source-bound independent and root release gates; no gate waiver',applicationCommit:app,proofCommit:proof,verifiedImages:verified,issueMustRemainOpen:blocked,productionPatientTestMutations:0,at:new Date().toISOString()},null,2));
const body=`${blocked?'BLOCKED — infrastruttura CI; issue lasciata APERTA.':'CLOSED — VERIFIED.'} Correzione [${app}](https://github.com/l2v-hub/ClinicOS/commit/${app}) online, Vercel ${deployment.vercel.id} READY con Git SHA esatto, alias/HTML/JS/CSS HTTP200 e hash invariati prima/dopo22 prove sul bundle pubblicato.

Tutti4 criteri originali PASS: azioni identificano camera e letto senza ambiguità; tooltip/editor/conferma mantengono la stessa identità originale anche durante rinomina; eliminazione distinta con icona cestino, colore danger e16px di separazione, conferma esistente preservata; verifica senza alcun DELETE reale. Nomi lunghi e separatori/virgolette sono resi letteralmente e completamente, senza abbreviare l'identità.

Tre candidati respinti dalla QA e conservati integralmente: [07,105 artefatti](${tree}/failed-independent-qa-07/artifact-manifest.json), [143,100](${tree}/failed-independent-qa2-143/artifact-manifest.json), [922,140](${tree}/failed-independent-qa3-922/artifact-manifest.json). Le prove forti mostravano clipping di titoli e testo di conferma a390px. La correzione finale è locale a Posti letto: titoli/messaggio a capo e pulsante danger con altezza automatica; override scoped della regola nowrap/fixed-height del design system, senza modificare il componente condiviso, palette o autorizzazioni. Non sono state indebolite le asserzioni né sostituiti fallimenti con screenshot migliori.

[Nuova QA4 indipendente](${tree}/independent-qa4/validation-report.md):22/22 gruppi browser PASS, [122 artefatti immutabili](${tree}/independent-qa4/artifact-manifest.json), SHA${gate.qaManifestSha256}. Root22 con ricette byte-identiche e22 sul sito compilato, inclusi limiti dei glifi orizzontali/verticali, Tab/Escape/focus return e pixel hit-test. Screenshot finali realmente ispezionati. Viewport Chromium1280×720 e390×844, NON certificazione hardware/AT fisica.

Tipi FE/BE/tsc-b/build Reactcompiler/secrets PASS.24/24 test mirati PASS; regressione1267:1255PASS,12 errori nominati identici alla baseline accettata,0 nuovi, NON verde globale. Scanner nativo sulle8 sorgenti diff0 finding baseline/candidato; non audit CVE globale. Sorgente1539 file prima/dopo invariata, rawSHA${gate.sourceSha256}; rawSHA QA${gate.independentRawSourceSha256}, differenze checkout solo strictUTF8 CRLF-to-LF verificate. API/auth/schema/deps/config/backend invariati; backend47a/Railwayed539 health200, nessun deploy backend necessario.

${blocked?`[CI${ci.candidateRun}](https://github.com/l2v-hub/ClinicOS/actions/runs/${ci.candidateRun}) Initialize containers fallita PRIMA del checkout (DockerHub); CI applicativa non verificata, non il noto errore backend. [Receipt](${tree}/ci-blocker-receipt.json); nessuna chiusura o retry invariato.`:`[CI${ci.candidateRun}](https://github.com/l2v-hub/ClinicOS/actions/runs/${ci.candidateRun}) completata e [confrontata](${tree}/ci-comparison.json): ${ci.candidateConclusion==='success'?'success':'stesso singolo fallimento backend accettato e stesso stage; test downstream saltati, non dichiarati passanti'},0 nuovi. Secret scan${ci.frontendSecretScanRun} success.`}

Prove fissate a${proof}: [report](${tree}/validation-report.md), [gate](${tree}/release-gate-receipt.json), [deployment](${tree}/deployment-receipt.json), [online](${tree}/compiled-online/online-receipt.json), [manifest canonicale/credenziali/ZIP](${tree}/publication-manifest.json), [risultati/trace/video](${tree}/compiled-online), [receipt HTML](${tree}/compiled-online/playwright-report/index.html). HTML è receipt Playwright-library, non report del runner nativo. Tutte le API intercettate PRIMA rete;0 scritture pazienti reali/PHI/DELETE. Le2 risposte409 deliberate sono esclusivamente mock su QA-BED-426-2-B e asserite esplicitamente; reload verificato in memoria simulata, NON persistenza DB reale. Nessuna certificazione clinica/hardware/AT globale.

${images.map(({label,path})=>`### ${label}\n![426 ${label}](${raw}/${path})`).join('\n\n')}`;
let comment=comments.find(c=>c.user?.login===actor&&c.body===body);
if(!comment)comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/426/comments','--method','POST','-f',`body=${body}`]));
assert.equal(comment.body,body);assert.equal(comment.user?.login,actor);
if(blocked)gh(['issue','edit','426','--repo','l2v-hub/ClinicOS','--add-label','status-blocked']);else gh(['issue','close','426','--repo','l2v-hub/ClinicOS','--reason','completed']);
const current=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/426']));assert.equal(current.state,blocked?'open':'closed');assert.equal(current.body,original);
const receipt={applicationCommit:app,proofCommit:proof,proofBranch:branch,githubProof:comment.html_url,state:current.state,decision:blocked?'PARTIAL EVIDENCE PUBLISHED; EXTERNAL CI BLOCKER, NO CLOSURE':'CLOSED — VERIFIED',canonicalHashesVerified:publication.files.length,images:verified,secretChecks:publication.secretChecks,zipEntriesChecked:publication.zipEntriesChecked,productionPatientTestMutations:0,at:new Date().toISOString()};writeFileSync(root+'/github-publication-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
