import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {verifyBrowser} from './browser-guards.mjs';
const root='artifacts/task-validation/426-room-actions',out=root+'/compiled-online',read=p=>JSON.parse(readFileSync(root+'/'+p)),sha=b=>createHash('sha256').update(b).digest('hex');
const deployment=read('deployment-receipt.json'),pre=read('compiled-online/pre-run.json'),gate=read('release-gate-receipt.json');assert.equal(pre.applicationCommit,deployment.applicationCommit);assert.equal(pre.applicationCommit,gate.applicationCommit);let cases=0;
for(const r of pre.records){assert.equal(sha(readFileSync(out+'/recipes/'+r.recipe)),r.compiledRecipeSha256);assert.equal(r.compiledRecipeSha256,r.localFrozenRecipeSha256);const result=read('compiled-online/'+r.folder+'/test-results/browser-results.json');verifyBrowser(result,pre.applicationCommit,r.cases);cases+=r.cases;}
assert.equal(cases,gate.rootIndependentRerun);
const response=await fetch(pre.bundleUrl);assert.equal(response.status,200);const actual=sha(Buffer.from(await response.arrayBuffer()));assert.equal(actual,pre.bundleSha256Before);assert.equal(actual,deployment.vercel.bundleSha256);
const htmlResponse=await fetch('https://clinicos-eosin.vercel.app/');assert.equal(htmlResponse.status,200);assert.equal(sha(Buffer.from(await htmlResponse.arrayBuffer())),pre.htmlSha256Before);
for(const style of pre.styleAssets){const css=await fetch(style.url);assert.equal(css.status,200);assert.equal(sha(Buffer.from(await css.arrayBuffer())),style.sha256);}
const receipt={applicationCommit:pre.applicationCommit,decision:'COMPILED ONLINE ACCEPTANCE VERIFIED',cases,bundleUrl:pre.bundleUrl,bundleSha256Before:pre.bundleSha256Before,bundleSha256After:actual,productionPatientTestMutations:0,apiGuard:'All auth/facility/clinical APIs intercepted before wire; production static GET allowlist only',physicalHardware:false,persistence:'Mock-only reload, no real database or DELETE test',at:new Date().toISOString()};writeFileSync(out+'/online-receipt.json',JSON.stringify(receipt,null,2));
mkdirSync(out+'/playwright-report',{recursive:true});writeFileSync(out+'/playwright-report/index.html',`<!doctype html><html lang="it"><meta charset="utf-8"><title>ClinicOS426 browser assertions</title><body><h1>#426 — ${cases} verifiche PASS</h1><p>Receipt di asserzioni Playwright library, NON report del runner nativo. Commit ${pre.applicationCommit}; bundle SHA${actual}. Fixture sintetiche, API intercettate prima rete, nessuna scrittura reale/DELETE. Emulazione browser, non certificazione hardware o AT.</p><ul>${pre.records.map(r=>`<li><a href="../${r.folder}/test-results/browser-results.json">${r.folder}: ${r.cases} casi, valori e guardie</a></li>`).join('')}</ul></body></html>`);console.log(JSON.stringify(receipt));
