import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
const errors = [];
page.on('console', (m) => m.type() === 'error' && errors.push(m.text().slice(0, 200)));
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message.slice(0, 300)));
await page.goto('http://localhost:4173', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(700);
await page.getByText('Operatore', { exact: true }).first().click();
await page.locator('.teams-sidebar').waitFor();
await page.waitForTimeout(1500);
await page.locator('.teams-sidebar button', { hasText: 'Pazienti' }).first().click();
await page.locator('.page-content tbody tr').nth(1).waitFor();
await page.waitForTimeout(800);
await page.locator('.page-content tbody tr').nth(1).click();
await page.waitForTimeout(2500);
await page.screenshot({ path: 'artifacts/task-validation/performance-navigazione-tra-contesti-lista-pazienti-e-altri/perf/detail-shot.png' });
console.log((await page.locator('.page-content').innerText()).slice(0, 400).replace(/\n/g, ' | '));
console.log('errors:', errors.slice(0, 5));
await browser.close();
