import {readFileSync,writeFileSync,mkdirSync,copyFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
const base=resolve('artifacts/task-validation/420-import-recovery/independent-qa420'),attempt=resolve(base,process.argv[2]||'attempt-1');assert.equal(existsSync(attempt),false,'Immutable attempt already exists');mkdirSync(attempt+'/before',{recursive:true});
const source='c00bff678dfc9845c31742bc5d0d750fbbb9603e',scopes=['frontend/src','backend/src','prisma','package.json','package-lock.json','frontend/package.json','frontend/tsconfig.json','frontend/tsconfig.app.json','frontend/tsconfig.node.json','frontend/vite.config.ts','frontend/vercel.json','backend/package.json','backend/tsconfig.json','scripts/build/copy-assessment-fonts.mjs','scripts/stub-css-loader.mjs','scripts/run-node-tests.mjs'];
const sha=b=>createHash('sha256').update(b).digest('hex');const git=a=>{const r=spawnSync('git',a,{encoding:'utf8',maxBuffer:30e6});assert.equal(r.status,0);return r.stdout;};assert.equal(git(['rev-parse','HEAD']).trim(),source);assert.equal(git(['diff','HEAD','--',...scopes]),'');assert.equal(git(['ls-files','--others','--exclude-standard','--',...scopes]),'');
const sourceFiles=git(['ls-files','-z','--',...scopes]).split('\0').filter(Boolean).sort().map(path=>({path,sha256:sha(readFileSync(path))}));
const recipeFiles=['fixture.mjs','recipe.mjs','qa-server.mjs','commands.mjs','prepare.mjs','task-contract.md'];const files=recipeFiles.map(path=>{const b=readFileSync(resolve(base,path));copyFileSync(resolve(base,path),resolve(attempt,'before',path+'.source'));return{path,sha256:sha(b),bytes:b.length};});
for(const path of ['frontend/vite.config.ts','frontend/tsconfig.app.json','frontend/package.json','scripts/run-node-tests.mjs','scripts/stub-css-loader.mjs']){const b=readFileSync(path);const target=path.replaceAll('/','__');copyFileSync(path,resolve(attempt,'before',target+'.source'));files.push({path:target,original:path,sha256:sha(b),bytes:b.length});}
writeFileSync(attempt+'/before/source.json',JSON.stringify({applicationCommit:source,scope:scopes,files:sourceFiles},null,2));writeFileSync(attempt+'/before/pre-run-receipt.json',JSON.stringify({snapshotAt:new Date().toISOString(),applicationCommit:source,files,runtime:{node:process.version,playwright:'1.61.1',compiler:'actual frontend/vite.config.ts react compiler',port:7503,envOverrides:false,sharedDependencies:'readonly junction installed by integration; no mutation'},authoring:'Fresh independent recipe; inspected implementer synthetic transport fixture reused with stricter per-URL guard and independent fault extensions'},null,2));console.log(attempt);
