import {readFileSync,writeFileSync,readdirSync,statSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve,relative} from 'node:path';
import assert from 'node:assert/strict';
const dir=resolve('artifacts/task-validation/420-import-recovery/independent-qa420'),sha=b=>createHash('sha256').update(b).digest('hex');
const before=JSON.parse(readFileSync(dir+'/source-before/source-receipt.json')),after=JSON.parse(readFileSync(dir+'/source-after/source-receipt.json'));assert.deepEqual(before,after);assert.equal(after.applicationCommit,'c00bff678dfc9845c31742bc5d0d750fbbb9603e');
for(const attempt of ['attempt-1','attempt-2']){const pre=JSON.parse(readFileSync(`${dir}/${attempt}/before/pre-run-receipt.json`));for(const file of pre.files)assert.equal(sha(readFileSync(`${dir}/${attempt}/before/${file.path}.source`)),file.sha256);const results=JSON.parse(readFileSync(`${dir}/${attempt}/run/test-results/results.json`));assert.ok(pre.snapshotAt<results.results[0].startedAt);if(attempt==='attempt-2'){assert.equal(results.results.length,20);assert.ok(results.results.every(r=>r.status==='PASS'));assert.equal(results.productionPatientMutations,0);}else assert.equal(results.results.at(-1).status,'FAIL');}
const comparison=JSON.parse(readFileSync(dir+'/commands/regression-comparison.json'));assert.equal(comparison.sameFailures,true);assert.equal(comparison.currentFailures.length,12);const commands=JSON.parse(readFileSync(dir+'/commands/results.json'));assert.ok(commands.every(r=>r.name==='full-regression'||r.exitCode===0));
const privacy=JSON.parse(readFileSync(dir+'/privacy-scan-receipt.json','utf8').replace(/^\uFEFF/,''));assert.equal(privacy.findings,0);
function walk(p){return readdirSync(p).sort().flatMap(name=>{const target=resolve(p,name);return statSync(target).isDirectory()?walk(target):[target];});}
const cache=resolve(dir,'runtime-cache'),cacheFiles=existsSync(cache)?walk(cache).map(p=>({path:relative(cache,p).replaceAll('\\','/'),sha256:sha(readFileSync(p)),bytes:statSync(p).size})):[];
writeFileSync(dir+'/runtime-cache-manifest.json',JSON.stringify({excluded:'Owned Vite optimizer runtime cache only, not source or original evidence; retained separately manifested, never deleted',files:cacheFiles},null,2));
assert.equal(existsSync(dir+'/immutable-manifest.json'),false,'Do not overwrite seal');
const files=walk(dir).filter(p=>!p.startsWith(cache+'/')&&!p.startsWith(cache+'\\')).map(p=>({path:relative(dir,p).replaceAll('\\','/'),sha256:sha(readFileSync(p)),bytes:statSync(p).size}));
writeFileSync(dir+'/immutable-manifest.json',JSON.stringify({decision:'READY FOR CODEX QA',sealedAt:new Date().toISOString(),applicationCommit:after.applicationCommit,baselineCommit:after.baseline,fileCount:files.length,retention:'Original failed attempt1 and passing attempt2 raw PNG/trace/video/guards/report retained; archived pre-run recipes end .source. Only runtime-cache excluded and separately byte manifested.',files},null,2));console.log(JSON.stringify({decision:'READY FOR CODEX QA',fileCount:files.length,manifestSha256:sha(readFileSync(dir+'/immutable-manifest.json')),sourceSha256:after.sourceSha256}));
