import { test, expect } from 'playwright/test';
import { guard } from './fixtures.mjs';
for (const [name, viewport] of [['desktop', { width: 1256, height: 1032 }], ['mobile', { width: 390, height: 844 }]]) {
  test(`${name}: extracted variants stay visible and require review after browser-only reload`, async ({ page }, info) => {
    await page.setViewportSize(viewport); const log = await guard(page);
    await page.goto('/qa-therapy?reconcile');
    const rows = page.getByTestId('discharge-therapy-row');
    await expect(rows).toHaveCount(3);
    const beta = rows.nth(1);
    await expect(beta.getByText('Beta', { exact: true }).first()).toBeVisible();
    await expect(beta.getByLabel('Stato terapia', { exact: true })).toHaveValue('');
    await expect(beta.getByLabel('Data inizio *', { exact: true })).toHaveValue('');
    const source = beta.getByTestId('structured-therapy-source');
    await expect(source).toBeVisible();
    await expect(source).toContainText('Dati estratti automaticamente');
    await expect(source).toContainText('25 mg');
    await expect(source).toContainText('sospeso');
    await expect(beta.getByTestId('discharge-original-text')).toHaveCount(0);
    await expect(beta.getByRole('button', { name: 'Ho verificato questa terapia', exact: true })).toBeDisabled();
    const notes = beta.getByLabel('Note e indicazioni', { exact: true });
    await notes.fill('Revisione sintetica — dati da confermare');
    await page.reload();
    await expect(notes).toHaveValue('Revisione sintetica — dati da confermare');
    await expect(beta.getByLabel('Stato terapia', { exact: true })).toHaveValue('');
    await expect(source).toContainText('25 mg');
    await expect(rows.nth(2).getByTestId('structured-therapy-source')).toContainText('50 mg');
    await source.scrollIntoViewIfNeeded();
    const geometry = await source.evaluate(el => ({width:el.clientWidth,scroll:el.scrollWidth}));
    expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);
    await source.screenshot({ path:info.outputPath(`${name}-extracted-source.png`) });
    await page.screenshot({ path:info.outputPath(`${name}-candidate-review.png`) });
    expect(await page.evaluate(() => globalThis.syntheticOnly)).toBeUndefined();
    await beta.getByRole('button', { name: 'Lascia in bozza Beta', exact:true }).click();
    await page.reload();
    await expect(beta).toContainText('Resta in bozza');
    await expect(source).toContainText('25 mg');
    expect(log.errors).toEqual([]); expect(log.blocked).toEqual([]);
  });
  test(`${name}: proposals and summary retain escaped extraction evidence, not fabricated source text`, async ({ page }, info) => {
    await page.setViewportSize(viewport); const log = await guard(page);
    await page.goto('/qa-therapy?reconcile');
    await page.getByRole('button', {name:'QA: proposte',exact:true}).click();
    const proposal = page.getByRole('region', {name:'Nuove proposte dalle pagine aggiornate'});
    await expect(proposal).toBeVisible();
    await expect(proposal.getByTestId('structured-therapy-source')).toContainText('50 mg');
    await expect(proposal.getByTestId('discharge-original-text')).toHaveCount(0);
    await proposal.screenshot({path:info.outputPath(`${name}-proposal-source.png`)});
    await page.getByRole('button', {name:'QA: riepilogo',exact:true}).click();
    const sources = page.getByTestId('structured-therapy-source');
    await expect(sources).toHaveCount(3);
    await expect(sources.nth(1)).toContainText('<script>syntheticOnly</script>');
    await expect(sources.nth(1)).toContainText('25 mg');
    await expect(page.getByTestId('discharge-original-text')).toHaveCount(0);
    await sources.nth(1).scrollIntoViewIfNeeded();
    await page.screenshot({path:info.outputPath(`${name}-summary-source.png`)});
    expect(await page.evaluate(() => globalThis.syntheticOnly)).toBeUndefined();
    expect(log.errors).toEqual([]); expect(log.blocked).toEqual([]);
  });
}
