import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
const root='artifacts/task-validation/419-calendar-create';
const application='fa028c11ffe5dbfe514df8110e6ccf7f6b977602',baseline='d028e1ee4c5c44d96b5005362b28f54e5c05fee1';
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:20e6});assert.equal(r.status,0,'Protected Git action/check failed safely');return r.stdout.trim();};
const gate=JSON.parse(readFileSync(root+'/release-gate-receipt.json','utf8'));
assert.equal(gate.applicationCommit,application);assert.equal(gate.decision,'AUTHORIZED SCOPED APPLICATION PROMOTION');
assert.equal(git(['rev-parse','HEAD']),application);
git(['diff','--exit-code',application,'--','frontend','backend','prisma','package.json','package-lock.json']);
assert.equal(git(['ls-files','--others','--exclude-standard','--','frontend','backend','prisma']), '');
assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+baseline+'\\s'));
git(['diff','--check',baseline,application,'--','frontend']);
const receipt={action:'PUSH EXACT APPLICATION TO MAIN',authority:'Direct human authorization, independently assessed root release gate',application,expectedRemoteBaseline:baseline,sourceSha256:gate.sourceSha256,decision:'AUTHORIZED',at:new Date().toISOString(),excluded:'All QA artifact commits, unrelated dirty launchers, blocked issue candidates and dirty primary'};
writeFileSync(root+'/source-promotion-policy.json',JSON.stringify(receipt,null,2));
git(['push','origin',application+':refs/heads/main']);
assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+application+'\\s'));
writeFileSync(root+'/source-promotion-receipt.json',JSON.stringify({...receipt,result:'REMOTE MAIN EXACT APPLICATION VERIFIED',verifiedAt:new Date().toISOString()},null,2));
console.log('Exact application fa028 promoted; deployment/online/closure gates remain pending');
