import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/425-chart-scroll',app='b7ae14d120c1e70ccf72784206a505f8c48f975e',branch='codex/bug-425-chart-scroll',read=p=>JSON.parse(readFileSync(root+'/'+p)),sha=b=>createHash('sha256').update(b).digest('hex');
const configured=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:100e6});assert.equal(r.status,0,'Git proof check failed safely');return r.stdout.trim();};
const gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',maxBuffer:30e6,env:{...process.env,GH_TOKEN:configured.GITHUB_TOKEN||configured.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const proof=git(['rev-parse','HEAD']),publication=read('publication-manifest.json'),gate=read('release-gate-receipt.json'),deployment=read('deployment-receipt.json'),online=read('compiled-online/online-receipt.json');
assert.equal(online.applicationCommit,app);assert.equal(online.cases,16);assert.equal(gate.originalCriteriaPassed,4);assert.equal(publication.applicationCommit,app);assert.equal(publication.originalIndependentManifestFrozen,true);
assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof+'\\s'));assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+app+'\\s'));assert.ok(git(['diff','--name-only',app,proof]).split('\n').every(p=>p.startsWith(root+'/')));
for(const row of publication.files){const r=spawnSync('git',['show',proof+':'+row.path],{maxBuffer:100e6});assert.equal(r.status,0);assert.equal(sha(r.stdout),row.gitBlobSha256);}
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${root}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${root}`;
const images=[['Desktop: Salva terapia visibile e raggiungibile','compiled-online/browser03/doctor-1280-modal-save.png'],['Mobile emulato: azioni completamente visibili','compiled-online/browser03/doctor-390-modal-save.png'],['Tablet emulato: scroll raggiunge Al bisogno dopo la griglia','compiled-online/browser01/doctor-768-after-wheel.png']],verified=[];
for(const [,path]of images){const r=await fetch(raw+'/'+path);assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(sha(bytes),sha(readFileSync(root+'/'+path)));verified.push({path,http:200,sha256:sha(bytes)});}
const blocked=existsSync(root+'/ci-blocker-receipt.json'),ci=read(blocked?'ci-blocker-receipt.json':'ci-comparison.json');assert.equal(ci.applicationCommit,app);
const report=readFileSync(root+'/validation-report.md','utf8');assert.match(report,blocked?/## Final Decision\s+BLOCKED(?:\s|$)/:/## Final Decision\s+CLOSED — VERIFIED(?:\s|$)/);
if(!blocked){const check=spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',root],{encoding:'utf8'});assert.equal(check.status,0);writeFileSync(root+'/check-closure.log',check.stdout+check.stderr);}
const issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/425']));assert.equal(issue.body,read('original-issue.json').body);assert.equal(issue.state,'open');const comments=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/425/comments','--paginate']));let comment=comments.find(c=>c.body.includes(proof)&&c.body.includes(app));
const policy={decision:blocked?'AUTHORIZED PINNED PARTIAL COMMENT/BLOCKED LABEL ONLY':'AUTHORIZED PINNED VERIFIED COMMENT/ISSUE CLOSURE',authority:'Explicit human bug-fix/deploy/evidence authorization; root source-bound release decision, no gate waiver',applicationCommit:app,proofCommit:proof,verifiedImages:verified,issueMustRemainOpen:blocked,productionPatientTestMutations:0,at:new Date().toISOString()};writeFileSync(root+'/github-publication-policy.json',JSON.stringify(policy,null,2));
const body=`${blocked?'BLOCKED — CI infrastruttura esterna; issue lasciata APERTA.':'CLOSED — VERIFIED.'} Correzione [${app}](https://github.com/l2v-hub/ClinicOS/commit/${app}) online: Vercel ${deployment.vercel.id} READY, metadata/Git SHA esatti, alias/HTML/JS/CSS HTTP200 e hash invariati prima/dopo16 prove sul sito compilato.

I4 criteri originali PASS nello scope: unico proprietario verticale prevedibile per Clinica/Terapia; wheel sopra la griglia raggiunge «Al bisogno» dopo il calendario; focus Tab/ShiftTab non coperto da testate/azioni; overflow verificato su dimensioni effettive Chromium1150×1004,1280×720,1024×768,768×1024,390×844. Sono dimensioni browser/emulazione coarse-pointer, NON certificazione hardware/tablet fisico/touch/reparto.

La QA ha respinto il primo candidato796:10 controlli popup tagliati da transform persistente del pannello, anche se visibili nel DOM. Fallimento [142 artefatti immutabili](${tree}/failed-independent-qa-796/artifact-manifest.json) conservato. Disabilitata solo l’animazione trattenuta nel pannello cartella; ora330 focus-control hit-test corrispondono, containing block viewport, clipping effettivo0 e Salva visibile/raggiungibile su3 dimensioni. Il calendario della baseline67 raggiungeva già il contenuto dopo la griglia: nessuna regressione iniziale inventata; riprodotti5 campi coperti dal footer sticky, ora azioni nel flusso.

[QA indipendente](${tree}/independent-qa2/validation-report.md):16 gruppi browser PASS; [manifest160](${tree}/independent-qa2/artifact-manifest.json) SHA${gate.qaManifestSha256}. Root16 con ricette byte-identiche e16 sul bundle online. Denied nurse therapy.create non espone Nuova terapia né azioni slot. Tipi FE/BE/tsc-b/build Reactcompiler/secrets PASS; focused44/43PASS/1classico baseline e full1257/1245PASS/12 errori nominati identici/0 nuovi, NON verde globale. Scanner nativo sui3 file diff0 finding baseline/candidato, non audit globale CVE. Source1534 root SHA${gate.sourceSha256}; solo3 percorsi frontend, API/auth/schema/config/deps/backend invariati. Backend47a/Railwayed539 unchanged health200, nessun deploy backend necessario.

${blocked?`[CI${ci.candidateRun}](https://github.com/l2v-hub/ClinicOS/actions/runs/${ci.candidateRun}) fallita Initialize containers PRIMA del checkout: DockerHub non disponibile, stessa condizione esterna già ripetuta3 volte in424. Secret scan${ci.frontendSecretScanRun} PASS. [Receipt](${tree}/ci-blocker-receipt.json) e log sanitizzato conservati; CI applicativa NON verificata, NON il noto errore backend. Chiusura sospesa senza cambiare workflow/env/credenziali o ripetere retry invariati. Proseguo con426 indipendente.`:`[CI${ci.candidateRun}](https://github.com/l2v-hub/ClinicOS/actions/runs/${ci.candidateRun}) completata; [confronto esatto](${tree}/ci-comparison.json). ${ci.candidateConclusion==='success'?'Workflow success.':'Stesso singolo fallimento backend già accettato e stesso stage; test import downstream saltati, non dichiarati passanti.'} Secret scan${ci.frontendSecretScanRun} success. Nessun nuovo fallimento.`}

Prove fissate a ${proof}: [report](${tree}/validation-report.md), [deployment](${tree}/deployment-receipt.json), [receipt online](${tree}/compiled-online/online-receipt.json), [manifest canonicale/credenziali/ZIP](${tree}/publication-manifest.json), [trace popup](${raw}/compiled-online/browser03/doctor-1280-trace.zip), [risultati/guardie](${tree}/compiled-online/browser03/results.json), [video](${tree}/compiled-online/browser03), [receipt HTML](${tree}/compiled-online/playwright-report.html). HTML è un receipt Playwright-library, non il report del runner nativo. Tutte le API cliniche/auth/catalogo intercettate PRIMA rete;0 scritture su pazienti reali, fixture inventate, nessuna PHI negli screenshot. Nessuna falsa persistenza DB o body-lock; nessuna certificazione globale AT/clinica/provider.

${images.map(([label,path])=>`### ${label}\n![425 ${label}](${raw}/${path})`).join('\n\n')}`;
if(!comment)comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/425/comments','--method','POST','-f',`body=${body}`]));
if(blocked)gh(['issue','edit','425','--repo','l2v-hub/ClinicOS','--add-label','status-blocked']);else gh(['issue','close','425','--repo','l2v-hub/ClinicOS','--reason','completed']);
const current=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/425']));assert.equal(current.state,blocked?'open':'closed');assert.equal(current.body,read('original-issue.json').body);
const receipt={applicationCommit:app,proofCommit:proof,proofBranch:branch,githubProof:comment.html_url,state:current.state,decision:blocked?'PARTIAL EVIDENCE PUBLISHED; EXTERNAL CI BLOCKER, NO CLOSURE':'CLOSED — VERIFIED',canonicalHashesVerified:publication.files.length,images:verified,secretChecks:publication.secretChecks,zipEntriesChecked:publication.zipEntriesChecked,productionPatientTestMutations:0,at:new Date().toISOString()};writeFileSync(root+'/github-publication-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
