import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/425-chart-scroll',out=root+'/compiled-online',read=p=>JSON.parse(readFileSync(root+'/'+p)),sha=b=>createHash('sha256').update(b).digest('hex');
const deployment=read('deployment-receipt.json'),pre=read('compiled-online/pre-run.json');assert.equal(pre.applicationCommit,deployment.applicationCommit);
for(const r of pre.records)assert.equal(sha(readFileSync(out+'/recipes/'+r.name)),r.compiledRecipeSha256);
let cases=0;
for(const [name,count]of [['browser01',10],['browser02',3],['browser03',3]]){const result=read('compiled-online/'+name+'/results.json');assert.equal(result.results.length,count);for(const r of result.states)for(const key of ['unexpected','external','writes','pageErrors','consoleErrors','httpErrors'])assert.deepEqual(r[key],[]);if(name==='browser03')for(const r of result.results){assert.equal(r.clipping.length,110);assert.ok(r.clipping.every(f=>f.hit&&f.clipped.length===0&&f.fixedContainingBlock==='viewport'));assert.equal(r.saveBounds.hit,true);assert.ok(r.saveBounds.top>=0&&r.saveBounds.bottom<=r.viewport.height);}cases+=count;}
const response=await fetch(pre.bundleUrl);assert.equal(response.status,200);const actual=sha(Buffer.from(await response.arrayBuffer()));assert.equal(actual,pre.bundleSha256Before);assert.equal(actual,deployment.vercel.bundleSha256);
const htmlResponse=await fetch('https://clinicos-eosin.vercel.app/');assert.equal(htmlResponse.status,200);assert.equal(sha(Buffer.from(await htmlResponse.arrayBuffer())),pre.htmlSha256Before);
for(const style of pre.styleAssets){const css=await fetch(style.url);assert.equal(css.status,200);assert.equal(sha(Buffer.from(await css.arrayBuffer())),style.sha256);}
const receipt={applicationCommit:pre.applicationCommit,decision:'COMPILED ONLINE ACCEPTANCE VERIFIED',cases,bundleUrl:pre.bundleUrl,bundleSha256Before:pre.bundleSha256Before,bundleSha256After:actual,productionPatientTestMutations:0,apiGuard:'All clinical/auth/provider APIs intercepted before wire; only production static GET allowlist passes network',physicalTablet:false,at:new Date().toISOString()};writeFileSync(out+'/online-receipt.json',JSON.stringify(receipt,null,2));
writeFileSync(out+'/playwright-report.html',`<!doctype html><html lang="it"><meta charset="utf-8"><title>ClinicOS #425 — browser assertions</title><body><h1>#425 — ${cases} verifiche browser PASS</h1><p>Receipt di asserzioni Playwright library, non report del runner nativo. Commit ${pre.applicationCommit}; bundle SHA ${actual}. Solo fixture sintetiche, API intercettate prima della rete; nessuna scrittura su pazienti reali. Dimensioni browser, non certificazione hardware.</p><ul>${['browser01','browser02','browser03'].map(n=>`<li><a href="${n}/results.json">${n}: risultati, richieste e guardie</a></li>`).join('')}</ul></body></html>`);console.log(JSON.stringify(receipt));
