import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, mkdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
const root=resolve('artifacts/task-validation/426-room-actions/independent-qa3');
const sha=b=>createHash('sha256').update(b).digest('hex');
const before=JSON.parse(readFileSync(root+'/source-before.json')),after=JSON.parse(readFileSync(root+'/source-after.json'));
const commit='922a801f5c64cbeff02e2c14298d4dd5a16e622f';
assert.equal(before.head,commit);assert.equal(after.head,commit);assert.equal(before.status,'');assert.equal(after.status,'');assert.deepEqual(before.files,after.files);assert.deepEqual(before.untracked,[]);assert.deepEqual(after.untracked,[]);
const refs=before.files.map(f=>commit+':'+f.path),batch=spawnSync('git',['cat-file','--batch'],{input:refs.join('\n')+'\n',maxBuffer:160e6});assert.equal(batch.status,0);
let pos=0;const comparisons=[];
for(const file of before.files){const end=batch.stdout.indexOf(10,pos),header=batch.stdout.subarray(pos,end).toString(),[blob,type,length]=header.split(' ');assert.equal(type,'blob');const size=Number(length),data=batch.stdout.subarray(end+1,end+1+size),physical=readFileSync(file.path);pos=end+size+2;let normalization='exact';if(!physical.equals(data)){assert.ok(Buffer.from(physical.toString('utf8')).equals(physical),'Strict UTF8 '+file.path);assert.ok(Buffer.from(data.toString('utf8')).equals(data),'Strict Git UTF8 '+file.path);assert.ok(Buffer.from(physical.toString('utf8').replace(/\r\n/g,'\n')).equals(Buffer.from(data.toString('utf8').replace(/\r\n/g,'\n'))),'CRLF only '+file.path);normalization='strict UTF8 CRLF-only';}comparisons.push({path:file.path,blob,rawSha256:sha(physical),gitSha256:sha(data),normalization});}
writeFileSync(root+'/source-git-binding.json',JSON.stringify({commit,sourceFiles:comparisons.length,physicalSourceSha256:before.sourceSha256,unchangedBeforeAfter:true,comparisons},null,2));
const commands=JSON.parse(readFileSync(root+'/commands01/command-results.json'));
assert.equal(commands.records.find(x=>x.name==='focused').tests,23);assert.equal(commands.records.find(x=>x.name==='focused').fail,0);assert.equal(commands.records.find(x=>x.name==='full-regression').tests,1266);assert.equal(commands.records.find(x=>x.name==='full-regression').fail,12);assert.deepEqual(commands.newFailures,[]);
const recipes=JSON.parse(readFileSync(root+'/browser-recipes-frozen.json'));const runs=[];
for(const row of recipes){assert.equal(sha(readFileSync(root+'/recipes/'+row.recipe+'.mjs')),row.hash);const failed=row.recipe==='confirm-bounds',result=JSON.parse(readFileSync(root+'/'+row.output+'/test-results/'+(failed?'failure':'browser-results')+'.json'));if(!failed)assert.equal(result.applicationCommit,commit);else assert.match(result.message,/destructivebutton text wraps horizontally/);assert.equal(result.outcomes.length,failed?0:row.cases);for(const test of result.outcomes)assert.equal(test.status,'PASS');for(const state of result.states){for(const key of ['clinicalWrites','unexpected','external','pageErrors'])assert.deepEqual(state[key],[]);assert.equal(state.httpErrors.length,state.expectedErrors||0);assert.equal(state.errors.length,state.expectedErrors||0);assert.equal(state.requests.filter(r=>r.method==='DELETE').length,0);}runs.push({...row,status:failed?'FAIL':'PASS',outcomes:result.outcomes,expectedMock409:result.states.reduce((n,s)=>n+(s.expectedErrors||0),0)});}
assert.equal(runs.reduce((n,r)=>n+r.cases,0),21);
assert.ok(existsSync(root+'/server-stop-receipt.json'));
const diagnostic=JSON.parse(readFileSync(root+'/confirm-bounds-diagnostic01/test-results/failure.json'));assert.match(diagnostic.message,/destructivebutton text wraps horizontally/);
writeFileSync(root+'/validation-summary.json',JSON.stringify({applicationCommit:commit,verdict:'FAILED VALIDATION',sourcePhysicalSha256:before.sourceSha256,runs,browserCases:21,browserPassed:20,browserFailed:1,diagnosticRerun:'Same failure, separate folder; assertions unchanged, earlier geometry persistence only',focused:23,regression:{tests:1266,pass:1254,fail:12,newFailures:0},realMutations:0,actualDeleteRequests:0,limitations:'Before-wire synthetic Chromium actual Vite SPA; mock-only reload, not DB persistence, hardware, physical AT or deployment certification.'},null,2));
mkdirSync(root+'/playwright-report',{recursive:true});const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
writeFileSync(root+'/playwright-report/index.html','<!doctype html><meta charset="utf-8"><title>Independent QA3 #426 FAILED VALIDATION</title><h1>Library-assertion evidence summary, not native Playwright Test runner</h1><p>Source '+commit+'</p><p>20 Chromium real UI cases PASS; 1 FAILED: valid32W destructive button text clips/spills at390px, scroll435/client311. Diagnostic repeats failure. Synthetic before-wire APIs; no real mutation or DELETE. Types/build/scans and23 focused PASS;1266 regression with12 exact baseline failures, zero new.</p><ol>'+runs.flatMap(r=>r.outcomes.map(t=>'<li>'+escape(r.recipe+': '+t.name)+' — PASS</li>')).join('')+'</ol>');
const files=[];function walk(dir){for(const name of readdirSync(dir)){const p=dir+'/'+name;if(statSync(p).isDirectory())walk(p);else if(name!=='artifact-manifest.json'){const data=readFileSync(p);files.push({path:p.slice(root.length+1),bytes:data.length,sha256:sha(data)});}}}walk(root);files.sort((a,b)=>a.path.localeCompare(b.path));
writeFileSync(root+'/artifact-manifest.json',JSON.stringify({applicationCommit:commit,verdict:'FAILED VALIDATION',files,browserCases:21,browserPassed:20,browserFailed:1,recipeMap:recipes,physicalSourceSha256:before.sourceSha256,scope:'Only independent-qa3; raw bytes no relabeling, manifest excludes itself; separate diagnostic failure preserved'},null,2));
console.log('SEALED '+files.length+' files SHA256 '+sha(readFileSync(root+'/artifact-manifest.json')));
