import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/418-reading-recency',application='d028e1ee4c5c44d96b5005362b28f54e5c05fee1',branch='codex/bug-418-reading-recency';
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:10e6});assert.equal(r.status,0);return r.stdout.trim();};
const env=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',env:{...process.env,GH_TOKEN:env.GITHUB_TOKEN||env.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8'));
const deployment=read('deployment-receipt.json'),publication=read('publication-manifest.json'),ci=read('ci-comparison.json'),gate=read('release-gate-receipt.json');
assert.equal(deployment.applicationCommit,application);assert.equal(deployment.decision,'VERIFIED RELEASE');assert.equal(ci.frontendSecretScanConclusion,'success');assert.deepEqual(ci.newFailureNames,[]);assert.equal(gate.decision,'AUTHORIZED SCOPED APPLICATION PROMOTION');
const online=read('online-final/browser-results.json');assert.equal(online.outcomes.length,24);assert.ok(online.outcomes.every(o=>o.status==='PASS'));
assert.match(readFileSync(root+'/validation-report.md','utf8'),/## Final Decision\s+CLOSED — VERIFIED/);
assert.equal(spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',root],{encoding:'utf8'}).status,0);
assert.equal(git(['branch','--show-current']),branch);const proof=git(['rev-parse','HEAD']);assert.notEqual(proof,application);
assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof));assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+application));
git(['diff','--exit-code',application,proof,'--','frontend','backend','prisma','package.json','package-lock.json','scripts/build','scripts/run-node-tests.mjs']);
const sha=b=>createHash('sha256').update(b).digest('hex');
for(const row of publication.files){const r=spawnSync('git',['show',`${proof}:${row.path}`],{maxBuffer:100e6});assert.equal(r.status,0);assert.equal(sha(r.stdout),row.gitBlobSha256,'Published canonical drift '+row.path);}
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${root}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${root}`;
const images=[['Desktop reale, fixture locali','root-final/device/overview-actual-desktop.png'],['Panoramica compilata online, API sintetiche intercettate','online-final/screenshots/overview-recency.png'],['Rilevazione reparto compilata online, API sintetiche intercettate','online-final/screenshots/ward-recency.png']],verified=[];
for(const [,path]of images){const r=await fetch(`${raw}/${path}`);assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(sha(bytes),sha(readFileSync(root+'/'+path)));verified.push({path,http:r.status,sha256:sha(bytes)});}
const issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/418']));assert.equal(issue.state,'open');assert.equal(issue.body,read('issue-source.json').body,'Original acceptance changed; re-audit required');
const body=`CLOSED — VERIFIED: tutti i quattro criteri originali verificati.\n\nCorrezione [${application}](https://github.com/l2v-hub/ClinicOS/commit/${application}), Vercel ${deployment.vercel.id} READY con SHA Git esatto e [app online](https://clinicos-eosin.vercel.app/) verificata. Backend invariato, health200. Data/ora completa con anno e testo di recenza leggibile, vicino al valore: minuti, giorni e settimane. Lo storico non è descritto come attuale e non precompila nuovi valori. Confronto espanso con propria data sorgente. Invalidi, futuri e anni non rappresentabili espliciti senza crash; clock di sola visualizzazione. NEWS2 e soglie cliniche invariati.\n\n[Report completo](${tree}/validation-report.md): 65 test mirati, types/build/scansioni segreti PASS; nuovo ciclo indipendente immutabile21/21, rerun root21/21 e24 gruppi root ordinari e compilati online. Confronto reale Windows2133×1145 con dati sintetici di minuti/giorni/settimane e screenshot originale. Tablet/mobile sono emulazioni, non certificazione reparto, sole, guanti o AT. Cattura pixel reparto fallita: AX/DOM reale conservati, nessuna immagine sostitutiva. API intercettate prima della rete,0 scritture su pazienti di produzione. Reload con normale riaccesso al simulatore, non certificazione database.\n\nTrasparenza QA: ae2a fallì per formattazione anno. Un successivo gate tecnicoPASS resta BLOCKED: alcuni PNG standalone del preliminare19 e un JSON furono sovrascritti dal suo harness21; byte precedenti non recuperabili, trace/video/screenshot automatici per-run conservati. Non lo dichiariamo immutabile o recuperato. È stato eseguito un NUOVO ciclo21 con tutte destinazioni separate e originali sigillati; nessuna reinterpretazione del blocco.\n\nSuite1226/1214PASS/12fallimenti identici alla baseline417,0nuovi. CI: stesso singolo fallimento backend preesistente, downstream saltati; scansione frontend:3MEDIUM fuori dal diff. Nessuna dichiarazione di CI/sicurezza globalmente verdi.\n\nProve ${proof}: [nuovo gate indipendente](${tree}/independent-qa418-immutable/validation-report.md),[tentativo BLOCKED e inventario retention](${tree}/independent-qa418-final/validation-report.md),[ae2a FAILED](${tree}/independent-qa418/validation-report.md),[manifest/hash e scansione archivi](${tree}/publication-manifest.json),[deployment](${tree}/deployment-receipt.json),[CI](${tree}/ci-comparison.json),[trace online](${raw}/online-final/overview-trace.zip),[report browser](${tree}/online-final/playwright-report),[risultati](${tree}/online-final/test-results),[video](${tree}/online-final/video).\n\n${images.map(([label,path])=>`### ${label}\n![418 ${label}](${raw}/${path})`).join('\n\n')}`;
const comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/418/comments','--method','POST','-f',`body=${body}`]));
gh(['api','repos/l2v-hub/ClinicOS/issues/418','--method','PATCH','-f','state=closed','-f','state_reason=completed']);
const closed=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/418']));assert.equal(closed.state,'closed');assert.equal(closed.state_reason,'completed');
const receipt={applicationCommit:application,proofCommit:proof,proofBranch:branch,deployment:deployment.vercel.id,githubProof:comment.html_url,state:closed.state,closedAt:closed.closed_at,canonicalHashesVerified:publication.files.length,images:verified,secretChecks:publication.secretChecks,zipEntriesChecked:publication.zipEntriesChecked,productionPatientTestMutations:0};
writeFileSync(root+'/github-closure-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
