import {browser,setup,openAgenda,finish,expect,out,report,identity} from './fixture.mjs';
import {writeFileSync} from 'node:fs';
const primary=p=>p.getByRole('button',{name:'Nuovo appuntamento',exact:true});
const dialog=p=>p.getByRole('dialog',{name:'Nuovo Appuntamento'});
const help=p=>p.locator('#operator-appointment-creation-help');
const slots=p=>p.getByRole('button',{name:/^Crea appuntamento alle/});
const results=[];
const appointment=(ora,id='QA-419-APPOINTMENT')=>({id,operatorId:identity.id,patientId:null,patientName:'Persona Sintetica',data:'2026-10-09',ora,durata:30,tipologia:'visita',stato:'programmato',note:''});
async function run(name,options,fn){const ctx=await setup(options);let failed=null;const startedAt=new Date().toISOString();try{await openAgenda(ctx);await fn(ctx);await ctx.page.screenshot({path:`${out}/screenshots/${name}.png`});}catch(error){failed=error;try{await ctx.page.screenshot({path:`${out}/screenshots/${name}-failed.png`});}catch{}}try{await finish(ctx,name);}catch(error){failed??=error;}results.push({name,status:failed?'FAIL':'PASS',startedAt,finishedAt:new Date().toISOString(),...(failed?{error:failed.message}:{})});writeFileSync(`${out}/test-results/run-progress.json`,JSON.stringify(results,null,2));console.log(`${failed?'FAIL':'PASS'} ${name}`);}
try{
 await run('empty-primary-explicit-context',{},async({page})=>{await expect(help(page)).toBeVisible();await expect(help(page)).toContainText('Nessun appuntamento in questa giornata. Usa Nuovo appuntamento');await expect(primary(page)).toBeEnabled();await expect(primary(page)).toHaveAttribute('aria-describedby','operator-appointment-creation-help');await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=date]')).toHaveValue('2026-10-09');await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:00');await expect(dialog(page).getByRole('combobox',{name:/Paziente/})).toHaveValue('');await expect(dialog(page).getByText('Seleziona un paziente per salvare l’appuntamento. Cerca per nome, cognome o codice fiscale.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeDisabled();});
 await run('daily-keyboard-both-keys',{},async({page})=>{const slot=page.getByRole('button',{name:'Crea appuntamento alle 10:00',exact:true});await slot.focus();await page.keyboard.press('Enter');await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=time]')).toHaveValue('10:00');await page.getByRole('button',{name:'Annulla',exact:true}).click();await slot.focus();await page.keyboard.press('Space');await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=time]')).toHaveValue('10:00');});
 await run('present-and-hidden-occupied', {appointments:[appointment('08:00')]},async({page})=>{await expect(page.locator('.agt-apt-card')).toHaveCount(1);await expect(help(page)).not.toContainText('Nessun appuntamento');await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:30');await page.getByRole('button',{name:'Annulla',exact:true}).click();await page.getByRole('button',{name:/^Completato/}).click();await expect(page.locator('.agt-apt-card')).toHaveCount(0);await expect(page.getByRole('button',{name:'Crea appuntamento alle 08:00',exact:true})).toHaveCount(0);await page.locator('.agt-slot').first().click();await expect(dialog(page)).toHaveCount(0);await expect(help(page)).not.toContainText('Nessun appuntamento');await primary(page).click();await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:30');});
 await run('past-day-no-hidden-opener',{},async({page})=>{await page.getByRole('button',{name:'Intervallo precedente'}).click();await expect(primary(page)).toBeDisabled();await expect(help(page)).toBeVisible();await expect(help(page)).toContainText('Giorno passato: non puoi creare nuovi appuntamenti. Scegli oggi o una data futura.');await expect(slots(page)).toHaveCount(0);await page.locator('.agt-slot').first().click();await page.locator('.agt-slot').first().dispatchEvent('keydown',{key:'Enter'});await expect(dialog(page)).toHaveCount(0);});
 await run('after-hours-visible-next-date-path',{time:'2026-10-09T23:09:00+02:00'},async({page})=>{await expect(primary(page)).toBeDisabled();await expect(help(page)).toBeVisible();await expect(help(page)).toContainText('Nessuna fascia libera nelle ore rimanenti di oggi. Scegli una data futura.');await expect(slots(page)).toHaveCount(0);await page.locator('.agt-slot').first().click();await expect(dialog(page)).toHaveCount(0);await page.getByRole('button',{name:'Intervallo successivo'}).click();await expect(primary(page)).toBeEnabled();await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=date]')).toHaveValue('2026-10-10');await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:00');});
 await run('full-day-visible-reason',{appointments:Array.from({length:22},(_,i)=>appointment(`${String(8+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`,`QA-FULL-${i}`))},async({page})=>{await expect(page.locator('.agt-apt-card')).toHaveCount(22);await expect(primary(page)).toBeDisabled();await expect(help(page)).toBeVisible();await expect(help(page)).toContainText('Nessuna fascia libera');await expect(slots(page)).toHaveCount(0);});
 await run('denied-role-daily-and-weekly',{allowed:false},async({page})=>{await expect(primary(page)).toBeDisabled();await expect(help(page)).toBeVisible();await expect(help(page)).toContainText('Il tuo ruolo non può creare appuntamenti.');await expect(slots(page)).toHaveCount(0);await page.locator('.agt-slot').first().click();await expect(dialog(page)).toHaveCount(0);await page.getByRole('button',{name:'Settimana',exact:true}).click();await expect(page.getByRole('button',{name:/^Crea appuntamento il/})).toHaveCount(0);await page.locator('.agt-week-cell').first().click();await page.locator('.agt-week-cell').first().dispatchEvent('keydown',{key:' '});await expect(dialog(page)).toHaveCount(0);});
 await run('weekly-keyboard-and-past-policy',{},async({page})=>{await page.getByRole('button',{name:'Settimana',exact:true}).click();await expect(page.getByRole('button',{name:'Crea appuntamento il 2026-10-08 alle 08:00',exact:true})).toHaveCount(0);const slot=page.getByRole('button',{name:'Crea appuntamento il 2026-10-10 alle 10:00',exact:true});await slot.focus();await page.keyboard.press('Enter');await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=date]')).toHaveValue('2026-10-10');await expect(dialog(page).locator('input[type=time]')).toHaveValue('10:00');await page.getByRole('button',{name:'Annulla',exact:true}).click();await slot.focus();await page.keyboard.press('Space');await expect(dialog(page)).toBeVisible();});
 await run('patient-selection-required-and-enables',{},async({page})=>{await primary(page).click();await expect(dialog(page)).toBeVisible();const picker=dialog(page).getByRole('combobox',{name:/Paziente/});await expect(picker).toHaveAttribute('aria-required','true');await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeDisabled();await picker.fill('Sintetica');await page.getByRole('option',{name:/Persona/}).click();await expect(picker).toHaveValue(/Sintetica/);await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeEnabled();});
 await run('minute-tick-updates-visible-availability',{time:'2026-10-09T18:30:00+02:00'},async({page})=>{await expect(primary(page)).toBeEnabled();await expect(page.getByRole('button',{name:'Crea appuntamento alle 18:30',exact:true})).toBeVisible();await page.clock.fastForward(61000);await expect(primary(page)).toBeDisabled();await expect(slots(page)).toHaveCount(0);await expect(help(page)).toContainText('Nessuna fascia libera nelle ore rimanenti');});
 await run('click-time-recheck-without-render-tick',{time:'2026-10-09T18:30:00+02:00'},async({page})=>{await expect(primary(page)).toBeEnabled();await page.clock.setSystemTime(new Date('2026-10-09T18:31:00+02:00'));await primary(page).click();await expect(dialog(page)).toHaveCount(0);const stale=page.locator('.agt-slot').last();await stale.click();await stale.dispatchEvent('keydown',{key:'Enter'});await expect(dialog(page)).toHaveCount(0);await page.clock.fastForward(60001);await expect(primary(page)).toBeDisabled();await expect(help(page)).toContainText('Nessuna fascia libera');});
 await run('permission-revocation-and-restoration',{},async({page,state})=>{await primary(page).click();await expect(dialog(page)).toBeVisible();const initial=state.requests.filter(r=>r.path==='/auth/me').length;state.allowed=false;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect.poll(()=>state.requests.filter(r=>r.path==='/auth/me').length).toBeGreaterThan(initial);await expect(dialog(page)).toHaveCount(0);await expect(primary(page)).toBeDisabled();await expect(help(page)).toContainText('Il tuo ruolo non può creare appuntamenti.');state.allowed=true;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(primary(page)).toBeEnabled();await expect(dialog(page)).toHaveCount(0);await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(dialog(page).getByRole('combobox',{name:/Paziente/})).toHaveValue('');});
 await run('mobile-visible-help-and-context',{mobile:true},async({page})=>{await expect(primary(page)).toBeEnabled();await expect(help(page)).toBeVisible();await expect(help(page)).toContainText('Seleziona il paziente nel modulo.');const bounds=await help(page).boundingBox();expect(bounds.x+bounds.width).toBeLessThanOrEqual(391);await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:00');await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeDisabled();});
}finally{report(results);await browser.close();}
if(results.length!==13||results.some(r=>r.status!=='PASS'))process.exitCode=1;
