import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/428-operator-role',read=p=>JSON.parse(readFileSync(root+'/'+p)),own=read('root-rerun/source-before.json'),other=read('independent-qa/source-before.json'),app=read('frozen-source.json').applicationCommit,sha=b=>createHash('sha256').update(b).digest('hex'),decode=new TextDecoder('utf-8',{fatal:true});
assert.equal(own.head,app);assert.equal(other.head,app);assert.equal(own.status,'');assert.equal(other.status,'');assert.deepEqual(own.untracked,[]);assert.deepEqual(other.untracked,[]);assert.deepEqual(own.files.map(f=>f.path),other.files.map(f=>f.path));assert.equal(own.files.length,1546);
const r=spawnSync('git',['cat-file','--batch'],{input:own.files.map(f=>app+':'+f.path).join('\n')+'\n',maxBuffer:100e6,windowsHide:true});assert.equal(r.status,0);let offset=0;const rows=[];
for(const [i,file]of own.files.entries()){const end=r.stdout.indexOf(10,offset),header=r.stdout.subarray(offset,end).toString('ascii'),m=header.match(/^([a-f0-9]{40}) blob (\d+)$/);assert.ok(m);const size=Number(m[2]),blob=r.stdout.subarray(end+1,end+1+size);offset=end+2+size;const checks=[];
 for(const [path,receipt,label]of [[file.path,file,'root'],['C:/w-428-qa2/'+file.path,other.files[i],'independent']]){const raw=readFileSync(path);assert.equal(sha(raw),receipt.sha256);let equality='EXACT';if(!raw.equals(blob)){assert.equal(decode.decode(raw).replaceAll('\r\n','\n'),decode.decode(blob).replaceAll('\r\n','\n'),file.path);equality='STRICT UTF8 CRLF ONLY';}checks.push({label,rawSha256:sha(raw),equality});}rows.push({path:file.path,gitBlob:m[1],gitBlobSha256:sha(blob),checks});}
assert.equal(offset,r.stdout.length);writeFileSync(root+'/root-rerun/source-git-binding.json',JSON.stringify({applicationCommit:app,decision:'ROOT VERIFIED BOTH PHYSICAL CHECKOUTS AGAINST CLEAN IMMUTABLE GIT SOURCE',files:rows,sourceFiles:rows.length,rootRawSha256:own.sourceSha256,independentRawSha256:other.sourceSha256},null,2));console.log('Both1546 physical source inputs bound to actual cleanGit candidate, strictCRLF-only');
