import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyCanonical} from './canonical-blobs.mjs';
const root='artifacts/task-validation/428-operator-role',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,'')),app=read('frozen-source.json').applicationCommit,branch='codex/bug-428-operator-role',sha=b=>createHash('sha256').update(b).digest('hex');
const configured=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:100e6,windowsHide:true});assert.equal(r.status,0,'Proof check failed safely');return r.stdout.trim();};
const gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',maxBuffer:30e6,windowsHide:true,env:{...process.env,GH_TOKEN:configured.GITHUB_TOKEN||configured.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const proof=git(['rev-parse','HEAD']),publication=read('publication-manifest.json'),gate=read('release-gate-receipt.json'),deploy=read('deployment-receipt.json'),online=read('compiled-online/online-receipt.json'),ci=read('ci-comparison.json');
for(const r of [publication,gate,deploy,online,ci])assert.equal(r.applicationCommit,app);assert.equal(online.cases,gate.rootIndependentRerun);assert.equal(gate.originalCriteriaPassed,4);assert.equal(publication.originalIndependentManifestFrozen,true);assert.equal(deploy.decision,'VERIFIED RELEASE');assert.equal(deploy.vercel.state,'READY');assert.equal(deploy.backend.actualCheckoutSha,app);assert.equal(deploy.backend.railwayStatus,'SUCCESS');assert.equal(gate.realIsolatedDbEach,4);assert.deepEqual(ci.newFailureNames,[]);assert.equal(ci.frontendSecretScanConclusion,'success');
assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof+'\\s'));assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+app+'\\s'));assert.ok(git(['diff','--name-only',app,proof]).split('\n').every(p=>p.startsWith(root+'/')));verifyCanonical(publication.files,proof);
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${root}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${root}`,images=read('public-images.json'),verified=[];
for(const {label,path}of images){assert.ok(label&&path.startsWith('compiled-online/'));const r=await fetch(raw+'/'+path);assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(sha(bytes),sha(readFileSync(root+'/'+path)));verified.push({path,http:200,sha256:sha(bytes)});}assert.ok(verified.length>=3);
assert.match(readFileSync(root+'/validation-report.md','utf8'),/## Final Decision\s+CLOSED — VERIFIED(?:\s|$)/);const check=spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',root],{encoding:'utf8',windowsHide:true});assert.equal(check.status,0);writeFileSync(root+'/check-closure.log',check.stdout+check.stderr);
const original=read('original-issue.json').issue.body,issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/428']));assert.equal(issue.body,original);assert.ok(['open','closed'].includes(issue.state));const actor=JSON.parse(gh(['api','user'])).login;assert.ok(actor);const comments=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/428/comments','--paginate','--slurp'])).flat();
const body=`CLOSED — VERIFIED. Correzione [${app}](https://github.com/l2v-hub/ClinicOS/commit/${app}) online: Vercel ${deploy.vercel.id} READY/commit e alias verificati; backend [workflow ${deploy.backend.runId}](${deploy.backend.runUrl}), checkout esatto, Railway ${deploy.backend.railwayDeploymentId} SUCCESS/image digest, health200. HTML/JS/CSS invariati prima/dopo ${online.cases} gruppi sul bundle pubblicato.

Tutti4 criteri originali PASS: dashboard e tabella condividono etichette e qualifica, esplicitamente distinte dai permessi; valori mancanti/legacy non sono più vuoti; ruoli normalizzati/legacy presentati coerentemente e custom visibilmente da verificare; apertura/annullamento e modifiche non correlate non cambiano il ruolo o le autorizzazioni. Il backend non inventa Medico per dati mancanti. L’editor conserva la voce corrente e omette ruolo invariato nel salvataggio; solo una scelta esplicita cambia la funzione professionale. Nessuna modifica schema, autorizzazioni, workflow, dipendenze o configurazione.

[Nuova QA indipendente](${tree}/independent-qa/validation-report.md):56 gruppi PASS; ${gate.immutableQaFiles} [artefatti immutabili](${tree}/independent-qa/manifest.json), manifest SHA ${gate.qaManifestSha256}. Root56 e online56 con ricette byte-identiche. Matrice16 valori desktop/mobile, verifica/tastiera/selezione corrente,12 PUT sintetici senza ruolo e2 scelte esplicite; sei prove di editor realmente visibile con solo scroll nativo. La baseline7680 riproduce il difetto in2 casi separati. Tutti i tentativi falliti e ricette originali conservati; nessun requisito indebolito. [Screenshot realmente ispezionati](${tree}/visual-review.md). Limite dichiarato: il select nativo stretto può troncare opzioni lunghe; valore/opzione completa e intera etichetta della tabella/card verificati, non ridisegno globale.

45/45 test mirati, tipi FE/BE/tsc-b/build/secrets PASS. Regressione1292:1280PASS/12 errori nominati identici alla baseline/0 nuovi, NON verde globale. Scanner nativo12 file0 nuovi finding, non audit CVE globale. ${gate.sourceFiles} sorgenti fisici immutati e legati al Git; SHA root ${gate.sourceSha256}. Cross-checkout strictUTF8 CRLF→LF solo. 4/4 test API reali con PostgreSQL nuovo e57 migrazioni esistenti, sia QA sia root: GET/PUT e reload preservano valori raw/null, User.role e policy; rifiuti401/403 senza mutazioni. Il caso senza opt-in da cwd backend è4 SKIP/0 scritture, NON prova di persistenza. Cache-Control mancante sui rifiuti dell’outer gate resta limite preesistente, esplicitamente non riparato.

[CI ${ci.candidateRun}](https://github.com/l2v-hub/ClinicOS/actions/runs/${ci.candidateRun}): ${ci.candidateConclusion==='success'?'success':'stesso singolo errore backend e stesso stage della baseline422; downstream saltati, non dichiarati passanti'},0 nuovi; [confronto](${tree}/ci-comparison.json). Secret scan ${ci.frontendSecretScanRun} success.

Proof ${proof}: [report](${tree}/validation-report.md), [gate](${tree}/release-gate-receipt.json), [deployment](${tree}/deployment-receipt.json), [online](${tree}/compiled-online/online-receipt.json), [manifest canonicale/credenziali/ZIP](${tree}/publication-manifest.json), [risultati/trace/video](${tree}/compiled-online). HTML receipt delle asserzioni Playwright-library, non report runner nativo. API intercettate PRIMA rete e solo asset statici GET online;14 PUT browser consentiti sono mock sintetici, persistenza reale solo su cluster locale nuovo. Zero scritture pazienti reali/PHI, nessuna certificazione hardware/AT/sole diretto o accettazione clinica audit429.

${images.map(({label,path})=>`### ${label}\n![428 ${label}](${raw}/${path})`).join('\n\n')}`;
let comment=comments.find(c=>c.user?.login===actor&&c.body===body);if(issue.state==='closed')assert.ok(comment,'Already-closed outcome requires exact authorized proof comment');
writeFileSync(root+'/github-publication-policy.json',JSON.stringify({decision:'AUTHORIZED EXACT PINNED COMMENT AND VERIFIED ISSUE CLOSURE',authority:'Direct human authorization plus independent/root/deployed/CI/publicproof gates',applicationCommit:app,proofCommit:proof,verifiedImages:verified,actor,productionPatientTestMutations:0,at:new Date().toISOString()},null,2));
if(!comment)comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/428/comments','--method','POST','-f',`body=${body}`]));assert.equal(comment.body,body);assert.equal(comment.user?.login,actor);if(issue.state==='open')gh(['issue','close','428','--repo','l2v-hub/ClinicOS','--reason','completed']);
const fresh=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/428']));assert.equal(fresh.state,'closed');assert.equal(fresh.body,original);const receipt={applicationCommit:app,proofCommit:proof,proofBranch:branch,githubProof:comment.html_url,state:fresh.state,canonicalHashesVerified:publication.files.length,images:verified,secretChecks:publication.secretChecks,zipEntriesChecked:publication.zipEntriesChecked,decision:'CLOSED — VERIFIED',productionPatientTestMutations:0,at:new Date().toISOString()};writeFileSync(root+'/github-publication-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
