import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {verifyCanonical} from './canonical-blobs.mjs';
const root='artifacts/task-validation/428-operator-role',app=JSON.parse(readFileSync(root+'/frozen-source.json')).applicationCommit,branch='codex/bug-428-operator-role',sha=b=>createHash('sha256').update(b).digest('hex');
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:100e6,windowsHide:true});assert.equal(r.status,0,'Protected proof operation failed safely');return r.stdout.trim();};
const manifest=JSON.parse(readFileSync(root+'/publication-manifest.json'));assert.equal(manifest.applicationCommit,app);assert.equal(manifest.originalIndependentManifestFrozen,true);assert.equal(git(['branch','--show-current']),branch);assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+app+'\\s'));
const staged=git(['diff','--cached','--name-only']).split('\n').filter(Boolean);assert.ok(staged.length);assert.ok(staged.every(p=>p.startsWith(root+'/')));verifyCanonical(manifest.files);
const online=JSON.parse(readFileSync(root+'/compiled-online/online-receipt.json')),gate=JSON.parse(readFileSync(root+'/release-gate-receipt.json'));assert.equal(online.applicationCommit,app);assert.equal(online.cases,gate.rootIndependentRerun);
const parentProof=git(['rev-parse','HEAD']),remote=git(['ls-remote','origin','refs/heads/'+branch]);assert.ok(remote.startsWith(parentProof+'\t')||(parentProof===app&&remote===''));
const policy={decision:'AUTHORIZED SOURCE-BOUND SYNTHETIC EVIDENCE COMMIT/PUSH',authority:'Direct human authorization; independent/root/compiled/source/deployment verified; GitHub closure separately gated',applicationCommit:app,parentProof,branch,scope:root,canonicalFiles:manifest.files.length,secretChecks:manifest.secretChecks,zipMembers:manifest.zipEntriesChecked,productionPatientTestMutations:0,at:new Date().toISOString()};
const policyPath=root+'/proof-push-policy-'+parentProof.slice(0,12)+'.json',bytes=Buffer.from(JSON.stringify(policy,null,2)),configured=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;let checks=0;
for(const [key,value]of Object.entries(configured))if(/TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL|CONNECTION_STRING|DATABASE_URL/.test(key)&&typeof value==='string'&&value.length>=8){assert.equal(bytes.toString('utf8').includes(value),false,'Credential detected, no value emitted');checks++;}
writeFileSync(policyPath,bytes);git(['add','-f','--',policyPath]);const blob=spawnSync('git',['show',':'+policyPath],{maxBuffer:100e6});assert.equal(blob.status,0);assert.equal(sha(blob.stdout),sha(bytes));manifest.files.push({path:policyPath,sha256:sha(bytes),gitBlobSha256:sha(blob.stdout),exportNormalization:'none'});manifest.secretChecks+=checks;
writeFileSync(root+'/publication-manifest.json',JSON.stringify(manifest,null,2));git(['add','-f','--',root+'/publication-manifest.json']);git(['commit','-m','test(operators): publish source-bound issue 428 validation evidence']);const proof=git(['rev-parse','HEAD']);assert.ok(git(['diff','--name-only',app,proof]).split('\n').every(p=>p.startsWith(root+'/')));git(['push','origin','HEAD:refs/heads/'+branch]);assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof+'\\s'));console.log(JSON.stringify({applicationCommit:app,proofCommit:proof,branch,decision:'PROOF BRANCH VERIFIED; CLOSURE SEPARATELY GATED'}));
