import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect,setup,finish,states as activityStates,labels,backgrounds} from './transport.mjs';
const out=resolve(process.argv[2]);assert.ok(process.argv[2]);assert.equal(existsSync(out),false);for(const p of ['screenshots','video','trace','test-results','playwright-report'])mkdirSync(out+'/'+p,{recursive:true});
const browser=await chromium.launch({headless:true}),outcomes=[],guards=[],contexts=[],measurements=[];
async function check(name,fn){await fn();outcomes.push({name,status:'PASS'});console.log('PASS '+name);}
async function hierarchy(page,count,legend=true){await expect(page.locator('.agt-state-filter__caption')).toBeVisible();await expect(page.locator('.agt-state-filter__caption')).toHaveText('Appuntamenti nel periodo selezionato');await expect(page.getByRole('group',{name:'Filtra per stato',exact:true}).getByRole('button',{name:'Tutti gli stati '+count,exact:true})).toBeVisible();if(legend){await expect(page.getByRole('group',{name:'Stati delle attività',exact:true})).toBeVisible();for(const label of [...labels,'Disponibile'])await expect(page.locator('.agt-legend__item').filter({hasText:label})).toBeVisible();}}
async function adminIdentity(page){const dots=await page.locator('.agt-view .agt-op-dot').evaluateAll(nodes=>nodes.map(n=>({display:getComputedStyle(n).display,width:n.getBoundingClientRect().width})));expect(dots.length).toBeGreaterThan(0);for(const dot of dots){expect(dot.display).toBe('none');expect(dot.width).toBe(0);}}
async function cards(page,view,count=8){const selector=view==='Giorno'?'.agt-admin-grid .agt-apt-card':view==='Settimana'?'.agt-week-apt':'.agt-month-apt';const all=page.locator(selector);await expect(all).toHaveCount(count);for(let i=0;i<activityStates.length;i++){const row=all.filter({has:page.locator('.unused')});const matching=page.locator(selector+'.agt-apt-card--'+activityStates[i]);expect(await matching.count()).toBeGreaterThan(0);for(const card of await matching.all()){await expect(card).toBeVisible();await expect(card).toContainText(labels[i]);const style=await card.evaluate(n=>{const c=getComputedStyle(n);return {background:c.backgroundColor,leftWidth:c.borderLeftWidth,text:n.textContent};});expect(style.background).toBe(backgrounds[i]);if(view!=='Giorno'){expect(style.leftWidth).toBe('0px');await expect(card).toContainText('Sintetico');}measurements.push({view,state:activityStates[i],...style});}}}
async function capture(page,name){await page.screenshot({path:out+'/screenshots/'+name+'.png',fullPage:true});}
async function close(ctx,name){await finish(ctx,out,name);}
try{
 for(const [width,height,device]of [[1280,720,'desktop'],[390,844,'mobile']]){
  const ctx=await setup(browser,out,width,height);contexts.push(ctx);guards.push(ctx.state);const {page}=ctx;
  for(const view of ['Giorno','Settimana','Mese']){
   await check(device+' '+view+' mixed states: names/state words/semantic surfaces',async()=>{await page.getByRole('button',{name:view,exact:true}).click();await hierarchy(page,8);await adminIdentity(page);await cards(page,view);await capture(page,device+'-'+view.toLowerCase()+'-mixed');});
   await check(device+' '+view+' grayscale retains exact names and all state words',async()=>{await page.addStyleTag({content:'html { filter: grayscale(1); }'});expect(await page.evaluate(()=>getComputedStyle(document.documentElement).filter)).toBe('grayscale(1)');await hierarchy(page,8);await cards(page,view);await capture(page,device+'-'+view.toLowerCase()+'-grayscale');await page.evaluate(()=>document.querySelectorAll('style').forEach(s=>{if(s.textContent==='html { filter: grayscale(1); }')s.remove();}));});
  }
  await check(device+' native state filter keyboard and toggle reset',async()=>{const group=page.getByRole('group',{name:'Filtra per stato',exact:true}),button=group.getByRole('button',{name:'Programmato 2',exact:true});await button.focus();await page.keyboard.press('Enter');await expect(button).toHaveAttribute('aria-pressed','true');await expect(page.locator('.agt-month-apt')).toHaveCount(2);await expect(page.locator('.agt-month-apt').first()).toContainText('Programmato');await page.keyboard.press('Enter');await expect(button).toHaveAttribute('aria-pressed','false');await expect(page.locator('.agt-month-apt')).toHaveCount(8);});
  await check(device+' native operator filter preserves names and loaded range',async()=>{await page.getByRole('button',{name:'Settimana',exact:true}).click();const group=page.getByRole('group',{name:'Filtra agenda per operatore',exact:true}),button=group.getByRole('button',{name:'Alfa',exact:true});await button.focus();await page.keyboard.press('Enter');await expect(button).toHaveAttribute('aria-pressed','true');await hierarchy(page,4);await cards(page,'Settimana',4);await page.keyboard.press('Enter');await expect(button).toHaveAttribute('aria-pressed','false');await hierarchy(page,8);});
  await close(ctx,device+'-mixed');
  const empty=await setup(browser,out,width,height,{empty:true});contexts.push(empty);guards.push(empty.state);
  for(const view of ['Giorno','Settimana','Mese'])await check(device+' '+view+' empty period explicit hierarchy, operator names not colored',async()=>{await empty.page.getByRole('button',{name:view,exact:true}).click();await hierarchy(empty.page,0);await adminIdentity(empty.page);await expect(empty.page.locator('.agt-apt-card,.agt-week-apt,.agt-month-apt')).toHaveCount(0);if(view==='Giorno')await expect(empty.page.locator('.agt-col-hdr__name').first()).toHaveText('Alfa Sintetico');await capture(empty.page,device+'-'+view.toLowerCase()+'-empty');});await close(empty,device+'-empty');
 }
 const shared=await setup(browser,out,1280,720,{count:11});contexts.push(shared);guards.push(shared.state);
 await check('11 operators real palette repeats blue, identity suppressed, mixed same-operator states',async()=>{await expect(shared.page.locator('.agt-col-hdr__name')).toHaveCount(11);const colors=await shared.page.locator('.agt-col-hdr .agt-op-dot').evaluateAll(nodes=>nodes.map(n=>n.style.backgroundColor));expect(colors[0]).toBe(colors[10]);expect(colors[0]).toBe('rgb(47, 107, 237)');await adminIdentity(shared.page);await cards(shared.page,'Giorno');await capture(shared.page,'eleven-operators-shared-color');});await close(shared,'shared-palette');
 const loading=await setup(browser,out,1280,720,{hold:true});contexts.push(loading);guards.push(loading.state);
 await check('held synthetic GET shows loading rather than invented empty-day claim',async()=>{await expect(loading.page.getByText('Caricamento agenda…',{exact:true})).toBeVisible();await hierarchy(loading.page,0);await expect(loading.page.locator('.agt-admin-day-wrap')).toHaveCount(0);await expect(loading.page.getByText(/Nessun appuntamento/)).toHaveCount(0);await capture(loading.page,'loading-hierarchy');loading.release();await hierarchy(loading.page,8);await cards(loading.page,'Giorno');});await close(loading,'loading');
 for(const [width,height,device]of [[1280,720,'desktop'],[390,844,'mobile']]){
  const ctx=await setup(browser,out,width,height,{operator:true});contexts.push(ctx);guards.push(ctx.state);
  await check(device+' HMI shared caption/count and unchanged day semantic palette',async()=>{await expect(ctx.page.locator('.agt-view--hmi')).toBeVisible();await hierarchy(ctx.page,4,false);for(const [i,color]of ['rgb(234, 241, 254)','rgb(253, 243, 226)','rgb(230, 246, 239)','rgb(238, 241, 246)'].entries()){const card=ctx.page.locator('.agt-day-card .agt-apt-card--'+activityStates[i]);await expect(card).toBeVisible();await expect(card).toContainText(labels[i]);expect(await card.evaluate(n=>getComputedStyle(n).backgroundColor)).toBe(color);}await capture(ctx.page,device+'-hmi-day');});
  for(const view of ['Settimana','Mese'])await check(device+' HMI '+view+' shared legend/count and unchanged identity dot',async()=>{await ctx.page.getByRole('button',{name:view,exact:true}).click();await hierarchy(ctx.page,4);const dot=ctx.page.locator('.agt-op-chip .agt-op-dot');if(device==='desktop'){await expect(dot).toBeVisible();expect(await dot.evaluate(n=>getComputedStyle(n).display)).not.toBe('none');}for(const label of labels)await expect(ctx.page.locator('.agt-inline-meta').filter({hasText:label})).toHaveCount(1);await capture(ctx.page,device+'-hmi-'+view.toLowerCase());});await close(ctx,device+'-hmi');
 }
 writeFileSync(out+'/test-results/browser-results.json',JSON.stringify({applicationCommit:process.env.SOURCE_COMMIT,outcomes,states:guards,measurements,fixtureTransport:'Actual repository SPA, API interception before wire, static GET only beyond fixture. Grayscale CSS rendering only; no hardware/real-data certification.'},null,2));
 writeFileSync(out+'/playwright-report/index.html','<!doctype html><meta charset="utf-8"><h1>427 independent Playwright library assertions</h1><p>This is an assertion receipt, not the native Playwright Test reporter.</p><pre>'+JSON.stringify(outcomes,null,2).replaceAll('&','&amp;').replaceAll('<','&lt;')+'</pre>');
}catch(e){for(const [i,c]of contexts.entries()){await c.page.screenshot({path:out+'/screenshots/failure-'+i+'.png',fullPage:true}).catch(()=>{});await c.context.tracing.stop({path:out+'/trace/failure-'+i+'.zip'}).catch(()=>{});}writeFileSync(out+'/test-results/failure.json',JSON.stringify({message:e.message,stack:e.stack,outcomes,states:guards},null,2));throw e;}finally{for(const c of contexts)await c.context.close().catch(()=>{});await browser.close();}
