import assert from 'node:assert/strict';
import {readFileSync,readdirSync,statSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
const root=resolve(process.argv[2]);assert.ok(process.argv[2]);
const read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,''));
const before=read('source-before.json'),after=read('source-after.json');assert.equal(before.head,'7680ec0b25c61de5745f296d91e370b575de9c00');assert.equal(before.head,after.head);assert.equal(before.status,'');assert.equal(after.status,'');assert.equal(before.files.length,1540);assert.deepEqual(before.files,after.files);assert.equal(before.sourceSha256,after.sourceSha256);
for(const plan of read('browser-plan.json')){const run=read(plan.folder+'/test-results/browser-results.json');assert.equal(run.applicationCommit,before.head);assert.equal(run.outcomes.length,plan.cases);assert.ok(run.outcomes.every(r=>r.status==='PASS'));for(const state of run.states)for(const key of ['errors','pageErrors','httpErrors','unexpected','external','clinicalWrites','allowedMockMutations'])assert.deepEqual(state[key],[],key);}
assert.equal(read('lane-handoff.json').browserLane,'RELEASED');const files=[];function walk(dir,rel=''){for(const name of readdirSync(dir)){if(name==='runtime-cache'||name==='node_modules'||name==='manifest.json')continue;const p=dir+'/'+name,r=(rel?rel+'/':'')+name;if(statSync(p).isDirectory())walk(p,r);else files.push({path:r,sha256:createHash('sha256').update(readFileSync(p)).digest('hex')});}}walk(root);files.sort((a,b)=>a.path.localeCompare(b.path));writeFileSync(root+'/manifest.json',JSON.stringify({head:before.head,files,exclusions:'Manifest self; runtime-cache; node_modules only. All original failed and passing evidence retained.'},null,2));console.log(JSON.stringify({head:before.head,files:files.length,manifestSha256:createHash('sha256').update(readFileSync(root+'/manifest.json')).digest('hex'),sourceSha256:before.sourceSha256}));
