import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/424-reading-action',app='67d21c3e9257a5acb8c9b25130c9417fb92185fb',read=p=>JSON.parse(readFileSync(root+'/'+p)),sha=b=>createHash('sha256').update(b).digest('hex');
const before=read('root-rerun/source-before/source-receipt.json'),after=read('root-rerun/source-after/source-receipt.json');assert.deepEqual(before,after);assert.equal(after.fileCount,1472);assert.equal(after.sourceSha256,'4cbd1b51f7c9991533f3882511ffa71262c66f3f09fac9a3b8bf29b617560574');
const manifestBytes=readFileSync(root+'/independent-qa/immutable-manifest.json');assert.equal(sha(manifestBytes),'7079affea9bc5191002a1af77c113fd3016cddcb09786568afba211978175058');const manifest=JSON.parse(manifestBytes);assert.equal(manifest.files.length,129);for(const f of manifest.files)assert.equal(sha(readFileSync(root+'/independent-qa/'+f.path)),f.sha256);
for(const f of read('root-rerun/pre-run.json').records){assert.equal(sha(readFileSync(root+'/root-rerun/recipes/'+f.name)),f.sha256);assert.equal(sha(readFileSync(root+'/independent-qa/'+f.name)),f.sha256);}
let cases=0;
for(const [out,qa,count]of [['ordinary','attempt01/browser',17],['supplemental','supplemental03',4]]){
 const result=read('root-rerun/'+out+'/test-results/browser-results.json'),independent=read('independent-qa/'+qa+'/test-results/browser-results.json');assert.equal(result.outcomes.length,count);assert.deepEqual(result.outcomes,independent.outcomes);assert.ok(result.outcomes.every(r=>r.status==='PASS'));cases+=count;
 for(const guard of result.states){for(const key of ['pageErrors','unexpected','external','clinicalWrites'])assert.deepEqual(guard[key],[]);assert.ok(guard.httpErrors.every(e=>[503,409].includes(e.status)&&(/\/ack$/.test(e.path)||e.path==='/patients/diary-unread-patient-counts')));assert.deepEqual(guard.errors.filter(e=>!/Failed to load resource.*(503|409)/.test(e)),[]);}
}
const commands=read('root-rerun/commands/command-results.json');assert.deepEqual(commands.newFailures,[]);for(const r of commands.records){if(r.name==='full-regression'){assert.equal(r.tests,1252);assert.equal(r.pass,1240);assert.equal(r.fail,12);assert.deepEqual(r.failures,commands.baselineFailures);}else assert.equal(r.exit,0);}assert.equal(commands.records.find(r=>r.name==='focused').pass,32);
const db=read('root-rerun/db/result.json');assert.equal(db.status,0);assert.equal(db.realPostgres,true);assert.equal(db.migrations,57);assert.match(readFileSync(root+'/root-rerun/db/tests.log','utf8'),/^[#ℹ] pass 12$/m);assert.match(readFileSync(root+'/root-rerun/db/tests.log','utf8'),/^[#ℹ] fail 0$/m);assert.ok(read('root-rerun/prisma/result.json').records.every(r=>r.exit===0));assert.equal(read('root-rerun/server-stop.json').listenerFree,true);
for(const suffix of ['','-mobile']){const baseline=read('baseline04/browser/benchmark'+suffix+'.json'),current=read('root-rerun/ordinary/benchmark'+suffix+'.json');assert.equal(baseline.source,'b5f471cd2cd56839e7ebbd0d3daf0bbf04791468');assert.deepEqual(baseline.viewport,current.viewport);assert.deepEqual(baseline.heights.map(r=>r.id),current.heights.map(r=>r.id));for(let i=0;i<3;i++){assert.equal(baseline.heights[i].height-current.heights[i].height,suffix?9:17);for(const text of ['Segnalata da Medico Sintetico','06/10/2026 09:00','Dati inventati per verificare la coda. Nessuna informazione di un paziente reale.'])assert.ok(current.heights[i].text.includes(text));}}
const receipt={applicationCommit:app,decision:'AUTHORIZED SCOPED APPLICATION PROMOTION',authority:'Explicit human commit/push/deploy authorization; root independent release decision after sealed QA and byte-identical root rerun',originalCriteriaPassed:4,independentBrowserCases:cases,rootIndependentRerun:cases,focusedEach:32,realLocalDbEach:12,migrations:57,sourceSha256:after.sourceSha256,qaManifestSha256:sha(manifestBytes),immutableQaFiles:129,newFailures:0,existingFullSuiteFailures:12,productionPatientTestMutations:0,scope:'Only five committed frontend presentation/test paths; backend/config/auth/schema/locks unchanged; no blocked405/408/410/416 source',remainingReleaseGates:['Exact production deployment','Compiled online acceptance','Complete CI baseline comparison','Canonical privacy scan and pinned public proof'],at:new Date().toISOString()};
writeFileSync(root+'/rerun-verification.json',JSON.stringify({...receipt,decision:'EXACT INDEPENDENT ROOT RERUN VERIFIED'},null,2));writeFileSync(root+'/release-gate-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
