import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/424-reading-action',application='67d21c3e9257a5acb8c9b25130c9417fb92185fb',branch='codex/bug-424-reading-action',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:20e6});assert.equal(r.status,0,'Git check failed safely');return r.stdout.trim();},env=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env,gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',maxBuffer:20e6,env:{...process.env,GH_TOKEN:env.GITHUB_TOKEN||env.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const deployment=read('deployment-receipt.json'),publication=read('publication-manifest.json'),ci=read('ci-comparison.json'),gate=read('release-gate-receipt.json'),online=read('compiled-online/online-receipt.json');assert.equal(deployment.applicationCommit,application);assert.equal(deployment.decision,'VERIFIED RELEASE');assert.equal(ci.frontendSecretScanConclusion,'success');assert.deepEqual(ci.newFailureNames,[]);assert.equal(gate.decision,'AUTHORIZED SCOPED APPLICATION PROMOTION');assert.equal(gate.originalCriteriaPassed,4);assert.equal(gate.rootIndependentRerun,21);assert.equal(gate.independentBrowserCases,21);assert.equal(online.applicationCommit,application);assert.equal(online.cases,21);assert.equal(online.decision,'COMPILED ONLINE ACCEPTANCE VERIFIED');assert.equal(online.bundleSha256,deployment.vercel.bundleSha256);assert.equal(spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',root],{encoding:'utf8'}).status,0);
assert.equal(git(['branch','--show-current']),branch);const proof=git(['rev-parse','HEAD']);assert.notEqual(proof,application);assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof));assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+application));git(['diff','--exit-code',application,proof,'--','frontend','backend','prisma','package.json','package-lock.json','scripts/build','scripts/run-node-tests.mjs']);
for(const row of publication.files){const r=spawnSync('git',['show',`${proof}:${row.path}`],{maxBuffer:100e6});assert.equal(r.status,0);assert.equal(sha(r.stdout),row.gitBlobSha256,'Published canonical drift');}
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${root}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${root}`,images=[['Azione esplicita e note compatte desktop','compiled-online/browser/screenshots/desktop-after-brief-notes.png'],['Conferma e urgenza separata','compiled-online/browser/screenshots/authoritative-read-active-urgency.png'],['Cartella paziente: lettore e data del server','compiled-online/supplemental/screenshots/direct-chart-confirmed.png'],['Mobile emulato: contenuto completo','compiled-online/browser/screenshots/mobile-after-brief-notes.png']],verified=[];
for(const [,path]of images){const r=await fetch(`${raw}/${path}`);assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(sha(bytes),sha(readFileSync(root+'/'+path)));verified.push({path,http:r.status,sha256:sha(bytes)});}
const issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424']));assert.equal(issue.body,read('original-issue.json').body,'Original criteria changed; re-audit required');const comments=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424/comments','--paginate']));let comment=comments.find(c=>c.body.includes(proof)&&c.body.includes('CLOSED — VERIFIED'));assert.ok(issue.state==='open'||comment,'Closed without matching proof');
writeFileSync(root+'/publication-policy-receipt.json',JSON.stringify({decision:'AUTHORIZED VERIFIED ISSUE COMMENT AND CLOSURE',authority:'Direct human user authorization plus independent/root release gate',applicationCommit:application,proofCommit:proof,immutableFiles:publication.files.length,allFourOriginalCriteriaPassed:true,verifiedImages:verified,productionPatientTestMutations:0,at:new Date().toISOString()},null,2));
const body=`CLOSED — VERIFIED: tutti i quattro criteri originali soddisfatti.

Correzione [${application}](https://github.com/l2v-hub/ClinicOS/commit/${application}); Vercel ${deployment.vercel.id} READY, SHA Git esatto e [app online](https://clinicos-eosin.vercel.app/) verificata sul bundle compilato.

1. Comando visibile e accessibile «Conferma lettura»; stato «Lettura non confermata» prima dell'azione. Tastiera, attesa, retry e restrizioni autore/permessi verificati.
2. Dopo il salvataggio nome/ruolo del lettore e data completa Europe/Rome provengono dal receipt server acknowledgedAt, conservati dopo refetch e reload; verificata anche la cartella paziente reale della SPA per infermiere e la vista medico.
3. Lettura invia solo purpose read: non prende in carico, non completa la nota e lascia distinta l'urgenza «Ho capito». Nessuna conferma inventata in caso di errore o risposta malformata. Semantica legacy invariata.
4. Una guida contestuale chiusa per lista sostituisce spiegazioni comuni duplicate. Tre stesse note complete, stesso viewport e sorgente baseline422: desktop206.171875→189.171875px (17px meno ciascuna); mobile240.765625→231.765625px (9px meno). Identità, data, severità e testo completi; nessuna altezza fissa/troncamento/overflow orizzontale.

[Report](${tree}/validation-report.md):32 test mirati ciascuno root/QA, tipi e build con React compiler reale PASS,21 casi browser indipendenti e21 rerun root con ricette byte-identiche,21 sul bundle compilato online. [QA indipendente](${tree}/independent-qa/validation-report.md), [manifest129 immutabile](${tree}/independent-qa/immutable-manifest.json), [rerun](${tree}/rerun-verification.json).12 test reali PostgreSQL locali, DB sintetico isolato57 migrazioni, autorità/scope/timestamp/append-only/concorrenza verificati e cluster chiusi. Il reload UI è in-memory e non viene spacciato per prova DB di produzione. Tutte le API cliniche/auth intercettate prima della rete,0 scritture su pazienti reali.

Trasparenza:1252 test frontend,1240PASS e12 fallimenti identici alla baseline422,0 nuovi. [CI](${tree}/ci-comparison.json): stesso singolo fallimento backend preesistente e stesso stage, downstream saltati; secret scan PASS, non CI globale verde. Scanner nativo sui cinque file modificati:0 finding sia baseline sia candidato, non audit globale/CVE. Tutti i tentativi indipendenti, inclusi quelli falliti del solo harness, preservati e sigillati; incidenti di coordinamento e recupero byte-esatto documentati. Preliminari root conservati localmente. Backend/schema/auth/deps/config invariati; nessuna certificazione hardware/AT/reparto, clinica o provider. Solo dati e immagini sintetici, nessuna foto originale dell'audit allegata.

Prove fissate a ${proof}: [hash canonicali/scansione credenziali e archivi](${tree}/publication-manifest.json), [deployment](${tree}/deployment-receipt.json), [trace cartella compilata](${raw}/compiled-online/supplemental/chart-trace.zip), [risultati/guard](${tree}/compiled-online), [video](${tree}/compiled-online/supplemental/video), [receipt HTML Playwright-library](${tree}/compiled-online/playwright-report.html).

${images.map(([label,path])=>`### ${label}\n![424 ${label}](${raw}/${path})`).join('\n\n')}`;
if(!comment)comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424/comments','--method','POST','-f',`body=${body}`]));if(issue.state==='open')gh(['api','repos/l2v-hub/ClinicOS/issues/424','--method','PATCH','-f','state=closed','-f','state_reason=completed']);const closed=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424']));assert.equal(closed.state,'closed');assert.equal(closed.state_reason,'completed');const receipt={applicationCommit:application,proofCommit:proof,proofBranch:branch,deployment:deployment.vercel.id,githubProof:comment.html_url,state:closed.state,closedAt:closed.closed_at,canonicalHashesVerified:publication.files.length,images:verified,secretChecks:publication.secretChecks,zipEntriesChecked:publication.zipEntriesChecked,productionPatientTestMutations:0};writeFileSync(root+'/github-closure-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
