import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
const root='artifacts/task-validation/424-reading-action',run='37992961607',env=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const gh=args=>{const r=spawnSync('gh',[...args,'--repo','l2v-hub/ClinicOS'],{encoding:'utf8',maxBuffer:30e6,env:{...process.env,GH_TOKEN:env.GITHUB_TOKEN||env.GH_TOKEN}});assert.equal(r.status,0,'CI operation failed safely');return r.stdout;};
const state=JSON.parse(gh(['run','view',run,'--json','status,conclusion,jobs']));assert.equal(state.status,'completed');assert.deepEqual(state.jobs.flatMap(j=>j.steps.filter(s=>s.conclusion==='failure').map(s=>j.name+': '+s.name)),['gate: Initialize containers']);
let log=gh(['run','view',run,'--log-failed']);for(const [key,value]of Object.entries(env))if(/TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL|CONNECTION_STRING|DATABASE_URL/.test(key)&&typeof value==='string'&&value.length>=8)log=log.replaceAll(value,'[REDACTED CONFIGURED CREDENTIAL]');
writeFileSync(root+'/ci-infrastructure-attempt01.json',JSON.stringify({applicationCommit:'67d21c3e9257a5acb8c9b25130c9417fb92185fb',run,state,at:new Date().toISOString(),classification:'CI infrastructure before application checkout; full log retained sanitized; not accepted baseline backend test result'},null,2));writeFileSync(root+'/ci-infrastructure-attempt01.log',log);console.log(log.split('\n').filter(l=>/error|failed|denied|pull|429|unavailable|timeout|rate.limit/i.test(l)).slice(-25).join('\n'));
if(process.argv.includes('--retry')){writeFileSync(root+'/ci-retry-policy.json',JSON.stringify({decision:'AUTHORIZED ONE FAILED JOB RETRY',authority:'Direct human authorization to iterate deployment/testing without asking; no source/config/provider mutation',run,applicationCommit:'67d21c3e9257a5acb8c9b25130c9417fb92185fb',reason:'First attempt stopped during container initialization before application checkout',at:new Date().toISOString()},null,2));gh(['run','rerun',run,'--failed']);console.log('One failed CI job retry dispatched, no application mutation');}
