import assert from 'node:assert/strict';
import {readdirSync,readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
const root='artifacts/task-validation/424-reading-action',app='67d21c3e9257a5acb8c9b25130c9417fb92185fb',git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:20e6});assert.equal(r.status,0,'Scoped proof staging failed');return r.stdout.trim();};
assert.equal(git(['rev-parse','HEAD']),app);assert.equal(git(['diff','--cached','--name-only','--','frontend','backend','prisma','package.json','package-lock.json']),'');
const dirs=['baseline04','root-frozen','root-rerun','compiled-online','independent-qa'],paths=[];
function walk(dir){for(const e of readdirSync(dir,{withFileTypes:true})){const path=dir+'/'+e.name;if(e.isDirectory()){if(e.name==='runtime-cache'||e.name.startsWith('scratch-prisma-'))continue;walk(path);}else paths.push(path);}}
for(const dir of dirs){if(dir==='independent-qa'){const m=JSON.parse(readFileSync(root+'/'+dir+'/immutable-manifest.json'));assert.equal(m.applicationCommit,app);for(const f of m.files){assert.ok(!f.path.startsWith('/')&&!f.path.includes('..')&&!f.path.includes('runtime-cache'));paths.push(root+'/'+dir+'/'+f.path);}paths.push(root+'/'+dir+'/immutable-manifest.json');}else walk(root+'/'+dir);}
for(const e of readdirSync(root,{withFileTypes:true}))if(e.isFile()&&!['ci-progress.json','publication-manifest.json','publication-policy-receipt.json','github-closure-receipt.json'].includes(e.name))paths.push(root+'/'+e.name);
assert.ok(paths.every(p=>!p.includes('/runtime-cache/')&&!p.includes('/scratch-prisma-')));for(let i=0;i<paths.length;i+=50)git(['add','-f','--',...paths.slice(i,i+50)]);const staged=git(['diff','--cached','--name-only']).split('\n').filter(Boolean);assert.ok(staged.every(p=>p.startsWith(root+'/')));
writeFileSync(root+'/proof-staging-policy.json',JSON.stringify({decision:'AUTHORIZED SCOPED SYNTHETIC EVIDENCE STAGING',authority:'Direct human authorization; root sole proof writer',applicationCommit:app,explicitDirectoryAllowlist:dirs,artifactCount:new Set([...staged,root+'/proof-staging-policy.json']).size,at:new Date().toISOString(),excluded:['Root failed/dev attempts retained locally','runtime caches','scratch generated Prisma clones','dirty primary/launchers','blocked405/408/410/416 candidates','real patient attachments']},null,2));git(['add','-f','--',root+'/proof-staging-policy.json']);console.log('Scoped proof staged only; canonical privacy and immutable QA checks still required');
