import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect,setup,navigate,item,finish,tokens} from './transport.mjs';
const out=resolve(process.argv[2]);assert.ok(process.argv[2]);assert.equal(existsSync(out),false);for(const p of ['screenshots','video','trace','test-results','playwright-report'])mkdirSync(out+'/'+p,{recursive:true});
const browser=await chromium.launch({headless:true}),outcomes=[],states=[],contexts=[];
try{for(const [width,height,device] of [[1150,1004,'desktop'],[390,844,'mobile']]){const ctx=await setup(browser,out,width,height);contexts.push(ctx);states.push(ctx.state);const page=ctx.page;await expect(page.locator('.operator-workload-grid')).toBeVisible();const card=page.locator('.op-workload-card').filter({has:page.getByText('Identita03 Sintetico',{exact:true})});await expect(card).toBeVisible();await expect(card.locator('.op-workload-card__role')).toHaveText('oss · Reparto sintetico');await page.screenshot({path:out+'/screenshots/'+device+'-before-dashboard.png',fullPage:true});await navigate(ctx,'Operatori');await expect(page.locator('.op-management')).toBeVisible();const row=item(ctx,3);await expect(row).toBeVisible();const role=width<600?row.locator('.pt-list-card__meta').first():row.locator('td').nth(1).locator('.cell--muted');await expect(role).toHaveText(width<600?' · Reparto sintetico':' · Qualifica sintetica 3');expect(await role.textContent()).not.toContain('oss');await page.screenshot({path:out+'/screenshots/'+device+'-before-directory.png',fullPage:true});const button=row.locator('.table-actions button').first();await button.focus();await page.keyboard.press('Enter');await expect(page.getByRole('form',{name:'Modifica operatore'})).toBeVisible();await expect(page.getByLabel('Ruolo',{exact:true})).toHaveValue('medico');await page.screenshot({path:out+'/screenshots/'+device+'-before-legacy-editor.png',fullPage:true});await page.getByRole('button',{name:'Annulla',exact:true}).click();expect(ctx.state.allowedMockMutations).toEqual([]);outcomes.push({name:device+' baseline actual SPA demonstrates inconsistent legacy role and invented first editor option',status:'PASS'});await finish(ctx,out,device);}
writeFileSync(out+'/test-results/browser-results.json',JSON.stringify({applicationCommit:'7680ec0b25c61de5745f296d91e370b575de9c00',outcomes,states,fixture:'Exact same guarded synthetic transport as candidate; captures baseline defect, not a baseline medical-role assertion.'},null,2));writeFileSync(out+'/playwright-report/index.html','<!doctype html><meta charset="utf-8"><h1>428 actual baseline Playwright assertion receipt</h1><p>Library receipt, not native Test reporter.</p><pre>'+JSON.stringify(outcomes,null,2)+'</pre>');
}catch(e){for(const [i,c]of contexts.entries()){await c.page.screenshot({path:out+'/screenshots/failure-'+i+'.png',fullPage:true}).catch(()=>{});await c.context.tracing.stop({path:out+'/trace/failure-'+i+'.zip'}).catch(()=>{});}writeFileSync(out+'/test-results/failure.json',JSON.stringify({message:e.message,stack:e.stack,outcomes,states},null,2));throw e;}finally{for(const c of contexts)await c.context.close().catch(()=>{});await browser.close();}
