import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
const root='artifacts/task-validation/417-vitals-form',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8'));
const source=read('root-rerun/after/source-receipt.json'),review=read('independent-review-receipt.json');
assert.equal(source.applicationCommit,'02b4ba89af291186a72e040b868da024bb865164');assert.equal(source.sourceSha256,'66ad2baf06ce7ed812ef743e57acbef562201396535112d7d5bfcf3299b0920b');assert.equal(source.fileCount,1459);
assert.equal(review.applicationCommit,source.applicationCommit);assert.equal(review.decision,'INDEPENDENT ORIGINALS AND EXACT SOURCE VERIFIED');
const qa=read('independent-qa417/run04-final/raw-results.json'),rerun=read('root-rerun/adversarial-harness/root-final/raw-results.json');
for(const results of [qa,rerun]){assert.equal(results.stats.expected,24);assert.equal(results.stats.unexpected,0);assert.equal(results.stats.skipped,0);assert.equal(results.stats.flaky,0);}
assert.equal(read('root-rerun/adversarial-harness/root-final/run-receipt.json').exit,0);
const browser=read('root-rerun/browser/browser-results.json');assert.equal(browser.outcomes.length,18);assert.ok(browser.outcomes.every(o=>o.status==='PASS'));
const commands=read('root-rerun/commands/command-results.json');assert.deepEqual(commands.newFailures,[]);assert.equal(commands.records.find(r=>r.name==='focused').pass,47);assert.equal(commands.records.find(r=>r.name==='full-regression').fail,12);assert.ok(commands.records.filter(r=>r.name!=='full-regression').every(r=>r.exit===0));assert.equal(read('root-rerun/commands/backend-input-receipt.json').pass,7);
assert.deepEqual(read('security-receipt.json').newTouchedFindings,[]);assert.equal(read('candidate-secret-receipt.json').decision,'CANONICAL CANDIDATE CREDENTIAL SCAN PASS');
const receipt={applicationCommit:source.applicationCommit,applicationSourceSha256:source.sourceSha256,checkedAt:new Date().toISOString(),decision:'AUTHORIZED SCOPED APPLICATION PROMOTION',authority:'Direct human authorization; root integration release gate, not QA or Ruflo',independentManifestSha256:review.originalManifestSha256,independentFiles:review.immutableFiles,canonicalSourceSha256:review.canonicalSha256,acceptance:{AC1:'Identical labels units order format options in both actual SPA views',AC2:'Native Tab Enter Next with O2 consciousness and NEWS2 guidance, no implicit save',AC3:'Bounded selected-patient historical captions never new values, truthful loading/error/pagination',AC4:'Same raw invalid cases errors focus keypad, request retry and ownership guards'},focusedFrontendPassEach:47,backendInputPassEach:7,ordinaryRootBrowser:18,adversarialBrowserEach:24,unchangedFrontendBaselineFailures:12,newFrontendFailures:0,productionPatientTestMutations:0,backendChanges:false,excluded:'Unreleased405/408/410/416 source, primary dirty checkout and launchers, original patient photos',limits:'Synthetic API persistence and emulator responsive testing, not real DB/hardware/screen-reader or new clinical-policy approval. Existing broad security/dependency findings and global CI remain disclosed.',deploymentAcceptance:'Pending exact-source Vercel READY and guarded compiled online SPA rerun'};
writeFileSync(root+'/release-gate-receipt.json',JSON.stringify(receipt,null,2));console.log('Scoped application promotion authorized; deployment verification remains pending');
