import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect,setup,navigate,item,finish,guards,tokens,labels,profile,explanation} from './transport.mjs';
const out=resolve(process.argv[2]);assert.ok(process.argv[2]);assert.equal(existsSync(out),false);for(const p of ['screenshots','video','trace','test-results','playwright-report'])mkdirSync(out+'/'+p,{recursive:true});
const browser=await chromium.launch({headless:true}),outcomes=[],states=[],contexts=[];
async function check(name,ctx,fn){await fn();await guards(ctx);outcomes.push({name,status:'PASS'});ctx.state.asserted.push(name);console.log('PASS '+name);}
async function shot(ctx,name){await ctx.page.screenshot({path:out+'/screenshots/'+name+'.png',fullPage:true});}
async function open(ctx,i){const row=item(ctx,i);await expect(row).toBeVisible();const button=labels[i].includes('disponibile')||labels[i].includes('verificare')?row.getByRole('button',{name:'Verifica ruolo di Identita'+String(i).padStart(2,'0')+' Sintetico',exact:true}):row.locator('.table-actions button').first();await button.focus();await ctx.page.keyboard.press('Enter');await expect(ctx.page.getByRole('form',{name:'Modifica operatore'})).toBeVisible();}
async function selected(ctx,i){const control=ctx.page.getByLabel('Ruolo',{exact:true}),value=tokens[i]??'';await expect(control).toBeVisible();await expect(control).toHaveValue(value);const text=await control.locator('option:checked').textContent();expect(text).toBe(labels[i]);ctx.state.selected.push({i,value,text});await expect(ctx.page.locator('#operator-role-help')).toHaveText(explanation);}
try{
for(const [width,height,device] of [[1150,1004,'desktop'],[390,844,'mobile']]){
const ctx=await setup(browser,out,width,height);contexts.push(ctx);states.push(ctx.state);const page=ctx.page;
await check(device+' dashboard all16 explicit professional labels and separate qualification',ctx,async()=>{await expect(page.getByText(explanation,{exact:true})).toBeVisible();for(let i=0;i<tokens.length;i++){const card=page.locator('.op-workload-card').filter({has:page.getByText('Identita'+String(i).padStart(2,'0')+' Sintetico',{exact:true})});await expect(card).toBeVisible();await expect(card.locator('.op-workload-card__role').first()).toHaveText(profile(i));await expect(card.locator('.op-workload-card__role').nth(1)).toHaveText('Reparto sintetico');}await expect(page.locator('.operator-workload-grid img')).toHaveCount(0);await shot(ctx,device+'-dashboard-all-roles');});
await navigate(ctx,'Operatori');await expect(page.locator('.op-management')).toBeVisible();
await check(device+' same16 table/mobile role labels, qualification, uncertainty and literal XSS',ctx,async()=>{await expect(page.getByText(explanation,{exact:true})).toBeVisible();for(let i=0;i<tokens.length;i++){const row=item(ctx,i);await expect(row).toBeVisible();const role=width<600?row.locator('.pt-list-card__meta').first():row.locator('td').nth(1).locator('.cell--muted');await expect(role).toHaveText(profile(i));if(i>=10&&i<=14)await expect(row.getByRole('button',{name:/Verifica ruolo di/})).toBeVisible();}await expect(page.locator('.op-management img')).toHaveCount(0);await shot(ctx,device+'-directory-all-roles');});
for(let i=0;i<tokens.length;i++)await check(device+' native keyboard editor retains exact token '+i+'; cancel zero writes',ctx,async()=>{const before=ctx.state.allowedMockMutations.length;await open(ctx,i);await selected(ctx,i);if(i===10||i===14||i===15)await shot(ctx,device+'-retained-editor-'+i);await page.getByRole('button',{name:'Annulla',exact:true}).click();await expect(page.getByRole('form',{name:'Modifica operatore'})).toHaveCount(0);expect(ctx.state.allowedMockMutations.length).toBe(before);});
for(const i of [10,11,12,13,15,9])await check(device+' unrelated edit omits role '+i+' and mock reload retains exact original',ctx,async()=>{await open(ctx,i);await selected(ctx,i);await page.getByLabel('Reparto',{exact:true}).fill('Reparto aggiornato sintetico '+i);const before=ctx.state.allowedMockMutations.length;await page.getByRole('button',{name:'Salva modifiche',exact:true}).click();await expect.poll(()=>ctx.state.allowedMockMutations.length).toBe(before+1);const write=ctx.state.allowedMockMutations.at(-1);expect(write.id).toBe('QA-OP-428-'+i);expect(Object.hasOwn(write.payload,'ruolo')).toBe(false);expect(Object.hasOwn(write.payload,'role')).toBe(false);expect(ctx.operators[i].ruolo).toBe(tokens[i]??'');await page.reload();await expect(page.locator('.op-management')).toBeVisible();const row=item(ctx,i);await expect(row).toBeVisible();await expect(row).toContainText(profile(i));await expect(row).toContainText('Reparto aggiornato sintetico '+i);await open(ctx,i);await selected(ctx,i);await page.getByRole('button',{name:'Annulla',exact:true}).click();});
await check(device+' explicit selection sends only chosen professional role; mock reload displays change',ctx,async()=>{await open(ctx,10);await selected(ctx,10);await page.getByLabel('Ruolo',{exact:true}).selectOption('infermiere');await page.getByRole('button',{name:'Salva modifiche',exact:true}).click();await expect.poll(()=>ctx.state.allowedMockMutations.at(-1)?.payload.ruolo).toBe('infermiere');expect(Object.hasOwn(ctx.state.allowedMockMutations.at(-1).payload,'role')).toBe(false);await page.reload();await expect(item(ctx,10)).toBeVisible();await expect(item(ctx,10)).toContainText('Infermiere · Qualifica: Qualifica sintetica 10');await shot(ctx,device+'-explicit-role-reloaded');});
await finish(ctx,out,device);
}
writeFileSync(out+'/test-results/browser-results.json',JSON.stringify({applicationCommit:process.env.SOURCE_COMMIT,outcomes,states,fixtureTransport:'Actual SPA; all APIs guarded before wire; browser writes and reload are synthetic mock transport only. Separate PostgreSQL proves real API persistence.'},null,2));
writeFileSync(out+'/playwright-report/index.html','<!doctype html><meta charset="utf-8"><h1>428 independent Playwright library assertions</h1><p>Assertion receipt, not the native Playwright Test reporter. Actual SPA synthetic guarded transport, not production database persistence.</p><pre>'+JSON.stringify(outcomes,null,2).replaceAll('&','&amp;').replaceAll('<','&lt;')+'</pre>');
}catch(e){for(const [i,c] of contexts.entries()){await c.page.screenshot({path:out+'/screenshots/failure-'+i+'.png',fullPage:true}).catch(()=>{});await c.context.tracing.stop({path:out+'/trace/failure-'+i+'.zip'}).catch(()=>{});}writeFileSync(out+'/test-results/failure.json',JSON.stringify({message:e.message,stack:e.stack,outcomes,states},null,2));throw e;}finally{for(const c of contexts)await c.context.close().catch(()=>{});await browser.close();}
