import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
const root='artifacts/task-validation/424-reading-action/release-resume-20261010',application='67d21c3e9257a5acb8c9b25130c9417fb92185fb',baselineRun=37987185985,env=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const gh=args=>{const r=spawnSync('gh',args[0]==='api'?args:[...args,'--repo','l2v-hub/ClinicOS'],{encoding:'utf8',maxBuffer:30e6,env:{...process.env,GH_TOKEN:env.GITHUB_TOKEN||env.GH_TOKEN}});assert.equal(r.status,0,'GitHub read failed safely');return r.stdout;};
const runs=JSON.parse(gh(['run','list','--commit',application,'--json','databaseId,name,status,conclusion'])),candidateRun=runs.find(r=>r.name==='AI Import E2E Gate')?.databaseId,secretRun=runs.find(r=>r.name==='Frontend Secret Scan')?.databaseId;if(!candidateRun||!secretRun){console.log('CI not yet present');process.exit(2);}
const attempt=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/actions/runs/'+candidateRun]));assert.equal(attempt.run_attempt,4);assert.equal(attempt.head_sha,application);writeFileSync(root+'/ci-attempt4.json',JSON.stringify({applicationCommit:application,run:candidateRun,attempt:attempt.run_attempt,status:attempt.status,conclusion:attempt.conclusion,at:new Date().toISOString()},null,2));
const candidate=JSON.parse(gh(['run','view',String(candidateRun),'--json','status,conclusion,jobs'])),secret=JSON.parse(gh(['run','view',String(secretRun),'--json','status,conclusion']));
if(candidate.status!=='completed'||secret.status!=='completed'){const progress={applicationCommit:application,checkedAt:new Date().toISOString(),candidateRun,candidateStatus:candidate.status,secretRun,secretStatus:secret.status,secretConclusion:secret.conclusion,jobs:candidate.jobs.map(j=>({name:j.name,status:j.status,conclusion:j.conclusion,activeSteps:j.steps.filter(s=>s.status!=='completed').map(s=>({name:s.name,status:s.status}))})),decision:'PENDING, not final CI receipt'};writeFileSync(root+'/ci-progress.json',JSON.stringify(progress,null,2));console.log(JSON.stringify(progress));process.exit(2);}
const failedStageNames=candidate.jobs.flatMap(j=>j.steps.filter(s=>s.conclusion==='failure').map(s=>`${j.name}: ${s.name}`)).sort();
if(secret.conclusion==='success'&&candidate.conclusion==='failure'&&JSON.stringify(failedStageNames)===JSON.stringify(['gate: Initialize containers'])){
 let log=gh(['run','view',String(candidateRun),'--log-failed']);for(const [key,value]of Object.entries(env))if(/TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL|CONNECTION_STRING|DATABASE_URL/.test(key)&&typeof value==='string'&&value.length>=8)log=log.replaceAll(value,'[REDACTED CONFIGURED CREDENTIAL]');assert.match(log,/Docker pull failed/);writeFileSync(root+'/ci-infrastructure.log',log);
 const receipt={applicationCommit:application,candidateRun,frontendSecretScanRun:secretRun,frontendSecretScanConclusion:secret.conclusion,decision:'BLOCKED EXTERNAL CI INFRASTRUCTURE; ISSUE MUST REMAIN OPEN',failedStage:'Initialize containers',failedSteps:failedStageNames,reason:'DockerHub pull unavailable before application checkout; same external condition already repeated three times for424, no unchanged retries',applicationTestVerdict:'Unavailable, not accepted baseline backend failure and not globally green',retryPolicy:'No workflow/env/credentials expansion or unchanged retry; resume when registry availability changes',at:new Date().toISOString()};writeFileSync(root+'/ci-blocker-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));process.exit(3);
}
if(secret.conclusion==='success'&&candidate.conclusion==='success'){
 assert.deepEqual(failedStageNames,[]);const receipt={applicationCommit:application,candidateRun,frontendSecretScanRun:secretRun,frontendSecretScanConclusion:secret.conclusion,decision:'COMPLETED CI WORKFLOWS VERIFIED',candidateConclusion:'success',newFailureNames:[],failedSteps:[],baselineRun,at:new Date().toISOString()};writeFileSync(root+'/ci-comparison.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));process.exit(0);
}
assert.equal(secret.conclusion,'success');const failureNames=run=>[...new Set([...gh(['run','view',String(run),'--log-failed']).matchAll(/not ok \d+ - ([^\r\n]+)/g)].map(m=>m[1].trim()))].sort(),baselineNames=failureNames(baselineRun),candidateNames=failureNames(candidateRun);assert.deepEqual(candidateNames,baselineNames);assert.deepEqual(baselineNames,['therapy reads and writes apply patient scope before loading clinical data']);assert.equal(candidate.conclusion,'failure');
const baseline=JSON.parse(gh(['run','view',String(baselineRun),'--json','status,conclusion,jobs'])),failedSteps=run=>run.jobs.flatMap(j=>j.steps.filter(s=>s.conclusion==='failure').map(s=>`${j.name}: ${s.name}`)).sort();assert.deepEqual(failedSteps(candidate),failedSteps(baseline));assert.deepEqual(failedSteps(candidate),['gate: Backend unit tests']);
const receipt={applicationCommit:application,baselineApplication:'b5f471cd2cd56839e7ebbd0d3daf0bbf04791468',baselineRun,candidateRun,attempt:4,workflow:'AI Import E2E Gate',candidateConclusion:candidate.conclusion,failedStage:'Backend unit tests',baselineFailureNames:baselineNames,candidateFailureNames:candidateNames,newFailureNames:[],failedSteps:failedSteps(candidate),baselineFailedSteps:failedSteps(baseline),downstreamImportTests:'Skipped, not claimed passing',frontendSecretScanRun:secretRun,frontendSecretScanConclusion:secret.conclusion,scope:'No424 backend/pipeline changes, exact same single accepted422failure. Prior3container failures preserved; changed external availability allowed one retry4. Scoped compiled current-production acceptance separately verified, no global CI green claim'};writeFileSync(root+'/ci-comparison.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
