import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/task-validation/424-reading-action',own=root+'/release-resume-20261010',branch='codex/bug-424-reading-action',app='67d21c3e9257a5acb8c9b25130c9417fb92185fb',production='b7ae14d120c1e70ccf72784206a505f8c48f975e',sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(readFileSync(p));
const configured=read('C:/Workspace/ClinicOSHouse/.claude/settings.local.json').env,git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:100e6});assert.equal(r.status,0,'Protected Git read failed');return r.stdout.trim();},gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',maxBuffer:30e6,env:{...process.env,GH_TOKEN:configured.GITHUB_TOKEN||configured.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const proof=git(['rev-parse','HEAD']),manifest=read(root+'/publication-manifest.json'),gate=read(own+'/release-gate-receipt.json'),ci=read(own+'/ci-comparison.json'),deployment=read(own+'/deployment-receipt.json');
assert.equal(manifest.applicationCommit,app);assert.equal(manifest.originalIndependentManifestFrozen,true);assert.equal(gate.originalCriteriaPassed,4);assert.equal(gate.rootByteIdenticalBrowserCases,21);assert.equal(gate.currentProductionCommit,production);assert.equal(ci.attempt,4);assert.deepEqual(ci.newFailureNames,[]);assert.equal(ci.frontendSecretScanConclusion,'success');
assert.equal(git(['branch','--show-current']),branch);assert.ok(git(['ls-remote','origin','refs/heads/'+branch]).startsWith(proof+'\t'));assert.ok(git(['ls-remote','origin','refs/heads/main']).startsWith(production+'\t'));assert.ok(git(['diff','--name-only',app,proof]).split('\n').every(p=>p.startsWith(root+'/')));
const batch=spawnSync('git',['cat-file','--batch'],{input:manifest.files.map(r=>proof+':'+r.path+'\n').join(''),maxBuffer:256e6});assert.equal(batch.status,0);let offset=0;for(const row of manifest.files){const end=batch.stdout.indexOf(10,offset),header=batch.stdout.subarray(offset,end).toString('ascii').split(' ');assert.equal(header[1],'blob');const size=Number(header[2]);assert.ok(size<=100e6);offset=end+1;assert.equal(sha(batch.stdout.subarray(offset,offset+size)),row.gitBlobSha256);offset+=size;assert.equal(batch.stdout[offset++],10);}assert.equal(offset,batch.stdout.length);
const htmlResponse=await fetch('https://clinicos-eosin.vercel.app/');assert.equal(htmlResponse.status,200);assert.equal(sha(Buffer.from(await htmlResponse.arrayBuffer())),deployment.vercel.htmlSha256);for(const asset of [{url:deployment.vercel.bundleUrl,sha256:deployment.vercel.bundleSha256},...deployment.vercel.styleAssets]){const r=await fetch(asset.url);assert.equal(r.status,200);assert.equal(sha(Buffer.from(await r.arrayBuffer())),asset.sha256);}
const run=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/actions/runs/'+ci.candidateRun]));assert.equal(run.head_sha,app);assert.equal(run.run_attempt,4);assert.equal(run.status,'completed');assert.equal(run.conclusion,ci.candidateConclusion);
const closure=spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',own],{encoding:'utf8'});assert.equal(closure.status,0);writeFileSync(own+'/check-closure.log',closure.stdout+closure.stderr);
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${own}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${own}`,images=[['Azione esplicita e note compatte','root-ordinary/screenshots/desktop-after-brief-notes.png'],['Conferma lettura distinta dall’urgenza','root-ordinary/screenshots/authoritative-read-active-urgency.png'],['Cartella: lettore e data autorevoli','root-supplemental/screenshots/direct-chart-confirmed.png']],verified=[];
for(const [,path]of images){const r=await fetch(raw+'/'+path);assert.equal(r.status,200);const hash=sha(Buffer.from(await r.arrayBuffer()));assert.equal(hash,sha(readFileSync(own+'/'+path)));verified.push({path,http:200,sha256:hash});}
const issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424']));assert.equal(issue.body,read(root+'/original-issue.json').body,'Original criteria changed, re-audit required');const comments=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424/comments','--paginate']));let comment=comments.find(c=>c.body.includes(proof)&&c.body.includes('CLOSED — VERIFIED'));assert.ok(issue.state==='open'||comment,'Closed issue without matching proof');
writeFileSync(own+'/github-publication-policy.json',JSON.stringify({decision:'AUTHORIZED PINNED SYNTHETIC COMMENT/VERIFIED CLOSURE',authority:'Explicit human authorization and root independently accepted release gate',originalApplicationCommit:app,currentProductionCommit:production,proofCommit:proof,canonicalFiles:manifest.files.length,images:verified,productionPatientTestMutations:0,at:new Date().toISOString()},null,2));
const body=`CLOSED — VERIFIED: tutti i4 criteri originali soddisfatti. Il precedente blocco CI esterno è ora superato; il report BLOCKED precedente resta conservato come storico, non come stato attuale.

Correzione originale [${app}](https://github.com/l2v-hub/ClinicOS/commit/${app}) inclusa byte-identicamente nei5 file pertinenti della versione online [${production}](https://github.com/l2v-hub/ClinicOS/commit/${production}). Vercel ${deployment.vercel.id} READY, metadata/Git SHA e alias/HTML/JS/CSS verificati; hash invariati prima/dopo21 test compilati. Nessun rollback o nuova modifica sorgente per questa continuazione.

1. Comando visibile/accessibile «Conferma lettura», non uno stato futuro; tastiera, attesa, errore/retry, autore e permessi verificati.
2. «Lettura confermata da…» con nome/ruolo del lettore e data completa Europe/Rome da acknowledgedAt server; refetch/reload e cartella paziente diretta verificati, anche profilo medico.
3. purpose read resta distinto da «Ho capito», presa in carico e completamento. Errori503/409 o risposta malformata non inventano conferme; urgenza e stato nota restano invariati.
4. Note brevi complete, una guida comune chiusa per lista; spiegazioni duplicate eliminate. Confronto originale3 stesse note:17px meno desktop e9px meno mobile, senza troncamento/altezza fissa/scroll orizzontale.

[Nuovo report](${tree}/validation-report.md), [accettazione root](${tree}/acceptance-receipt.json), [QA indipendente](${tree}/independent-release-qa/validation-report.md):21 nuovi casi indipendenti sul bundle corrente e21 rerun root con ricette raw byte-identiche. [Manifest66 immutabile](${tree}/independent-release-qa/immutable-manifest.json) SHA4567bcf2883517856dd2ca8a98f7c99c55a26743c7302033edfa2fda2d15b377; precedente129-file manifest7079 preservato, compresi gli incidenti del solo harness.32 nuovi test mirati root e tipi FE/BE/tsc-b/build React compiler/secrets PASS; full1252/1240PASS/12 errori nominati identici/0 nuovi, non globalmente verde.1472 file sorgente originali invariati SHA4cbd1b51f7c9991533f3882511ffa71262c66f3f09fac9a3b8bf29b617560574. Backend/schema/config/deps/workflows invariati.

Le12 prove PostgreSQL reali/57 migrazioni per root e QA originali restano evidenza storica verificata per codice invariato, non nuove esecuzioni o persistenza DB di produzione. Il reload browser è in-memory. Tutte le API cliniche/auth intercettate PRIMA rete;0 scritture su pazienti reali, dati inventati e nessuna foto originaria dell’audit.

[CI37992961607 tentativo4](https://github.com/l2v-hub/ClinicOS/actions/runs/37992961607) completata dopo recupero container: [confronto](${tree}/ci-comparison.json) esattamente stesso singolo fallimento backend preesistente «therapy reads and writes apply patient scope before loading clinical data», stesso stage Backend unit tests,0 nuovi; downstream import saltati, NON dichiarati passanti. Secret scan37992961608success. Tre precedenti fallimenti infrastrutturali conservati, nessuna modifica workflow/env/credenziali. Nessuna certificazione globale hardware/touch/AT/clinica/CVE.

Prove fissate a ${proof}: [deployment corrente](${tree}/deployment-receipt.json), [binding source67→productionb7](${tree}/source-binding-after.json), [hash/scansione canonicale](${tree}/../publication-manifest.json), [trace cartella](${raw}/root-supplemental/chart-trace.zip), [video](${tree}/root-supplemental/video), [risultati/guardie](${tree}/root-ordinary/test-results/browser-results.json).3 PNG pubblici HTTP200 e hash raw verificati anche sul commit finale prima della chiusura.

${images.map(([label,path])=>`### ${label}\n![424 ${label}](${raw}/${path})`).join('\n\n')}`;
if(!comment)comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424/comments','--method','POST','-f','body='+body]));if(issue.labels.some(l=>l.name==='status-blocked'))gh(['issue','edit','424','--repo','l2v-hub/ClinicOS','--remove-label','status-blocked']);if(issue.state==='open')gh(['issue','close','424','--repo','l2v-hub/ClinicOS','--reason','completed']);const final=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/424']));assert.equal(final.state,'closed');assert.equal(final.body,issue.body);
const receipt={originalApplicationCommit:app,currentProductionCommit:production,proofCommit:proof,proofBranch:branch,githubProof:comment.html_url,state:final.state,closedAt:final.closed_at,decision:'CLOSED — VERIFIED',canonicalHashesVerified:manifest.files.length,images:verified,credentialChecks:manifest.secretChecks,zipMembers:manifest.zipEntriesChecked,productionPatientTestMutations:0,at:new Date().toISOString()};writeFileSync(own+'/github-publication-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
