import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {resolve,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const base=resolve('artifacts/task-validation/417-vitals-form/independent-qa417'),commit='02b4ba89af291186a72e040b868da024bb865164',baseline='0d7adc361b92c8466655d9ed830d2b87bbd0f419';
const git=args=>{const r=spawnSync('git',args,{maxBuffer:20*1024*1024});assert.equal(r.status,0,args.join(' '));return r.stdout;};
const paths=git(['diff','--name-only',baseline,commit]).toString().trim().split('\n');assert.equal(paths.length,10);assert(paths.every(p=>p.startsWith('frontend/src/')));
const protectedPaths=['frontend/src/lib/news2.ts','frontend/src/lib/patientParameterReadings.ts','frontend/src/lib/parameterPad.ts','frontend/src/lib/parameterEntryDrafts.ts','frontend/src/lib/useParameterEntryDraft.ts','frontend/src/components/operator/MultiPatientParametri.tsx','frontend/src/components/operator/PatientVitalSignsView.tsx','frontend/src/config.ts','backend/src','prisma','package.json','package-lock.json','frontend/package.json','frontend/package-lock.json','frontend/vite.config.ts','frontend/vercel.json'];git(['diff','--exit-code',baseline,commit,'--',...protectedPaths]);
const blobs=paths.map(path=>{const data=git(['show',`${commit}:${path}`]),out=resolve(base,'source/canonical-inputs',path);mkdirSync(dirname(out),{recursive:true});writeFileSync(out,data);return{path,gitBlob:git(['rev-parse',`${commit}:${path}`]).toString().trim(),sha256:createHash('sha256').update(data).digest('hex'),lineCount:data.toString().split('\n').length-1};});
const scan=spawnSync(process.execPath,['scripts/security/scan-frontend-secrets.mjs',resolve(base,'source/canonical-inputs')],{encoding:'utf8'});assert.equal(scan.status,0,'Canonical blob credential scan');writeFileSync(resolve(base,'commands/security-canonical-blobs.log'),scan.stdout+scan.stderr);
const added=git(['diff','--unified=0',baseline,commit]).toString().split('\n').filter(line=>line.startsWith('+')&&!line.startsWith('+++')).join('\n');
const riskyMarkers=['dangerouslySetInnerHTML','eval(','new Function','localStorage','sessionStorage','console.log','$queryRaw','$executeRaw','fetch('];
const changedRiskyMarkers=riskyMarkers.filter(marker=>added.includes(marker));assert.deepEqual(changedRiskyMarkers,[]);
const referencedCurrent=JSON.parse(readFileSync('C:/w-417/artifacts/task-validation/417-vitals-form/security-frontend-scan-data.json','utf8'));
const referencedBaseline=JSON.parse(readFileSync('C:/w-417/artifacts/task-validation/417-vitals-form/security-baseline-scan-data.json','utf8'));
assert.deepEqual(referencedCurrent.findings,referencedBaseline.findings);
const inheritedFindings=referencedCurrent.findings.map(f=>{const loc=f.location.replaceAll('\\','/'),path='frontend/src/'+loc.slice(0,loc.lastIndexOf(':'));git(['diff','--exit-code',baseline,commit,'--',path]);return{...f,path,unchanged:true};});
writeFileSync(resolve(base,'source/security-diff-receipt.json'),JSON.stringify({commit,baseline,changedFileCount:paths.length,blobs,protectedPaths,protectedPathsUnchanged:true,changedRiskyMarkers,canonicalCredentialScan:{exit:scan.status,sourceBound:true},inheritedScannerFindings:{provenance:'Root machine scanner JSON inspected independently; NOT a new broad scanner execution by QA',findings:inheritedFindings,exactBaselineMatch:true},limitations:'No globally clean dependency/security/full-suite claim; no production auth, physical hardware or real database persistence claim'},null,2));
console.log('Independent security diff review receipt: 10 canonical application blobs, configured credential scan PASS, protected boundaries unchanged; 3 inherited MEDIUM findings baseline-identical and untouched.');
