import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,readdirSync,statSync,mkdirSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
const root=resolve('artifacts/task-validation/426-room-actions/independent-qa2'),sha=b=>createHash('sha256').update(b).digest('hex'),head='1436602e81d0c03625cfa73ce24974099e919612',base='b7ae14d120c1e70ccf72784206a505f8c48f975e';
const git=(...a)=>execFileSync('git',a,{maxBuffer:20e6});
assert.equal(git('rev-parse','HEAD').toString().trim(),head);
const before=JSON.parse(readFileSync(root+'/source-before.json')),after=JSON.parse(readFileSync(root+'/source-after.json'));assert.deepEqual(before,after);assert.equal(before.status,'');assert.deepEqual(before.untracked,[]);
const changed=git('diff','--name-only',base+'..'+head).toString().trim().split('\n');assert.equal(changed.length,8);
const blobs=changed.map(path=>{const blob=git('show',head+':'+path),raw=readFileSync(path),canonical=Buffer.from(raw.toString('utf8').replace(/\r\n/g,'\n'));assert.equal(sha(blob),sha(canonical));return {path,gitBlobSha256:sha(blob),physicalSha256:sha(raw)};});
writeFileSync(root+'/source-integrity.json',JSON.stringify({head,base,files:before.files.length,sourceSha256:before.sourceSha256,beforeAfterIdentical:true,scope:changed,blobs},null,2));writeFileSync(root+'/diff-review.txt',git('diff',base+'..'+head));
const recipes=readdirSync(root+'/recipes').map(name=>({path:'recipes/'+name,sha256:sha(readFileSync(root+'/recipes/'+name))}));writeFileSync(root+'/replay-receipt.json',JSON.stringify({head,env:{APP_URL:'http://127.0.0.1:7519',SOURCE_COMMIT:head},recipes,runs:[{recipe:'browser.mjs',out:'browser01',count:6,status:'PASS'},{recipe:'supplemental.mjs',out:'supplemental01',count:5,status:'PASS'},{recipe:'long-labels.mjs',out:'long01',count:6,status:'PASS'},{recipe:'room-headers.mjs',out:'room-headers01',status:'FAIL',measuredRight:517.34375},{recipe:'delete-header.mjs',out:'delete-header01',status:'FAIL',measuredRight:611.09375}],verdict:'FAILED VALIDATION'},null,2));
for(const dir of ['browser01','supplemental01','long01']){const r=JSON.parse(readFileSync(root+'/'+dir+'/test-results/browser-results.json'));assert.equal(r.applicationCommit,head);for(const s of r.states){for(const k of ['unexpected','external','clinicalWrites','pageErrors'])assert.deepEqual(s[k],[]);assert.ok(s.allowedMockMutations.every(m=>m.method==='PUT'));}}
for(const dir of ['room-headers01','delete-header01']){const r=JSON.parse(readFileSync(root+'/'+dir+'/test-results/failure.json'));for(const s of r.states){for(const k of ['unexpected','external','clinicalWrites','pageErrors','allowedMockMutations','errors','httpErrors'])assert.deepEqual(s[k],[]);}}
const reportDir=root+'/playwright-report';mkdirSync(reportDir,{recursive:true});writeFileSync(reportDir+'/index.html','<!doctype html><html lang="en"><meta charset="utf-8"><title>426 independent QA2</title><h1>FAILED VALIDATION — immutable '+head+'</h1><p>Generated from actual Playwright library assertions; not native Test runner report. Original 17 cases passed. Two additional valid32W mobile resource headings fail.</p><ul><li>Inline room title right517.34375 exceeds376.</li><li>Deletion title right611.09375 exceeds374.390625; message/button overflow in actual pixels.</li></ul><p>No actual mutation or DELETE; source unchanged. Full raw evidence retained.</p></html>');
function walk(d){return readdirSync(d).flatMap(n=>{const p=d+'/'+n;if(n==='runtime-cache'||n==='artifact-manifest.json')return [];return statSync(p).isDirectory()?walk(p):[p];});}
const paths=walk(root).sort(),patterns=[/gh[pousr]_[A-Za-z0-9]{20,}/,/sk-(?:proj-)?[A-Za-z0-9_-]{20,}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/];for(const p of paths){const b=readFileSync(p);if(!p.endsWith('.zip')&&!p.endsWith('.png')&&!p.endsWith('.webm'))for(const re of patterns)assert.equal(re.test(b.toString('utf8')),false,'Artifact privacy pattern '+relative(root,p));}
writeFileSync(root+'/privacy-receipt.json',JSON.stringify({scope:'All raw text artifacts scanned for credential/private-key patterns; source/build/native checks separately. Synthetic fixture inspection. Root must still scan configured credential values and ZIP members before public release.',files:paths.length,findings:0},null,2));
const files=walk(root).sort().map(p=>({path:relative(root,p).replaceAll('\\','/'),sha256:sha(readFileSync(p))}));writeFileSync(root+'/artifact-manifest.json',JSON.stringify({head,files},null,2));console.log(JSON.stringify({head,manifestSha256:sha(readFileSync(root+'/artifact-manifest.json')),fileCount:files.length,sourceSha256:before.sourceSha256,recipes,verdict:'FAILED VALIDATION'}));
