import {browser,setup,openImport,finish,expect,out,report,newJob,memoryKey} from './fixture.mjs';
import {writeFileSync} from 'node:fs';
const results=[];
const upload=async(ctx,names=['synthetic-letter.png'])=>{
 const w=ctx.page.getByTestId('import-documents-workspace');
 const chooser=ctx.page.waitForEvent('filechooser');
 await w.getByRole('button',{name:await w.getByRole('button',{name:'Carica documento',exact:true}).count()?'Carica documento':'Seleziona file',exact:true}).click();
 await (await chooser).setFiles(names.map(name=>({name,mimeType:'image/png',buffer:ctx.syntheticPng})));
};
const empty=async ctx=>{
 const w=ctx.page.getByTestId('import-documents-workspace');
 await expect(w.getByRole('heading',{name:'Aggiungi la lettera di dimissione'})).toBeVisible();
 await expect(w.getByRole('button',{name:'Carica documento',exact:true})).toHaveClass('btn-primary');
 await expect(w.getByRole('button',{name:'Scansiona',exact:true})).toHaveClass('btn-secondary');
 await expect(w.getByRole('tablist')).toHaveCount(0);
 for(const name of ['Rinomina','Lettera precedente','Lettera successiva','Elimina lettera vuota','Avvia elaborazione','+ Nuova lettera'])await expect(w.getByRole('button',{name,exact:true})).toHaveCount(0);
 await expect(w.locator('.import-session-limits')).toHaveCount(0);
 return w;
};
async function scenario(name,options,run){const ctx=await setup({session:newJob(),...options});try{await openImport(ctx);await run(ctx);await ctx.page.screenshot({path:`${out}/screenshots/${name}.png`});await finish(ctx,name);results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:String(e)});writeFileSync(`${out}/test-results/failure.json`,JSON.stringify({name,error:String(e)},null,2));await ctx.page.screenshot({path:`${out}/screenshots/${name}-failure.png`}).catch(()=>{});await ctx.context.tracing.stop({path:`${out}/trace/${name}-failure.zip`}).catch(()=>{});await ctx.context.close();throw e;}finally{report(results);}}
try {
 for(const mobile of [false,true])await scenario(mobile?'empty-mobile':'empty-desktop',{mobile},async ctx=>{const w=await empty(ctx);await expect(w).toContainText('Formati: PDF, JPEG, PNG');await expect(w).toContainText('25 MB per file, 25 MB complessivi');await expect(w.locator('input[type=file]')).toHaveAttribute('accept','application/pdf,image/jpeg,image/png');const load=w.getByRole('button',{name:'Carica documento',exact:true});await load.focus();await expect(load).toBeFocused();await ctx.page.keyboard.press('Tab');await expect(w.getByRole('button',{name:'Scansiona',exact:true})).toBeFocused();expect(await w.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);expect(await ctx.page.getByRole('dialog',{name:'Importa lettere di dimissione'}).evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);});
 await scenario('custom-limits-formats',{},async ctx=>{ctx.state.session.limits={...ctx.state.session.limits,maxPages:7,maxSourceFiles:4,maxGroups:3,maxFileBytes:2097152,maxTotalBytes:5242880,acceptedMimeTypes:['application/pdf','image/png']};await ctx.page.getByRole('button',{name:'Chiudi importazione',exact:true}).last().click();await ctx.page.getByRole('button',{name:'Importa lettera di dimissione',exact:true}).click();const w=await empty(ctx);await expect(w).toContainText('Formati: PDF, PNG');await expect(w).toContainText('7 pagine, 4 file e 3 lettere');await expect(w).toContainText('2 MB per file, 5 MB complessivi');await expect(w.locator('input[type=file]')).toHaveAttribute('accept','application/pdf,image/png');});
 await scenario('first-default-group', {session:{...newJob(),manifest:{version:1,revision:1,groups:[],pages:[]}}},async ctx=>{await empty(ctx);await upload(ctx);await expect(ctx.page.locator('.import-page')).toHaveCount(1);expect(ctx.state.manifestEdits.length).toBe(1);expect(ctx.state.uploads[0].metadata.expectedRevision).toBe(2);});
 await scenario('multiple-pages-letters-management',{},async ctx=>{await upload(ctx,['synthetic-first.png','synthetic-second.png']);const w=ctx.page.getByTestId('import-documents-workspace');await expect(w.locator('.import-page')).toHaveCount(2);await expect(w.getByRole('button',{name:'Avvia elaborazione',exact:true})).toBeEnabled();const first=ctx.state.session.manifest.pages[0].id;await w.getByRole('button',{name:'Sposta pagina 1 dopo',exact:true}).click();await expect.poll(()=>ctx.state.session.manifest.pages.find(p=>p.id===first)?.sortOrder).toBe(1);await w.getByRole('button',{name:'+ Nuova lettera',exact:true}).click();await expect(w.getByRole('button',{name:'Elimina lettera vuota',exact:true})).toBeVisible();await expect(w.getByRole('heading',{name:'Aggiungi la lettera di dimissione'})).toHaveCount(0);await expect(w.getByRole('button',{name:'Avvia elaborazione',exact:true})).toBeDisabled();await w.getByLabel('Nome lettera').fill('Seconda lettera QA');await w.getByRole('button',{name:'Rinomina',exact:true}).click();await expect(w.getByRole('heading',{name:'Seconda lettera QA',exact:true})).toBeVisible();await w.getByRole('button',{name:'Lettera precedente',exact:true}).click();await expect.poll(()=>ctx.state.session.manifest.groups.find(g=>g.label==='Seconda lettera QA').sortOrder).toBe(0);await w.getByRole('tab',{name:'Lettera sintetica · 2 pagine',exact:true}).click();await w.locator('.import-page').first().getByLabel('Sposta nella lettera').selectOption({label:'Seconda lettera QA'});await expect(w.locator('.import-page')).toHaveCount(1);await w.getByRole('tab',{name:'Seconda lettera QA · 1 pagine',exact:true}).click();await expect(w.locator('.import-page')).toHaveCount(1);await expect(w.getByRole('button',{name:'Avvia elaborazione',exact:true})).toBeEnabled();});
 await scenario('pending-first-upload',{},async ctx=>{ctx.state.holdUpload=true;await upload(ctx);const w=await empty(ctx);await expect(w).toContainText('Salvataggio in corso');await expect(w.getByRole('button',{name:'Carica documento',exact:true})).toBeDisabled();await expect.poll(()=>ctx.state.uploads.length).toBe(1);ctx.state.holdUpload=false;ctx.state.resumeUpload();await expect(w.locator('.import-page')).toHaveCount(1);});
 await scenario('failed-first-upload-retry',{},async ctx=>{ctx.state.rejectUpload=true;await upload(ctx);const w=await empty(ctx);await expect(w.getByRole('button',{name:'Riprova caricamento',exact:true})).toBeVisible();await expect(w.getByRole('button',{name:'Scarta pagine non salvate',exact:true})).toBeVisible();await w.getByRole('button',{name:'Riprova caricamento',exact:true}).click();await expect(w.locator('.import-page')).toHaveCount(1);expect(ctx.state.uploads.length).toBe(2);expect(ctx.state.uploads[0]).toEqual(ctx.state.uploads[1]);});
 await scenario('lost-first-upload-idempotency',{},async ctx=>{ctx.state.loseUpload=true;await upload(ctx);const w=await empty(ctx);await expect(w.getByRole('button',{name:'Riprova caricamento',exact:true})).toBeVisible();await w.getByRole('button',{name:'Riprova caricamento',exact:true}).click();await expect(w.locator('.import-page')).toHaveCount(1);expect(ctx.state.uploads[0]).toEqual(ctx.state.uploads[1]);expect(ctx.state.session.manifest.pages.length).toBe(1);});
 await scenario('failed-first-upload-discard',{},async ctx=>{ctx.state.rejectUpload=true;await upload(ctx);const w=await empty(ctx);await w.getByRole('button',{name:'Scarta pagine non salvate',exact:true}).click();await expect(w.getByRole('button',{name:'Riprova caricamento',exact:true})).toHaveCount(0);await expect(w.getByRole('button',{name:'Carica documento',exact:true})).toBeEnabled();expect(ctx.state.session.manifest.pages.length).toBe(0);});
 await scenario('camera-denied-file-fallback',{},async ctx=>{await ctx.page.evaluate(()=>Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:()=>Promise.reject(new DOMException('Synthetic camera denied','NotAllowedError'))}}));await ctx.page.getByTestId('scatta-foto').click();await expect(ctx.page.getByTestId('camera-denied')).toBeVisible();const chooser=ctx.page.waitForEvent('filechooser');await ctx.page.getByRole('button',{name:'Apri importazione',exact:true}).click();await (await chooser).setFiles({name:'synthetic-fallback.png',mimeType:'image/png',buffer:ctx.syntheticPng});await expect(ctx.page.locator('.import-page')).toHaveCount(1);});
 await scenario('preview-and-replace',{},async ctx=>{await upload(ctx);const w=ctx.page.getByTestId('import-documents-workspace');await expect(w.locator('.import-page')).toHaveCount(1);const original=ctx.state.session.manifest.pages[0];await w.getByRole('button',{name:/Anteprima pagina 1/}).click();const preview=ctx.page.getByRole('dialog',{name:'Anteprima · pagina 1',exact:true});await expect(preview.getByRole('img')).toBeVisible();await preview.getByRole('button',{name:'Chiudi anteprima',exact:true}).last().click();await ctx.page.evaluate(()=>Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:()=>Promise.reject(new DOMException('Synthetic camera denied','NotAllowedError'))}}));await w.getByRole('button',{name:'Rifai',exact:true}).click();await expect(ctx.page.getByTestId('camera-denied')).toBeVisible();const chooser=ctx.page.waitForEvent('filechooser');await ctx.page.getByRole('button',{name:'Apri importazione',exact:true}).click();await (await chooser).setFiles({name:'synthetic-replacement.png',mimeType:'image/png',buffer:ctx.syntheticPng});await expect(w).toContainText('synthetic-replacement.png');expect(ctx.state.session.manifest.pages[0].id).toBe(original.id);expect(ctx.state.session.manifest.pages[0].documentId).not.toBe(original.documentId);expect(ctx.state.session.manifest.pages.length).toBe(1);});
 await scenario('last-page-removal',{},async ctx=>{await upload(ctx);await expect(ctx.page.locator('.import-page')).toHaveCount(1);ctx.page.once('dialog',d=>d.accept());await ctx.page.getByRole('button',{name:'Rimuovi pagina 1',exact:true}).click();await empty(ctx);expect(ctx.state.session.manifest.groups.length).toBe(1);expect(ctx.state.session.documents.length).toBe(0);});
 await scenario('cancel-file-picker',{},async ctx=>{const chooser=ctx.page.waitForEvent('filechooser');await ctx.page.getByRole('button',{name:'Carica documento',exact:true}).click();await (await chooser).setFiles([]);await empty(ctx);expect(ctx.state.uploads).toEqual([]);expect(ctx.state.manifestEdits).toEqual([]);});
 await scenario('saved-content-close-reload',{},async ctx=>{await upload(ctx);await expect(ctx.page.locator('.import-page')).toHaveCount(1);const saved=structuredClone(ctx.state.session.manifest);await ctx.page.getByRole('button',{name:'Chiudi e riprendi la sessione',exact:true}).last().click();await ctx.page.reload();await openImport(ctx);await expect(ctx.page.locator('.import-page')).toHaveCount(1);expect(ctx.state.session.manifest).toEqual(saved);expect(await ctx.page.evaluate(key=>localStorage.getItem(key),memoryKey)).toBe(ctx.state.session.id);await expect(ctx.page.getByRole('heading',{name:'Aggiungi la lettera di dimissione'})).toHaveCount(0);});

 await scenario('preexisting-empty-groups', {session:{...newJob(),manifest:{...newJob().manifest,groups:[...newJob().manifest.groups,{...newJob().manifest.groups[0],id:'second-empty',label:'Lettera vuota',sortOrder:1}]}}},async ctx=>{await empty(ctx);expect(ctx.state.session.manifest.groups.length).toBe(2);await upload(ctx);const w=ctx.page.getByTestId('import-documents-workspace');await expect(w.getByRole('tablist')).toBeVisible();await expect(w.getByRole('tab')).toHaveCount(2);await expect(w.getByRole('button',{name:'Avvia elaborazione',exact:true})).toBeDisabled();await w.getByRole('tab',{name:'Lettera vuota · 0 pagine',exact:true}).click();await w.getByRole('button',{name:'Elimina lettera vuota',exact:true}).click();await expect(w.getByRole('tab')).toHaveCount(1);await expect(w.getByRole('button',{name:'Avvia elaborazione',exact:true})).toBeEnabled();});
 await scenario('global-original-with-zero-pages', {session:{...newJob(),documents:[{id:'synthetic-orphan',filename:'synthetic-source.png',mimeType:'image/png',sizeBytes:200,pageCount:1,contentUrl:'/ai/extraction/jobs/synthetic-session-421/files/synthetic-orphan/content'}]}},async ctx=>{const w=ctx.page.getByTestId('import-documents-workspace');await expect(w.getByRole('heading',{name:'Aggiungi la lettera di dimissione'})).toHaveCount(0);await expect(w.getByRole('tablist')).toBeVisible();await expect(w.getByRole('button',{name:'Seleziona file',exact:true})).toBeVisible();await expect(w).toContainText('1 / 30 file originali');});
 await scenario('mobile-upload-management',{mobile:true},async ctx=>{await upload(ctx);const w=ctx.page.getByTestId('import-documents-workspace');await expect(w.locator('.import-page')).toHaveCount(1);await expect(w.getByRole('button',{name:'+ Nuova lettera',exact:true})).toBeVisible();await expect(w.getByRole('button',{name:'Avvia elaborazione',exact:true})).toBeEnabled();expect(await w.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);expect(await ctx.page.getByRole('dialog',{name:'Importa lettere di dimissione'}).evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);});
 await scenario('keyboard-enter-file-choice',{},async ctx=>{const w=await empty(ctx);await w.getByRole('button',{name:'Carica documento',exact:true}).focus();const chooser=ctx.page.waitForEvent('filechooser');await ctx.page.keyboard.press('Enter');await (await chooser).setFiles({name:'synthetic-keyboard.png',mimeType:'image/png',buffer:ctx.syntheticPng});await expect(w.locator('.import-page')).toHaveCount(1);expect(ctx.state.uploads[0].filename).toBe('synthetic-keyboard.png');});
} finally {report(results);await browser.close();}

