import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect,setup,finish,guards,reload,categories,types,png,metadata} from './transport.mjs';
const out=resolve(process.argv[2]);assert.ok(process.argv[2]);assert.equal(existsSync(out),false);for(const p of ['screenshots','video','trace','test-results','playwright-report'])mkdirSync(out+'/'+p,{recursive:true});
const browser=await chromium.launch({headless:true}),contexts=[],states=[],outcomes=[];
async function check(name,ctx,fn){await fn();await guards(ctx);outcomes.push({name,status:'PASS'});ctx.state.asserted.push(name);console.log('PASS '+name);}
async function shot(ctx,name,target){if(name.endsWith('-first-native-form'))target=ctx.page.getByRole('heading',{name:'Nuovo documento',exact:true});if(target)await target.scrollIntoViewIfNeeded();await ctx.page.screenshot({path:out+'/screenshots/'+name+'.png',fullPage:true});if(name.endsWith('-first-native-form')){await ctx.page.getByRole('button',{name:'Salva documento',exact:true}).scrollIntoViewIfNeeded();await ctx.page.screenshot({path:out+'/screenshots/'+name+'-save-action.png',fullPage:true});}}
async function empty(ctx){await expect(ctx.page.getByRole('region',{name:'Archivio senza documenti'})).toBeVisible();await expect(ctx.page.getByRole('heading',{name:'Nessun documento',exact:true})).toBeVisible();}
async function add(ctx){const b=ctx.page.getByRole('button',{name:'Aggiungi documento',exact:true});await b.focus();await ctx.page.keyboard.press('Enter');await expect(ctx.page.getByRole('heading',{name:'Nuovo documento',exact:true})).toBeVisible();}
async function make(width,height,opts){const ctx=await setup(browser,out,width,height,opts);contexts.push(ctx);states.push(ctx.state);return ctx;}
try{
for(const [width,height,device] of [[1150,1004,'desktop'],[390,844,'mobile']]){
 let ctx=await make(width,height),page=ctx.page;
 await check(device+' true empty guides first action; compact closed categories no management controls',ctx,async()=>{await empty(ctx);await expect(page.getByText('Aggiungi il primo documento alla cartella del paziente.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Aggiungi documento',exact:true})).toBeVisible();await expect(page.locator('.archive-empty__guide')).toContainText('PDF, JPEG, JPG o PNG · massimo 15 MB.');await expect(page.locator('.archive-empty details')).not.toHaveAttribute('open','');await expect(page.locator('.patient-document-archive__filters,.patient-document-archive__selection,.patient-document-archive__workspace')).toHaveCount(0);await expect(page.getByRole('button',{name:/Stampa selezionati/})).toHaveCount(0);await expect(page.locator('.archive-empty button:disabled')).toHaveCount(0);const box=await page.locator('.archive-empty').boundingBox();expect(box.width).toBeLessThanOrEqual(width);await shot(ctx,device+'-empty-next-step');});
 await check(device+' native keyboard details all10 categories unchanged and assessment origin explained',ctx,async()=>{const summary=page.locator('.archive-empty summary');await summary.focus();await page.keyboard.press('Enter');await expect(page.locator('.archive-empty details')).toHaveAttribute('open','');await expect(page.locator('.archive-empty li')).toHaveCount(10);expect(await page.locator('.archive-empty li strong').allTextContents()).toEqual(categories);await expect(page.getByText('PDF generati dalla sezione Moduli, non caricati manualmente.',{exact:true})).toBeVisible();await shot(ctx,device+'-categories-expanded');await summary.focus();await page.keyboard.press('Enter');await expect(page.locator('.archive-empty details')).not.toHaveAttribute('open','');expect(ctx.state.allowedMockMutations).toEqual([]);});
 await check(device+' native add retains9 optgroups22 types; keyboard cancel zero writes',ctx,async()=>{await add(ctx);const select=page.getByRole('combobox',{name:'Tipo documento',exact:true});await expect(select).toBeVisible();expect(await select.locator('optgroup').evaluateAll(nodes=>nodes.map(n=>n.label))).toEqual(categories.slice(1));expect(await select.locator('option').evaluateAll(nodes=>nodes.map(n=>n.value))).toEqual(types);await select.selectOption('piano_terapeutico');await expect(select).toHaveValue('piano_terapeutico');await expect(page.getByRole('button',{name:'Scatta foto',exact:true})).toBeVisible();await shot(ctx,device+'-first-native-form');await page.getByRole('button',{name:'Annulla',exact:true}).focus();await page.keyboard.press('Enter');await empty(ctx);expect(ctx.state.allowedMockMutations).toEqual([]);});
 await check(device+' missing attachment rejected locally and no writes',ctx,async()=>{await add(ctx);await page.getByRole('button',{name:'Salva documento',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Seleziona il file da archiviare oppure indica il documento come mancante.'})).toBeVisible();expect(ctx.state.allowedMockMutations).toEqual([]);await page.getByRole('button',{name:'Annulla',exact:true}).click();await empty(ctx);});
 await check(device+' synthetic first PNG exact scoped upload and record save transition to management',ctx,async()=>{await add(ctx);await page.getByRole('combobox',{name:'Tipo documento',exact:true}).selectOption('prescrizione');await page.getByLabel('Descrizione',{exact:true}).fill('Documento sintetico QA 423');await page.getByLabel('Seleziona documento',{exact:true}).setInputFiles({name:'synthetic-423.png',mimeType:'image/png',buffer:png});await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Chiudi anteprima',exact:true}).last().click();await page.getByRole('button',{name:'Salva documento',exact:true}).click();await expect(page.getByRole('heading',{name:'Nuovo documento',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Documento sintetico QA 423',exact:true})).toBeVisible();await expect(page.getByLabel('Cerca nell’archivio',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Archivio senza documenti'})).toHaveCount(0);expect(ctx.state.uploads).toBe(1);expect(ctx.state.cartellaSaves).toBe(1);await shot(ctx,device+'-first-document-saved');});
 await check(device+' synthetic persisted first file and record survive native reload and re-login',ctx,async()=>{await reload(ctx);await expect(page.getByRole('button',{name:'Documento sintetico QA 423',exact:true})).toBeVisible();await expect(page.locator('.patient-document-archive__item')).toContainText('synthetic-423.png');await expect(page.locator('.patient-document-archive__summary')).toHaveText('1 documento trovato');expect(ctx.state.uploads).toBe(1);expect(ctx.state.cartellaSaves).toBe(1);await shot(ctx,device+'-first-document-reloaded');});
 await check(device+' populated search-zero distinct from realempty; existing management retained',ctx,async()=>{await page.getByLabel('Cerca nell’archivio',{exact:true}).fill('nonexistent synthetic query');await expect(page.getByText('Nessun documento corrisponde alla ricerca.',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Archivio senza documenti'})).toHaveCount(0);await expect(page.locator('.patient-document-archive__selection')).toBeVisible();await expect(page.getByRole('button',{name:'+ Aggiungi',exact:true})).toBeVisible();await shot(ctx,device+'-filtered-zero-not-empty');await page.getByLabel('Cerca nell’archivio',{exact:true}).fill('');await expect(page.getByRole('button',{name:'Documento sintetico QA 423',exact:true})).toBeVisible();});
 await finish(ctx,out,device+'-first-upload');
 for(const grant of ['no-upload','no-save','missing']){ctx=await make(width,height,{grant});page=ctx.page;await check(device+' explicit '+grant+' policy read-only explains referent no add/form or writes',ctx,async()=>{await empty(ctx);await expect(page.getByText(/Il tuo ruolo non può aggiungere documenti/)).toBeVisible();await expect(page.getByText(/rivolgiti al coordinatore o all’amministrazione/)).toBeVisible();await expect(page.getByRole('button',{name:'Aggiungi documento',exact:true})).toHaveCount(0);await expect(page.locator('.patient-archive-form')).toHaveCount(0);expect(ctx.state.allowedMockMutations).toEqual([]);await shot(ctx,device+'-empty-'+grant);});await finish(ctx,out,device+'-'+grant);}
 ctx=await make(width,height,{operator:false});page=ctx.page;await check(device+' administrator same capability-driven first action not professionalrole',ctx,async()=>{await empty(ctx);await add(ctx);await expect(page.getByRole('combobox',{name:'Tipo documento',exact:true})).toHaveValue('documento_identita');await page.getByRole('button',{name:'Annulla',exact:true}).click();expect(ctx.state.allowedMockMutations).toEqual([]);await empty(ctx);});await finish(ctx,out,device+'-admin');
 ctx=await make(width,height,{operator:false,grant:'no-upload'});page=ctx.page;await check(device+' administrator denied upload receives same organizational referent',ctx,async()=>{await empty(ctx);await expect(page.getByText(/Il tuo ruolo non può aggiungere documenti/)).toBeVisible();await expect(page.getByRole('button',{name:'Aggiungi documento',exact:true})).toHaveCount(0);expect(ctx.state.allowedMockMutations).toEqual([]);});await finish(ctx,out,device+'-admin-denied');
 ctx=await make(width,height,{mode:'hold'});page=ctx.page;await check(device+' delayed metadata is loading not empty and no active add',ctx,async()=>{await expect.poll(()=>ctx.state.held).toBeGreaterThan(0);await expect(page.getByText('Caricamento dell’archivio completo…',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Archivio senza documenti'})).toHaveCount(0);await expect(page.getByRole('button',{name:'+ Aggiungi',exact:true})).toBeDisabled();await shot(ctx,device+'-loading-not-empty');ctx.release();await empty(ctx);expect(ctx.state.allowedMockMutations).toEqual([]);});await finish(ctx,out,device+'-loading');
 for(const mode of ['error','malformed']){ctx=await make(width,height,{mode});page=ctx.page;await check(device+' '+mode+' metadata distinct partial/error with native retry to empty',ctx,async()=>{await expect(page.getByText('Impossibile caricare tutti i file. Le schede visibili sono un elenco parziale.',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Archivio senza documenti'})).toHaveCount(0);await expect(page.getByRole('button',{name:'+ Aggiungi',exact:true})).toBeDisabled();if(mode==='error')expect(ctx.state.expectedErrors.length).toBeGreaterThan(0);else expect(ctx.state.expectedErrors).toEqual([]);await shot(ctx,device+'-'+mode+'-not-empty');ctx.state.mode='ready';await page.getByRole('button',{name:'Riprova archivio',exact:true}).click();await empty(ctx);expect(ctx.state.allowedMockMutations).toEqual([]);});await finish(ctx,out,device+'-'+mode);}
 for(const grant of ['no-save','missing']){ctx=await make(width,height,{grant,populated:true,xss:true});page=ctx.page;await check(device+' populated '+grant+' guards edits/removal; escaped literal title no XSS',ctx,async()=>{const list=page.locator('.patient-document-archive__list');await expect(list.getByRole('button',{name:'<img src=x onerror=alert(423)>',exact:true})).toBeVisible();await expect(list.locator('img')).toHaveCount(0);await expect(list.getByRole('button',{name:'Modifica dettagli',exact:true})).toHaveCount(0);await expect(list.getByRole('button',{name:'Rimuovi scheda',exact:true})).toHaveCount(0);expect(ctx.state.allowedMockMutations).toEqual([]);await shot(ctx,device+'-populated-'+grant+'-xss',list);});await finish(ctx,out,device+'-populated-'+grant);}
 for(const grant of ['no-classify','no-upload']){
 ctx=await make(width,height,{grant,populated:true,metadataEdit:true});page=ctx.page;
 await check(device+' '+grant+' existing file native metadata-only edit save preserves type/id with exact PUT no upload/PATCH',ctx,async()=>{const list=page.locator('.patient-document-archive__list');await expect(list.getByRole('button',{name:'Modifica dettagli',exact:true})).toBeVisible();await list.getByRole('button',{name:'Modifica dettagli',exact:true}).click();await expect(page.getByRole('heading',{name:'Modifica documento',exact:true})).toBeVisible();const select=page.getByRole('combobox',{name:'Tipo documento',exact:true});await expect(select).toHaveValue('prescrizione');if(grant==='no-classify')await expect(select).toBeDisabled();else await expect(select).toBeEnabled();await expect(page.getByText('File archiviato',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Carica file',exact:true})).toHaveCount(0);await page.getByLabel('Note',{exact:true}).fill('Nota sintetica QA 423 aggiornata');await shot(ctx,device+'-'+grant+'-metadata-form-type',select);await shot(ctx,device+'-'+grant+'-metadata-form-save',page.getByRole('button',{name:'Salva documento',exact:true}));await page.getByRole('button',{name:'Salva documento',exact:true}).click();await expect(page.getByRole('heading',{name:'Modifica documento',exact:true})).toHaveCount(0);await expect(list).toContainText('Nota sintetica QA 423 aggiornata');expect(ctx.state.uploads).toBe(0);expect(ctx.state.cartellaSaves).toBe(1);expect(ctx.state.allowedMockMutations.map(m=>m.method)).toEqual(['PUT']);expect(ctx.documents).toEqual([metadata]);expect(ctx.state.requests.filter(r=>r.method==='PATCH')).toEqual([]);await shot(ctx,device+'-'+grant+'-metadata-saved',list);});
 await check(device+' '+grant+' native reload retains edited note and original stored type/file id; remove cancel writes none',ctx,async()=>{await reload(ctx);const list=page.locator('.patient-document-archive__list');await expect(list).toContainText('Nota sintetica QA 423 aggiornata');await expect(list).toContainText('synthetic-423.png');await expect(list.getByText('Prescrizione',{exact:true})).toBeVisible();await list.getByRole('button',{name:'Modifica dettagli',exact:true}).click();await expect(page.getByLabel('Note',{exact:true})).toHaveValue('Nota sintetica QA 423 aggiornata');await expect(page.getByRole('combobox',{name:'Tipo documento',exact:true})).toHaveValue('prescrizione');await page.getByRole('button',{name:'Annulla',exact:true}).click();await list.getByRole('button',{name:'Rimuovi scheda',exact:true}).click();await expect(page.getByRole('alertdialog',{name:'Rimuovi scheda documento',exact:true})).toBeVisible();await page.getByRole('button',{name:'Annulla',exact:true}).click();expect(ctx.state.allowedMockMutations.map(m=>m.method)).toEqual(['PUT']);expect(ctx.documents).toEqual([metadata]);await shot(ctx,device+'-'+grant+'-metadata-reloaded',list);});
 await finish(ctx,out,device+'-'+grant+'-metadata');
 }
 ctx=await make(width,height,{grant:'no-classify'});page=ctx.page;await check(device+' no classify still authorized first upload form; cancel zero writes',ctx,async()=>{await empty(ctx);await add(ctx);await expect(page.getByRole('combobox',{name:'Tipo documento',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'Tipo documento',exact:true}).selectOption('prescrizione');await page.getByRole('button',{name:'Annulla',exact:true}).click();expect(ctx.state.allowedMockMutations).toEqual([]);});await finish(ctx,out,device+'-no-classify-first');
 ctx=await make(width,height,{grant:'null-policy'});page=ctx.page;await check(device+' legacy absent policy uses established server-authoritative presentation compatibility',ctx,async()=>{await empty(ctx);await add(ctx);await page.getByRole('button',{name:'Annulla',exact:true}).click();expect(ctx.state.allowedMockMutations).toEqual([]);});await finish(ctx,out,device+'-null-policy');
}
writeFileSync(out+'/test-results/browser-results.json',JSON.stringify({applicationCommit:process.env.SOURCE_COMMIT,outcomes,states,fixtureTransport:'Actual SPA; all API transport guarded before wire. Only exact synthetic first-upload POST+PUT or explicitly scoped existing-file metadata-only PUT allowed. No PATCH. Reload persistence is mocked transport, NOT real DB or production write proof.'},null,2));
writeFileSync(out+'/playwright-report/index.html','<!doctype html><meta charset="utf-8"><h1>423 independent Playwright library assertions</h1><p>Actual SPA, native UI; assertion receipt, not native Playwright Test reporter. Synthetic guarded transport only.</p><pre>'+JSON.stringify(outcomes,null,2).replaceAll('&','&amp;').replaceAll('<','&lt;')+'</pre>');
}catch(e){for(const [i,c] of contexts.entries()){await c.page.screenshot({path:out+'/screenshots/failure-'+i+'.png',fullPage:true}).catch(()=>{});await c.context.tracing.stop({path:out+'/trace/failure-'+i+'.zip'}).catch(()=>{});}writeFileSync(out+'/test-results/failure.json',JSON.stringify({message:e.message,stack:e.stack,outcomes,states},null,2));throw e;}finally{for(const c of contexts)await c.context.close().catch(()=>{});await browser.close();}
