import { readFileSync,writeFileSync,readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
const folder='artifacts/task-validation/405-appointment-labels';
const sha=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
const head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
if(head!=='21f8c75c221c464fb00499326cf261143b444bf4')throw Error('Unexpected candidate HEAD');
const paths=execFileSync('git',['ls-files','frontend','scripts/run-node-tests.mjs','scripts/stub-css-loader.mjs','scripts/security/scan-frontend-secrets.mjs'],{encoding:'utf8'}).trim().split('\n');
const source=paths.map(path=>({path,sha256:sha(path)}));
execFileSync('git',['diff','--exit-code','HEAD','--','frontend'],{encoding:'utf8'});
const failureNames=file=>[...new Set(readFileSync(file,'utf8').split(/\r?\n/).filter(line=>line.startsWith('✖ ')&&!line.includes('failing tests:')).map(line=>line.replace(/ \([\d.]+ms\)$/,'').slice(2)))].sort();
const baseline=failureNames('artifacts/task-validation/404-giro-allergies/logs/full-regression.log');
const candidate=failureNames(`${folder}/logs/full-regression.log`);
const regression={baselineCommit:'45f3582dae64b0f34d2c1181286ed1d919d85d97',baselineLog:'artifacts/task-validation/404-giro-allergies/logs/full-regression.log',baselineSha256:sha('artifacts/task-validation/404-giro-allergies/logs/full-regression.log'),candidateTotal:1178,candidatePass:1166,candidateFail:12,baselineFailures:baseline,candidateFailures:candidate,newFailures:candidate.filter(name=>!baseline.includes(name)),removedFailures:baseline.filter(name=>!candidate.includes(name)),unchanged:JSON.stringify(baseline)===JSON.stringify(candidate)};
if(!regression.unchanged||baseline.length!==12)throw Error('Regression baseline mismatch');
writeFileSync(`${folder}/test-results/regression-comparison.json`,JSON.stringify(regression,null,2));
const artifacts=readdirSync(folder,{recursive:true,encoding:'utf8'}).filter(p=>!/independent-source-receipt\.json$/.test(p)).flatMap(p=>{try{return[{path:`${folder}/${p.replaceAll('\\','/')}`,sha256:sha(`${folder}/${p}`)}]}catch{return[];}});
const receipt={candidate:head,baseline:regression.baselineCommit,observedAt:new Date().toISOString(),applicationClean:true,sourceHash:createHash('sha256').update(JSON.stringify(source)).digest('hex'),source,artifacts,policy:{evidenceOnly:true,productionAccess:false,realMutations:0,screenReader:'UNVERIFIED',release:'BLOCKED'},commands:JSON.parse(readFileSync(`${folder}/logs/command-results.json`,'utf8')),regression};
writeFileSync(`${folder}/independent-source-receipt.json`,JSON.stringify(receipt,null,2));
console.log(JSON.stringify({candidate:head,sourceHash:receipt.sourceHash,artifacts:artifacts.length,regressionUnchanged:regression.unchanged,newFailures:regression.newFailures}));
