import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const own=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const repo='C:/w-424-qa', prior=repo+'/artifacts/task-validation/424-reading-action/independent-qa';
const baseline='b5f471cd2cd56839e7ebbd0d3daf0bbf04791468', candidate='67d21c3e9257a5acb8c9b25130c9417fb92185fb', current='b7ae14d120c1e70ccf72784206a505f8c48f975e';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const json=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const git=(...args)=>execFileSync('git',args,{cwd:repo});
assert.equal(git('rev-parse','HEAD').toString().trim(),candidate);
const manifestPath=prior+'/immutable-manifest.json', manifestBytes=fs.readFileSync(manifestPath), manifest=json(manifestPath);
assert.equal(sha(manifestBytes),'7079affea9bc5191002a1af77c113fd3016cddcb09786568afba211978175058');
assert.equal(manifest.files.length,129);
for(const entry of manifest.files){const b=fs.readFileSync(path.join(prior,entry.path));assert.equal(sha(b),entry.sha256,entry.path);assert.equal(b.length,entry.bytes,entry.path);}
const oldSource=json(prior+'/source-before/source-receipt.json');
for(const entry of oldSource.files)assert.equal(sha(fs.readFileSync(path.join(repo,entry.path))),entry.sha256,entry.path);
const paths=['frontend/src/components/operator/ConsegneUnreadQueue.tsx','frontend/src/components/operator/cartella/DiarioPazienteTab.tsx','frontend/src/components/operator/cartella/DiaryThreadReceipt.css','frontend/src/components/operator/cartella/DiaryThreadReceipt.tsx','frontend/src/lib/__tests__/diaryReading.test.ts'].sort();
assert.deepEqual(git('diff','--name-only',baseline,candidate).toString().trim().split(/\r?\n/).sort(),paths);
const blobs=paths.map(p=>{const a=git('cat-file','blob',candidate+':'+p),b=git('cat-file','blob',current+':'+p);assert.deepEqual(a,b,p);return{path:p,sha256:sha(a),bytes:a.length,candidateBlob:git('rev-parse',candidate+':'+p).toString().trim(),currentBlob:git('rev-parse',current+':'+p).toString().trim()};});
const protectedPaths=['backend','prisma','package.json','package-lock.json','frontend/package.json','frontend/package-lock.json','frontend/tsconfig.json','frontend/tsconfig.app.json','frontend/tsconfig.node.json','frontend/vite.config.ts','frontend/vercel.json','frontend/src/config.ts','.github/workflows'];
assert.equal(git('diff','--name-only',candidate,current,'--',...protectedPaths).toString().trim(),'');
const commands=json(prior+'/commands/command-results.json');
const focused=commands.records.find(r=>r.name==='focused');assert.equal(focused.tests,32);assert.equal(focused.pass,32);assert.equal(focused.fail,0);
const db=json(prior+'/db/result.json');assert.equal(db.status,0);assert.equal(db.realPostgres,true);assert.equal(db.migrations,57);
const ordinary=json(prior+'/attempt01/browser/test-results/browser-results.json'),supplemental=json(prior+'/supplemental03/test-results/browser-results.json');
assert.equal(ordinary.outcomes.length,17);assert.equal(supplemental.outcomes.length,4);for(const r of [...ordinary.outcomes,...supplemental.outcomes])assert.equal(r.status,'PASS');
const out=path.join(own,'pre-run');assert.equal(fs.existsSync(out),false,'new pre-run only');fs.mkdirSync(path.join(out,'recipes'),{recursive:true});
const recipes=['compiled-browser.mjs','compiled-supplemental.mjs'].map(name=>{const source='C:/w-424/artifacts/task-validation/424-reading-action/compiled-online/pre-run/recipes/'+name,b=fs.readFileSync(source),target=path.join(out,'recipes',name);fs.copyFileSync(source,target);assert.equal(sha(fs.readFileSync(target)),sha(b));return{name,sha256:sha(b),bytes:b.length,source,target};});
const receipt={at:new Date().toISOString(),authority:'Independent release continuation artifact-only',candidate,current,baseline,priorManifestSha256:sha(manifestBytes),priorFilesVerified:129,priorSourceFilesVerified:oldSource.files.length,priorSourceSha256:oldSource.sourceSha256,blobs,protectedPathsUnchanged:protectedPaths,reviewedPriorNotRerun:{focused,db,ordinaryCases:17,supplementalCases:4},recipes};
fs.writeFileSync(path.join(out,'continuity-and-frozen-recipes.json'),JSON.stringify(receipt,null,2));
fs.copyFileSync(manifestPath,path.join(out,'prior-manifest.raw.json'));
console.log(JSON.stringify({verifiedOldFiles:129,verifiedSourceFiles:oldSource.files.length,blobsIdentical:blobs.length,recipes:recipes.map(r=>({name:r.name,sha256:r.sha256})),current}));
