import {browser,setup,openImport,finish,expect,out,report,newJob,memoryKey,identity} from './fixture.mjs';
const results=[];
const footer=p=>p.locator('.import-session-footer');
const content=p=>p.getByTestId('import-documents-workspace');
const newButton=p=>p.getByRole('button',{name:'Nuova importazione',exact:true});
const retry=p=>p.getByRole('button',{name:'Riprova apertura sessione',exact:true});
const shot=(p,n)=>p.screenshot({path:`${out}/screenshots/${n}.png`});
async function truthfulUnavailable(p){await expect(footer(p)).toBeVisible();await expect(footer(p)).not.toContainText(/Chiudendo|pagine già salvate|conserv/);await expect(p.locator('.import-modal__head .icon-btn')).toHaveAttribute('aria-label','Chiudi importazione');}
async function run(name,options,assertions){const startedAt=new Date().toISOString();const ctx=await setup(options);try{await openImport(ctx);await assertions(ctx);await shot(ctx.page,name);await finish(ctx,name);results.push({name,status:'PASS',startedAt,endedAt:new Date().toISOString()});console.log('PASS '+name);}catch(e){await shot(ctx.page,name+'-failed').catch(()=>{});await finish(ctx,name+'-failed').catch(()=>{});results.push({name,status:'FAIL',startedAt,error:e.message});throw e;}}
const saved=()=>{const j=newJob();j.documents=[{id:'synthetic-document',filename:'pagina-sintetica.png',mimeType:'image/png',sizeBytes:67,pageCount:1,contentUrl:'/not-used'}];j.manifest.pages=[{id:'synthetic-page',documentId:'synthetic-document',sourcePageNumber:1,groupId:'synthetic-letter',sortOrder:0,status:'pending',canRetry:false,errorCode:null,error:null}];j.manifest.groups[0].pageCount=1;return j;};
async function close(p){const button=footer(p).getByRole('button',{name:'Chiudi importazione',exact:true});await expect(button).toBeVisible();await button.focus();await p.keyboard.press('Enter');await expect(p.getByRole('dialog')).toHaveCount(0);await expect(p.getByRole('button',{name:'Importa lettera di dimissione',exact:true})).toBeVisible();}
async function reopen(page,state){await page.reload();await openImport({page,state});}
try{
 for(const [status,message] of [['expired','La sessione è scaduta.'],['cancelled','La sessione è stata eliminata.'],['confirmed','Questa importazione è già conclusa.']])await run('authoritative-'+status,{session:newJob(status)},async({page,state})=>{await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('alert')).toContainText(message);await truthfulUnavailable(page);await expect(newButton(page)).toBeVisible();expect(state.created).toBe(0);expect(await page.evaluate(k=>localStorage.getItem(k),memoryKey)).toBe('synthetic-session-420');});
 await run('masked404-neutral-not-deleted',{sessionStatus:404},async({page,state})=>{await expect(page.getByRole('alert')).toContainText('La sessione non è disponibile.');await expect(page.getByRole('alert')).not.toContainText(/scaduta|conclusa|eliminata/);await truthfulUnavailable(page);expect(state.created).toBe(0);});
 for(const fault of ['503','network','403'])await run('temporary-'+fault+'-same-reference',{sessionStatus:fault==='403'?403:503},async({page,state})=>{await expect(retry(page)).toBeVisible();await truthfulUnavailable(page);await expect(newButton(page)).toHaveCount(0);if(fault==='network'){state.networkFailure=true;await retry(page).click();await expect(page.getByRole('alert')).toContainText('Disponibilità della sessione non verificata.');await truthfulUnavailable(page);}state.session=newJob();state.sessionStatus=200;await retry(page).focus();await page.keyboard.press('Enter');await expect(content(page)).toContainText('0 / 30 pagine');expect(state.created).toBe(0);expect(state.requests.filter(r=>r.path.startsWith('/ai/extraction/jobs/')).every(r=>r.path==='/ai/extraction/jobs/synthetic-session-420')).toBe(true);expect(await page.evaluate(k=>localStorage.getItem(k),memoryKey)).toBe('synthetic-session-420');});
 await run('explicit-new-feedback-keyboard-return-and-reload',{},async({page,state})=>{await expect(newButton(page)).toBeVisible();state.delayCreate=600;await newButton(page).focus();await page.keyboard.press('Enter');await expect(page.getByRole('status').filter({hasText:'Creazione nuova sessione…'})).toBeVisible();await truthfulUnavailable(page);await shot(page,'creation-pending');await expect(page.getByRole('status').filter({hasText:'Nuova sessione creata. Aggiungi i documenti da importare.'})).toBeVisible();await expect(content(page)).toContainText('0 / 30 pagine');await shot(page,'creation-success');expect(state.created).toBe(1);await close(page);await reopen(page,state);await expect(content(page)).toContainText('0 / 30 pagine');expect(state.created).toBe(1);expect(state.creationKeys).toHaveLength(1);expect(await page.evaluate(k=>localStorage.getItem(k),memoryKey)).toBe('synthetic-new-session-420');});
 await run('lost-creation-response-same-idempotency-key',{},async({page,state})=>{await expect(newButton(page)).toBeVisible();state.lostCreate=true;await newButton(page).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('alert')).toContainText('Riprova senza iniziare un’altra importazione.');await expect(page.getByRole('alert')).not.toContainText('non è stata avviata');await truthfulUnavailable(page);expect(state.created).toBe(1);await expect(newButton(page)).toHaveCount(0);await retry(page).click();await expect(page.getByRole('status').filter({hasText:'Nuova sessione creata.'})).toBeVisible();await expect(content(page)).toContainText('0 / 30 pagine');expect(state.creationKeys).toHaveLength(2);expect(state.creationKeys[0]).toBeTruthy();expect(state.creationKeys[0]).toBe(state.creationKeys[1]);expect(state.created).toBe(1);await close(page);await reopen(page,state);await expect(content(page)).toContainText('0 / 30 pagine');expect(state.creationKeys).toHaveLength(2);expect(await page.evaluate(k=>localStorage.getItem(k),memoryKey)).toBe('synthetic-new-session-420');});
 await run('saved-source-qualified-recovery',{session:saved()},async({page,state})=>{await expect(page.locator('[data-page-id="synthetic-page"]')).toContainText('pagina-sintetica.png');await expect(page.locator('.import-page__thumbnail img')).toBeVisible();await expect(footer(page)).toContainText('Chiudendo puoi riprendere le pagine già salvate finché la sessione resta disponibile.');await expect(page.locator('.import-modal__head .icon-btn')).toHaveAttribute('aria-label','Chiudi e riprendi la sessione');await shot(page,'saved-page-before-close');await close(page);await reopen(page,state);await expect(page.locator('[data-page-id="synthetic-page"]')).toContainText('pagina-sintetica.png');await expect(page.locator('.import-page__thumbnail img')).toBeVisible();expect(state.created).toBe(0);});
 await run('result404-not-parent-deletion',{session:newJob('review_ready')},async({page,state})=>{await expect(page.getByRole('alert')).toContainText('Synthetic missing result');await truthfulUnavailable(page);await expect(newButton(page)).toHaveCount(0);await expect(retry(page)).toBeVisible();expect(await page.evaluate(k=>localStorage.getItem(k),memoryKey)).toBe('synthetic-session-420');expect(state.created).toBe(0);});
 await run('page404-not-parent-terminal',{session:saved()},async({page,state})=>{await expect(content(page)).toBeVisible();await expect(page.locator('.import-page__thumbnail img')).toBeVisible();state.pageMissing=true;await close(page);await reopen(page,state);await expect(page.locator('.import-page__thumbnail')).toContainText('Apri anteprima');await expect(page.locator('[data-page-id="synthetic-page"]')).toContainText('pagina-sintetica.png');await expect(newButton(page)).toHaveCount(0);await expect(footer(page)).not.toContainText('Le pagine non possono essere riprese');expect(state.created).toBe(0);});
 await run('terminal-poll-disposes-stale-saved-page',{session:{...saved(),status:'processing'}},async({page,state})=>{await expect(content(page)).toBeVisible();state.session=newJob('confirmed');await page.clock.runFor(2200);await expect(page.getByRole('alert')).toContainText('Questa importazione è già conclusa.');await truthfulUnavailable(page);await expect(content(page)).toHaveCount(0);await expect(page.locator('[data-page-id="synthetic-page"]')).toHaveCount(0);await expect(newButton(page)).toBeVisible();expect(state.created).toBe(0);});
 await run('mutation-closed-clears-stale-workspace',{session:saved()},async({page,state})=>{await expect(page.locator('[data-page-id="synthetic-page"]')).toBeVisible();await page.getByRole('button',{name:'+ Nuova lettera',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Questa sessione non è più modificabile.');await truthfulUnavailable(page);await expect(content(page)).toHaveCount(0);await expect(newButton(page)).toBeVisible();expect(state.created).toBe(0);});
 for(const expiresAt of ['2026-10-08T18:00:00Z','invalid'])await run('expiry-'+(expiresAt==='invalid'?'invalid':'past')+'-not-fabricated',{session:{...saved(),expiresAt}},async({page,state})=>{await expect(content(page)).toContainText('1 / 30 pagine');await truthfulUnavailable(page);await expect(footer(page)).toContainText('Disponibilità della sessione non verificata');await expect(newButton(page)).toHaveCount(0);await expect(footer(page)).not.toContainText('Scadenza sessione:');expect(state.created).toBe(0);});
 await run('clock-expiry-removes-promise-only',{session:{...saved(),expiresAt:'2026-10-09T18:00:30Z'}},async({page,state})=>{await expect(footer(page)).toContainText('Chiudendo puoi riprendere');await page.clock.runFor(61000);await truthfulUnavailable(page);await expect(content(page)).toBeVisible();await expect(newButton(page)).toHaveCount(0);expect(state.created).toBe(0);});
 await run('different-actor-cannot-reuse-old-reference',{actor:{...identity,id:'QA-NURSE-420-OTHER',name:'Altro Infermiere Sintetico'},session:newJob()},async({page,state})=>{await expect(content(page)).toContainText('0 / 30 pagine');expect(state.created).toBe(1);expect(state.requests.some(r=>r.path==='/ai/extraction/jobs/synthetic-session-420')).toBe(false);expect(await page.evaluate(k=>localStorage.getItem(k),memoryKey)).toBe('synthetic-session-420');expect(await page.evaluate(()=>localStorage.getItem('clinicos:import-session:QA-NURSE-420-OTHER:operatore'))).toBe('synthetic-new-session-420');});
 await run('mobile-terminal-wrap-and-keyboard-return',{mobile:true},async({page})=>{await expect(page.getByRole('alert')).toContainText('La sessione è scaduta.');await truthfulUnavailable(page);await expect(newButton(page)).toBeVisible();expect(await page.locator('.import-session').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await shot(page,'mobile-terminal-before-return');await close(page);});
 await run('mobile-new-feedback-return',{mobile:true},async({page,state})=>{await expect(newButton(page)).toBeVisible();state.delayCreate=500;await newButton(page).click();await expect(page.getByRole('status').filter({hasText:'Creazione nuova sessione…'})).toBeVisible();await expect(page.getByRole('status').filter({hasText:'Nuova sessione creata.'})).toBeVisible();expect(await page.locator('.import-session').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await shot(page,'mobile-creation-success');await close(page);expect(state.created).toBe(1);});
}finally{report(results);await browser.close();}
