import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium,expect,setup,finish,guards,categories,types} from './transport.mjs';
const out=resolve(process.argv[2]);assert.ok(process.argv[2]);assert.equal(existsSync(out),false);for(const p of ['screenshots','video','trace','test-results','playwright-report'])mkdirSync(out+'/'+p,{recursive:true});
const browser=await chromium.launch({headless:true}),contexts=[],outcomes=[],states=[];
try{for(const [width,height,device] of [[1150,1004,'desktop'],[390,844,'mobile']]){const ctx=await setup(browser,out,width,height);contexts.push(ctx);states.push(ctx.state);const page=ctx.page;await expect(page.getByText('Nessun documento in questa cartella.',{exact:true})).toBeVisible();await expect(page.getByLabel('Cerca nell’archivio',{exact:true})).toBeVisible();await expect(page.locator('.patient-document-archive__selection')).toBeVisible();await expect(page.getByRole('button',{name:/Stampa selezionati/})).toBeDisabled();await expect(page.locator('.archive-empty')).toHaveCount(0);await guards(ctx);await page.screenshot({path:out+'/screenshots/'+device+'-accepted-baseline-empty.png',fullPage:true});outcomes.push({name:device+' actual accepted baseline exposes management controls and zero-folder tree',status:'PASS'});await finish(ctx,out,device);}
writeFileSync(out+'/test-results/browser-results.json',JSON.stringify({applicationCommit:'3cd984a5a40f1fe5cdc368dbcc4bb629bd6d1510',outcomes,states,fixtureTransport:'Actual accepted baseline SPA, identical guarded synthetic transport, zero mocked clinical writes'},null,2));writeFileSync(out+'/playwright-report/index.html','<!doctype html><meta charset="utf-8"><h1>423 accepted baseline actual SPA</h1><pre>'+JSON.stringify(outcomes,null,2)+'</pre>');
}catch(e){for(const [i,c]of contexts.entries()){await c.page.screenshot({path:out+'/screenshots/failure-'+i+'.png',fullPage:true}).catch(()=>{});await c.context.tracing.stop({path:out+'/trace/failure-'+i+'.zip'}).catch(()=>{});}writeFileSync(out+'/test-results/failure.json',JSON.stringify({message:e.message,stack:e.stack,outcomes,states},null,2));throw e;}finally{for(const c of contexts)await c.context.close().catch(()=>{});await browser.close();}
