import assert from 'node:assert/strict';
import {readFileSync,readdirSync,statSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {inflateRawSync} from 'node:zlib';
const root=resolve(process.argv[2]),out=resolve(process.argv[3]);assert.ok(process.argv[3]);assert.equal(existsSync(out),false);
const configured=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const secrets=Object.values(configured).filter(v=>typeof v==='string'&&v.length>=12&&(/token|key|secret|password|connection/i.test(Object.keys(configured).find(k=>configured[k]===v)||''))).map(v=>Buffer.from(v));
const files=[],findings=[];let zipMembers=0;
function scan(bytes,path){if(secrets.some(s=>bytes.includes(s)))findings.push({path,kind:'Configured credential detected'});if(/(?:sk-proj-|ghp_|github_pat_)[A-Za-z0-9_-]{20,}/.test(bytes.toString('utf8')))findings.push({path,kind:'Credential-shaped value detected'});}
function zip(bytes,path){let end=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65558);p--)if(bytes.readUInt32LE(p)===0x06054b50){end=p;break;}assert.ok(end>=0,'Valid ZIP');let at=bytes.readUInt32LE(end+16);const total=bytes.readUInt16LE(end+10);for(let i=0;i<total;i++){assert.equal(bytes.readUInt32LE(at),0x02014b50);const method=bytes.readUInt16LE(at+10),size=bytes.readUInt32LE(at+20),n=bytes.readUInt16LE(at+28),e=bytes.readUInt16LE(at+30),c=bytes.readUInt16LE(at+32),offset=bytes.readUInt32LE(at+42),name=bytes.subarray(at+46,at+46+n).toString('utf8');assert.equal(bytes.readUInt32LE(offset),0x04034b50);const start=offset+30+bytes.readUInt16LE(offset+26)+bytes.readUInt16LE(offset+28),compressed=bytes.subarray(start,start+size);assert.ok(method===0||method===8);const raw=method===0?compressed:inflateRawSync(compressed);scan(raw,path+'!'+name);zipMembers++;at+=46+n+e+c;}}
function walk(d){for(const name of readdirSync(d)){if(['node_modules','runtime-cache'].includes(name))continue;const p=resolve(d,name);if(statSync(p).isDirectory())walk(p);else if(p!==out&&!name.endsWith('manifest.json')){const bytes=readFileSync(p),path=relative(root,p).replaceAll('\\','/');scan(bytes,path);if(name.endsWith('.zip'))zip(bytes,path);files.push(path);}}}
walk(root);writeFileSync(out,JSON.stringify({files:files.length,zipMembers,configuredCredentialExactChecks:secrets.length,findings,syntheticOnly:'Browser evidence and fixture data synthetic; original clinical image not downloaded',scope:'Canonical publishable evidence excluding runtime cache/node_modules; ZIP member bytes also inspected'},null,2));assert.deepEqual(findings,[]);console.log('Publication scan PASS '+files.length+' files, '+zipMembers+' ZIP members; zero leaks');
