// Application Tool Layer — shared contract (Phase 1, see .ai-architecture/phase-1-capabilities).
//
// A tool is the invocable form of one catalogued capability. It never owns business logic: its
// handler adapts a uniform input to an EXISTING service symbol and returns that service's result.
// Authorization and audit are hooks (tools/hooks.ts) so the role/policy system of Phase 2 can
// replace the legacy behaviour without touching the tools.

import type { Operator } from '../ai/auth.js';

export type ToolKind = 'read' | 'write' | 'action';

/** Audit classification written to AiAuditEvent.kind. */
export type ToolAuditKind = 'read' | 'create' | 'update' | 'delete' | 'action';

export type ToolSensitivity = 'low' | 'medium' | 'high' | 'critical';

/** Who/what triggered the invocation. Metadata only: it never widens permissions. */
export type ToolOrigin = 'gui' | 'ai' | 'tool' | 'test';

export interface ToolIdentity {
  operatorId: string;
  /** Compat role string (as on req.operator.role). The policy role is re-resolved server-side. */
  role: string;
  name?: string;
  /** Policy role resolved by the auth gate (informative; the authorization hook re-resolves it). */
  appRole?: string;
}

export interface ToolContext {
  identity: ToolIdentity;
  origin: ToolOrigin;
  /** Correlation id; generated by the registry when absent. */
  requestId: string;
}

/** Minimal JSON Schema subset accepted by ajv; kept loose on purpose (the service validates). */
export type JsonSchema = Record<string, unknown>;

export interface ToolDefinition<I = Record<string, unknown>, O = unknown> {
  /** Stable machine-readable id, equal to the catalog `capability_id` (e.g. `consegne.create`). */
  name: string;
  domain: string;
  kind: ToolKind;
  auditKind: ToolAuditKind;
  description: string;
  sensitivity: ToolSensitivity;
  /** JSON Schema of the tool input (object). Path params are top-level, bodies go in `body`. */
  inputSchema: JsonSchema;
  /**
   * When true, `input.patientId` is required and the registry applies the same ownership check as
   * the `requirePatientScope` route middleware (404 `patient_not_found` when missing/out of scope).
   */
  patientScoped?: boolean;
  /**
   * Roles required by the CURRENT route gate (`requireRole(...)`), preserved by the legacy
   * authorization hook. Undefined = any authenticated operator (services still scope data).
   */
  legacyRoles?: readonly string[];
  /** How replays are made safe, when the tool writes. The service owns the mechanism. */
  idempotency?: 'requestId' | 'natural' | 'none';
  /**
   * JSON body limit (bytes) of `POST /tools/:name/invoke` when the standard 512 kB is too small
   * (base64 uploads). That body is parsed only AFTER authentication.
   */
  maxBodyBytes?: number;
  /** Route(s) the GUI uses for the same capability, for parity and documentation. */
  entryPoint: string;
  /** `file#symbol` of the reused business logic. */
  services: readonly string[];
  /** Domain-specific error translation; generic mapping applies when it returns undefined. */
  mapError?: (error: unknown) => ToolErrorShape | undefined;
  handler: (input: I, ctx: ToolContext) => Promise<O>;
}

export type ToolErrorCode =
  | 'invalid_input'
  | 'unauthenticated'
  | 'forbidden'
  | 'not_found'
  | 'conflict'
  | 'gone'
  | 'unprocessable'
  | 'confirmation_required'
  | 'upstream_error'
  | 'unavailable'
  | 'internal';

export interface ToolErrorShape {
  code: ToolErrorCode;
  status: number;
  message: string;
  /** Domain code of the underlying service error (e.g. `patient_not_found`), when present. */
  domainCode?: string;
  details?: Record<string, unknown>;
}

export type ToolResult<O = unknown> =
  | { ok: true; tool: string; requestId: string; data: O }
  | { ok: false; tool: string; requestId: string; error: ToolErrorShape };

/** Public, serialisable description of a tool (what an orchestrator such as Agno receives). */
export interface ToolDescriptor {
  name: string;
  domain: string;
  kind: ToolKind;
  description: string;
  sensitivity: ToolSensitivity;
  patientScoped: boolean;
  idempotency: 'requestId' | 'natural' | 'none';
  inputSchema: JsonSchema;
  /** Policy effect ALLOWED_WITH_CONFIRMATION for the caller: invoke with `confirmed: true`. */
  requiresConfirmation?: boolean;
}

/** The existing services expect the route-level `Operator` shape. */
export function actorOf(ctx: ToolContext): Operator {
  return { id: ctx.identity.operatorId, role: ctx.identity.role, name: ctx.identity.name };
}
