import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyBrowser} from './browser-guards.mjs';
const root='artifacts/task-validation/427-agenda-identity',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,'')),sha=b=>createHash('sha256').update(b).digest('hex'),frozen=read('frozen-source.json'),app=frozen.applicationCommit;
assert.equal(execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),app);const before=read('root-rerun/source-before.json'),after=read('root-rerun/source-after.json');assert.deepEqual(before,after);assert.equal(after.head,app);assert.equal(after.status,'');assert.deepEqual(after.untracked,[]);assert.equal(after.files.length,1540);
const qaBytes=readFileSync(root+'/independent-qa/manifest.json'),qa=JSON.parse(qaBytes);assert.equal(qa.head,app);assert.match(readFileSync(root+'/independent-qa/validation-report.md','utf8'),/^Verdict: READY FOR CODEX QA\r?$/m);for(const f of qa.files)assert.equal(sha(readFileSync(root+'/independent-qa/'+f.path)),f.sha256);
const qb=read('independent-qa/source-before.json'),qaAfter=read('independent-qa/source-after.json');assert.deepEqual(qb,qaAfter);assert.equal(qb.head,app);assert.equal(qb.status,'');assert.deepEqual(qb.untracked,[]);assert.deepEqual(before.files.map(f=>f.path),qb.files.map(f=>f.path));const normalization=[];
for(let i=0;i<before.files.length;i++){const a=before.files[i],b=qb.files[i];if(a.sha256===b.sha256)continue;const own=readFileSync(a.path),other=readFileSync('C:/w-427-qa/'+a.path),decode=new TextDecoder('utf-8',{fatal:true});assert.equal(sha(own),a.sha256);assert.equal(sha(other),b.sha256);assert.equal(decode.decode(own).replaceAll('\r\n','\n'),decode.decode(other).replaceAll('\r\n','\n'));normalization.push({path:a.path,policy:'strict UTF-8 CRLF-to-LF only'});}
const pre=read('root-rerun/pre-run.json');assert.equal(pre.applicationCommit,app);assert.equal(pre.qaManifestSha256,sha(qaBytes));for(const r of pre.records){assert.equal(sha(readFileSync(root+'/root-rerun/recipes/'+r.name)),r.sha256);assert.equal(sha(readFileSync(root+'/independent-qa/recipes/'+r.name)),r.sha256);}let cases=0;
const binding=read('root-rerun/source-git-binding.json');assert.equal(binding.applicationCommit,app);assert.equal(binding.sourceFiles,1540);assert.equal(binding.rootRawSha256,after.sourceSha256);assert.equal(binding.independentRawSha256,qb.sourceSha256);
for(const r of read('root-rerun/browser-plan.json')){const own=read('root-rerun/'+r.folder+'/test-results/browser-results.json'),ind=read('independent-qa/'+r.folder+'/test-results/browser-results.json');verifyBrowser(own,app,r.cases);verifyBrowser(ind,app,r.cases);assert.deepEqual(own.outcomes,ind.outcomes);cases+=r.cases;}
for(const f of ['root-rerun','independent-qa']){const c=read(f+'/commands01/command-results.json');assert.deepEqual(c.newFailures,[]);for(const r of c.records){if(r.name==='full-regression'){assert.equal(r.tests,1271);assert.equal(r.pass,1259);assert.equal(r.fail,12);assert.deepEqual(r.failures,c.baselineFailures);}else{assert.equal(r.exit,0);if(r.name==='focused'){assert.equal(r.tests,10);assert.equal(r.pass,10);}}}assert.deepEqual(read(f+'/security01/comparison.json').newFindings,[]);}
assert.equal(read('root-rerun/server-stop.json').listenerFree,true);assert.equal(read('independent-qa/lane-handoff.json').browserLane,'RELEASED');assert.ok(cases>=8);
const receipt={applicationCommit:app,decision:'AUTHORIZED SCOPED APPLICATION PROMOTION',authority:'Direct human authorization plus NEW independent427QA and root byte-identical source-bound replay',scope:frozen.scope,originalCriteriaPassed:4,independentBrowserCases:cases,rootIndependentRerun:cases,sourceSha256:after.sourceSha256,independentRawSourceSha256:qb.sourceSha256,sourceFiles:after.files.length,qaManifestSha256:sha(qaBytes),immutableQaFiles:qa.files.length,normalization,focusedEach:10,fullEach:{tests:1271,pass:1259,exactBaselineFailures:12,newFailures:0},productionPatientTestMutations:0,physicalHardware:false,remainingGates:['Exact production deployment','Compiled online acceptance','Completed CI baseline delta','Canonical privacy/pinned synthetic proof'],at:new Date().toISOString()};writeFileSync(root+'/release-gate-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({applicationCommit:app,cases,decision:receipt.decision}));
