import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyCanonical} from './canonical-blobs.mjs';
const root='artifacts/task-validation/427-agenda-identity',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,'')),app=read('frozen-source.json').applicationCommit,branch='codex/bug-427-agenda-identity',sha=b=>createHash('sha256').update(b).digest('hex');
const configured=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const git=args=>{const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:100e6,windowsHide:true});assert.equal(r.status,0,'Proof check failed safely');return r.stdout.trim();};
const gh=args=>{const r=spawnSync('gh',args,{encoding:'utf8',maxBuffer:30e6,windowsHide:true,env:{...process.env,GH_TOKEN:configured.GITHUB_TOKEN||configured.GH_TOKEN}});assert.equal(r.status,0,'GitHub operation failed safely');return r.stdout.trim();};
const proof=git(['rev-parse','HEAD']),publication=read('publication-manifest.json'),gate=read('release-gate-receipt.json'),deploy=read('deployment-receipt.json'),online=read('compiled-online/online-receipt.json'),ci=read('ci-comparison.json');
for(const r of [publication,gate,deploy,online,ci])assert.equal(r.applicationCommit,app);assert.equal(online.cases,gate.rootIndependentRerun);assert.equal(gate.originalCriteriaPassed,4);assert.equal(publication.originalIndependentManifestFrozen,true);assert.deepEqual(ci.newFailureNames,[]);assert.equal(ci.frontendSecretScanConclusion,'success');
assert.match(git(['ls-remote','origin','refs/heads/'+branch]),new RegExp('^'+proof+'\\s'));assert.match(git(['ls-remote','origin','refs/heads/main']),new RegExp('^'+app+'\\s'));assert.ok(git(['diff','--name-only',app,proof]).split('\n').every(p=>p.startsWith(root+'/')));verifyCanonical(publication.files,proof);
const raw=`https://raw.githubusercontent.com/l2v-hub/ClinicOS/${proof}/${root}`,tree=`https://github.com/l2v-hub/ClinicOS/tree/${proof}/${root}`,images=read('public-images.json'),verified=[];
for(const {label,path}of images){assert.ok(label&&path.startsWith('compiled-online/'));const r=await fetch(raw+'/'+path);assert.equal(r.status,200);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(sha(bytes),sha(readFileSync(root+'/'+path)));verified.push({path,http:200,sha256:sha(bytes)});}assert.ok(verified.length>=3);
assert.match(readFileSync(root+'/validation-report.md','utf8'),/## Final Decision\s+CLOSED — VERIFIED(?:\s|$)/);const check=spawnSync(process.execPath,['scripts/quality-gate/check-closure.js',root],{encoding:'utf8',windowsHide:true});assert.equal(check.status,0);writeFileSync(root+'/check-closure.log',check.stdout+check.stderr);
const original=read('original-issue.json').issue.body,issue=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/427']));assert.equal(issue.body,original);assert.ok(['open','closed'].includes(issue.state));const actor=JSON.parse(gh(['api','user'])).login;assert.ok(actor);const comments=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/427/comments','--paginate','--slurp'])).flat();
const body=`CLOSED — VERIFIED. Correzione [${app}](https://github.com/l2v-hub/ClinicOS/commit/${app}) online; Vercel${deploy.vercel.id} READY, GitSHA esatto e alias/HTML/JS/CSS HTTP200. Hash statici invariati prima/dopo${online.cases} gruppi sul bundle pubblicato.

Tutti4 criteri originali verificati: identità degli operatori tramite nome, senza pallini semantici o bordi identitari in Giorno/Settimana/Mese e nei filtri; stati leggibili in parole oltre al colore; didascalia esplicita del periodo/conteggi e legenda delle attività anche a vuoto; operatori/stati misti verificati anche in scala di grigi. I testi di stato e i nomi sulle card esistevano già e sono stati certificati runtime, non attribuiti come nuova funzionalità. Le superfici admin ora allineano arancio=Programmato e blu=In corso a badge/legenda, invece dell'inversione preesistente. HMI operatore esclusa dalle modifiche cromatiche, controlli/filtri/tastiera conservati. Nessuna modifica API/auth/schema/backend/deps/config.

[Nuova QA indipendente](${tree}/independent-qa/validation-report.md):${gate.independentBrowserCases} gruppi PASS; [${gate.immutableQaFiles} artefatti immutabili](${tree}/independent-qa/manifest.json), SHA${gate.qaManifestSha256}. Root${gate.rootIndependentRerun} con ricette byte-identiche e${online.cases} sul sito compilato. Tutti i tentativi indipendenti preliminari presenti nel manifest sono conservati senza riscriverli o indebolire le asserzioni; il report distingue gli eventuali problemi della navigazione di fixture dai risultati applicativi. Screenshot finali ispezionati realmente, [review](${tree}/visual-review.md). Limite preesistente conservato: sul telefono la griglia mensile a sette colonne avvolge i testi molto strettamente; non si rivendica un miglioramento della leggibilità generale della vista Mese né l'assenza di scorrimento orizzontale nel Giorno.

Tipi FE/BE/tsc-b/build Reactcompiler/secrets PASS,10/10 test mirati PASS. Regres­sione1271:1259PASS/12 errori nominati identici alla baseline accettata/0 nuovi, NON verde globale. Scanner nativo sui4 file diff0 nuovi finding, non audit CVE globale. ${gate.sourceFiles} input sorgente fisici invariati prima/dopo, rawSHA${gate.sourceSha256}; cross-checkout solo strictUTF8 CRLF-to-LF verificato. Backend47a/Railwayed539 conservato, health200, nessun deploy backend necessario.

[CI${ci.candidateRun}](https://github.com/l2v-hub/ClinicOS/actions/runs/${ci.candidateRun}):${ci.candidateConclusion==='success'?'success':'stesso singolo fallimento backend accettato e stesso stage; downstream saltati, non dichiarati passanti'},0 nuovi, [confronto](${tree}/ci-comparison.json); secret scan${ci.frontendSecretScanRun} success.

Proof${proof}: [report](${tree}/validation-report.md), [gate](${tree}/release-gate-receipt.json), [deployment](${tree}/deployment-receipt.json), [online](${tree}/compiled-online/online-receipt.json), [manifest canonicale/credenziali/ZIP](${tree}/publication-manifest.json), [risultati/trace/video](${tree}/compiled-online), [HTML receipt](${tree}/compiled-online/playwright-report/index.html). HTML è receipt delle asserzioni Playwright-library, non report del runner nativo. Tutte le API auth/cliniche/struttura intercettate PRIMA rete;0 scritture pazienti reali/PHI. Grayscale e viewport sono prove software Chromium, NON certificazione sole diretto/hardware/AT o accettazione clinica dell'audit429. Nessuna persistenza DB rivendicata per questa modifica di presentazione.

${images.map(({label,path})=>`### ${label}\n![427 ${label}](${raw}/${path})`).join('\n\n')}`;
let comment=comments.find(c=>c.user?.login===actor&&c.body===body);if(issue.state==='closed')assert.ok(comment,'Already-closed outcome requires exact authorized proof comment');
writeFileSync(root+'/github-publication-policy.json',JSON.stringify({decision:'AUTHORIZED EXACT PINNED COMMENT AND VERIFIED ISSUE CLOSURE',authority:'Direct human authorization plus independent/root/deployed/CI/publicproof gates',applicationCommit:app,proofCommit:proof,verifiedImages:verified,actor,productionPatientTestMutations:0,at:new Date().toISOString()},null,2));
if(!comment)comment=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/427/comments','--method','POST','-f',`body=${body}`]));assert.equal(comment.body,body);assert.equal(comment.user?.login,actor);if(issue.state==='open')gh(['issue','close','427','--repo','l2v-hub/ClinicOS','--reason','completed']);
const fresh=JSON.parse(gh(['api','repos/l2v-hub/ClinicOS/issues/427']));assert.equal(fresh.state,'closed');assert.equal(fresh.body,original);const receipt={applicationCommit:app,proofCommit:proof,proofBranch:branch,githubProof:comment.html_url,state:fresh.state,canonicalHashesVerified:publication.files.length,images:verified,secretChecks:publication.secretChecks,zipEntriesChecked:publication.zipEntriesChecked,decision:'CLOSED — VERIFIED',productionPatientTestMutations:0,at:new Date().toISOString()};writeFileSync(root+'/github-publication-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
