import {browser,setup,openAgenda,finish,expect,out,report,identity} from './fixture.mjs';
const results=[];
const primary=p=>p.getByRole('button',{name:'Nuovo appuntamento',exact:true});
const dialog=p=>p.getByRole('dialog',{name:'Nuovo Appuntamento'});
async function run(name,options,fn){const ctx=await setup(options);try{await openAgenda(ctx);await fn(ctx);await finish(ctx,name);results.push({name,status:'PASS'});console.log(`PASS ${name}`);}catch(e){try{await finish(ctx,`${name}-failed`);}catch{}results.push({name,status:'FAIL',error:e.message});console.log(`FAIL ${name}`);throw e;}}
try {
 await run('after-hours', {time:'2026-10-09T23:09:00+02:00'},async({page})=>{
  await expect(primary(page)).toBeDisabled();await expect(page.locator('#operator-appointment-creation-help')).toHaveText('Nessun appuntamento in questa giornata. Nessuna fascia libera nelle ore rimanenti di oggi. Scegli una data futura.');
  await expect(page.getByRole('button',{name:/Crea appuntamento alle/})).toHaveCount(0);await page.locator('.agt-slot').first().click();await expect(dialog(page)).toHaveCount(0);
  await page.screenshot({path:`${out}/screenshots/after-hours.png`});await page.getByRole('button',{name:'Intervallo successivo'}).click();
  await expect(primary(page)).toBeEnabled();await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('input[type=date]')).toHaveValue('2026-10-10');await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:00');
 });
 await run('empty-primary-and-slots',{},async({page})=>{
  await expect(primary(page)).toBeEnabled();await expect(page.locator('#operator-appointment-creation-help')).toContainText('Nessun appuntamento in questa giornata. Usa Nuovo appuntamento');await primary(page).click();await expect(dialog(page)).toBeVisible();
  await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:00');await expect(dialog(page).getByRole('combobox',{name:/Paziente/})).toHaveValue('');await expect(dialog(page).getByText('Seleziona un paziente per salvare l’appuntamento. Cerca per nome, cognome o codice fiscale.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeDisabled();
  await page.screenshot({path:`${out}/screenshots/no-patient-dialog.png`});await page.getByRole('button',{name:'Annulla',exact:true}).click();
  const slot=page.getByRole('button',{name:'Crea appuntamento alle 09:00',exact:true});await slot.focus();await page.keyboard.press('Enter');await expect(dialog(page).locator('input[type=time]')).toHaveValue('09:00');await page.getByRole('button',{name:'Annulla',exact:true}).click();await slot.focus();await page.keyboard.press('Space');await expect(dialog(page)).toBeVisible();await page.getByRole('button',{name:'Annulla',exact:true}).click();
  await page.screenshot({path:`${out}/screenshots/empty-day.png`});
 });
 await run('denied-role', {allowed:false},async({page})=>{await expect(primary(page)).toBeDisabled();await expect(page.locator('#operator-appointment-creation-help')).toContainText('Il tuo ruolo non può creare appuntamenti.');await expect(page.getByRole('button',{name:/Crea appuntamento alle/})).toHaveCount(0);await page.locator('.agt-slot').first().click();await expect(dialog(page)).toHaveCount(0);await page.getByRole('button',{name:'Settimana',exact:true}).click();await expect(page.getByRole('button',{name:/Crea appuntamento il/})).toHaveCount(0);await page.locator('.agt-week-cell').first().click();await expect(dialog(page)).toHaveCount(0);});
 await run('populated-filtered-occupancy', {appointments:[{id:'QA-APT-419',operatorId:identity.id,patientId:null,patientName:'Persona Sintetica',data:'2026-10-09',ora:'08:00',durata:30,tipologia:'visita',stato:'programmato',note:''}]},async({page})=>{await expect(page.locator('.agt-apt-card')).toHaveCount(1);await expect(page.locator('#operator-appointment-creation-help')).not.toContainText('Nessun appuntamento');await primary(page).click();await expect(dialog(page).locator('input[type=time]')).toHaveValue('08:30');await page.getByRole('button',{name:'Annulla',exact:true}).click();await page.getByRole('button',{name:/^Completato/}).click();await expect(page.locator('.agt-apt-card')).toHaveCount(0);await expect(page.getByRole('button',{name:'Crea appuntamento alle 08:00',exact:true})).toHaveCount(0);await expect(page.locator('#operator-appointment-creation-help')).not.toContainText('Nessun appuntamento');});
 await run('past-and-weekly',{},async({page})=>{await page.getByRole('button',{name:'Intervallo precedente'}).click();await expect(primary(page)).toBeDisabled();await expect(page.locator('#operator-appointment-creation-help')).toContainText('Giorno passato');await expect(page.getByRole('button',{name:/Crea appuntamento alle/})).toHaveCount(0);await page.getByRole('button',{name:'Settimana',exact:true}).click();await expect(page.getByRole('button',{name:'Crea appuntamento il 2026-10-08 alle 08:00',exact:true})).toHaveCount(0);const slot=page.getByRole('button',{name:'Crea appuntamento il 2026-10-10 alle 10:00',exact:true});await slot.focus();await page.keyboard.press('Enter');await expect(dialog(page).locator('input[type=date]')).toHaveValue('2026-10-10');await expect(dialog(page).locator('input[type=time]')).toHaveValue('10:00');});
 await run('clock-boundary',{time:'2026-10-09T18:30:00+02:00'},async({page})=>{await expect(primary(page)).toBeEnabled();await expect(page.getByRole('button',{name:'Crea appuntamento alle 18:30',exact:true})).toHaveCount(1);await page.clock.fastForward(61_000);await expect(primary(page)).toBeDisabled();await expect(page.getByRole('button',{name:/Crea appuntamento alle/})).toHaveCount(0);await expect(page.locator('#operator-appointment-creation-help')).toContainText('Nessuna fascia libera nelle ore rimanenti');});
 await run('full-day',{appointments:Array.from({length:22},(_,i)=>({id:`QA-FULL-${i}`,operatorId:identity.id,patientName:'Persona Sintetica',data:'2026-10-09',ora:`${String(8+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`,durata:30,tipologia:'visita',stato:'programmato'}))},async({page})=>{await expect(page.locator('.agt-apt-card')).toHaveCount(22);await expect(primary(page)).toBeDisabled();await expect(page.locator('#operator-appointment-creation-help')).toContainText('Nessuna fascia libera');await expect(page.getByRole('button',{name:/Crea appuntamento alle/})).toHaveCount(0);});
 await run('patient-selection-enables-save',{},async({page})=>{await primary(page).click();const patient=dialog(page).getByRole('combobox',{name:/Paziente/});await patient.fill('Sintetica');await page.getByRole('option',{name:/Persona/}).click();await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeEnabled();await expect(patient).toHaveValue(/Sintetica/);});
 await run('mobile-empty',{mobile:true},async({page})=>{await expect(primary(page)).toBeEnabled();await expect(page.locator('#operator-appointment-creation-help')).toBeVisible();const b=await page.locator('#operator-appointment-creation-help').boundingBox();expect(b.x+b.width).toBeLessThanOrEqual(391);await primary(page).click();await expect(dialog(page)).toBeVisible();await expect(page.getByRole('button',{name:'Salva appuntamento',exact:true})).toBeDisabled();await page.screenshot({path:`${out}/screenshots/mobile-no-patient.png`});});
 report(results);
}finally{report(results);await browser.close();}
