import {readFileSync,writeFileSync,readdirSync,statSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
const out='C:/w-418-qa-final/artifacts/task-validation/418-reading-recency/independent-qa418-immutable';
const sha=b=>createHash('sha256').update(b).digest('hex');
const walk=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(resolve(dir,e.name)):[resolve(dir,e.name)]);
const results=JSON.parse(readFileSync(out+'/fresh21b/results.json'));
const pre=JSON.parse(readFileSync(out+'/pre-run21b/receipt.json'));
if(results.stats.expected!==21||results.stats.unexpected!==0||results.stats.skipped!==0||results.stats.flaky!==0||pre.files.some(f=>sha(readFileSync(out+'/'+f.path))!==f.sha256))throw Error('Fresh run or recipe integrity failure');
if(!JSON.parse(readFileSync(out+'/server-stopped.json')).portFreeAfter)throw Error('Server not stopped');
const files=walk(out).filter(p=>!['SHA256-MANIFEST.json','seal-receipt.json'].includes(relative(out,p))).sort().map(p=>({path:relative(out,p).replaceAll('\\','/'),bytes:statSync(p).size,sha256:sha(readFileSync(p))}));
writeFileSync(out+'/SHA256-MANIFEST.json',JSON.stringify({application:'d028e1ee4c5c44d96b5005362b28f54e5c05fee1',allFilesExceptRecursiveSealMetadata:true,files},null,2));
const manifestSha256=sha(readFileSync(out+'/SHA256-MANIFEST.json'));
writeFileSync(out+'/seal-receipt.json',JSON.stringify({verdict:'READY FOR CODEX QA',application:'d028e1ee4c5c44d96b5005362b28f54e5c05fee1',files:files.length,manifestSha256,sealedAt:new Date().toISOString(),fresh21:{expected:21,unexpected:0,skipped:0,flaky:0},allFreshGateOriginalsPreserved:true,priorGateRetentionIncidentNotReinterpreted:true,serverStopped:true,scope:'All files in this new immutable gate sealed except recursive manifest/seal metadata; separately authorized prior sealed evidence reused by hash, no release authority.'},null,2));
console.log(`Sealed${files.length} files; manifest${manifestSha256}`);
