import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const {chromium,expect:baseExpect}=createRequire('C:/w-insulin-qa/package.json')('playwright/test'),expect=baseExpect.configure({timeout:60000}),out=resolve(process.argv[2]),before=process.env.BEFORE==='1';
assert.ok(process.argv[2]);for(const p of ['screenshots','video','trace','test-results'])mkdirSync(out+'/'+p,{recursive:true});
const browser=await chromium.launch({headless:true}),outcomes=[],states=[],contexts=[];
const identities=[{id:'QA-SUPERVISOR-426',name:'Supervisore Sintetico',roleLabel:'Supervisore',appRole:'administrator',uiShell:'admin'}];
const room=(numero,index)=>({id:'QA-ROOM-426-'+index,numero,tipo:'doppia',piano:'1',reparto:'Reparto Sintetico',stato:'attiva',note:'',beds:['A','B'].map(label=>({id:`QA-BED-426-${index}-${label}`,roomId:'QA-ROOM-426-'+index,label,stato:'libero',note:'',assignments:[]}))});
async function setup(width,height){
 const context=await browser.newContext({viewport:{width,height},recordVideo:{dir:out+'/video'}});contexts.push(context);await context.tracing.start({screenshots:true,snapshots:true,sources:true});
 const state={rooms:[room('101',1),room('102',2)],requests:[],unexpected:[],external:[],clinicalWrites:[],allowedMockMutations:[],errors:[],pageErrors:[],httpErrors:[],allowMutation:false,delay:false};states.push(state);
 await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname;
  if(u.hostname==='fonts.googleapis.com')return route.fulfill({status:200,contentType:'text/css',body:''});
  const api=u.hostname==='localhost'&&u.port==='3001'||['clinicos-backend-demo.up.railway.app','clinicos-backend-production-df88.up.railway.app'].includes(u.hostname);
  if(!api){const app=new URL(process.env.APP_URL||'http://127.0.0.1:7517'),local=['localhost','127.0.0.1'].includes(app.hostname);if(req.method()==='GET'&&u.origin===app.origin&&(local||path==='/'||path.startsWith('/assets/')||path==='/favicon.ico'))return route.continue();state.external.push(u.origin);return route.abort();}
  state.requests.push({method:req.method(),path});const json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
  if(path==='/auth/status')return json({mode:'disabled',temporaryDemo:false,simulator:true});
  if(path==='/auth/simulator/identities')return json({identities});
  if(path==='/auth/simulator/session'&&req.method()==='POST')return json({token:'synthetic-426-not-a-secret'});
  if(path==='/auth/simulator/logout'&&req.method()==='POST')return json({ok:true});
  if(req.method()!=='GET'){
   if(!state.allowMutation||!/^\/admin\/(rooms|beds)\/QA-(ROOM|BED)-426-/.test(path)){state.clinicalWrites.push({method:req.method(),path});return json({error:'Real or unauthorized mutation forbidden'},500);}
   state.allowedMockMutations.push({method:req.method(),path,body:req.postData()});if(state.delay){state.held=true;await new Promise(r=>state.release=r);state.held=false;}
   if(state.fail){state.fail=false;return json({error:'Errore sintetico salvataggio'},409);}
   return json({ok:true});
  }
  if(path==='/auth/me'){const capabilities=Object.fromEntries(['patients.list_page','patients.get','patients.clinical_summary','patients.clinical_overview','appointments.list','consegne.list','notes.list','operators.directory','administration.list_slots','therapy.list','therapy.list_page','clinical_record.get','diary.list','admin.rooms'].map(k=>[k,{allowed:true,effect:'ALLOWED'}]));capabilities['intake.create_draft']={allowed:false,effect:'DENIED'};return json({...identities[0],role:'admin',authMode:'disabled',temporaryDemo:false,capabilities});}
  if(path==='/admin/rooms')return json(state.rooms);
  if(path==='/admin/rooms/occupancy')return json({totalRooms:2,totalBeds:4,occupiedBeds:0,freeBeds:4,maintenanceBeds:0,occupancyPct:0});
  if(path==='/patients/page'||path==='/patients/parameters/page')return json({items:[],hasMore:false,nextCursor:null});
  if(path==='/patients/clinical-summary')return json([]);
  if(path==='/patients/clinical-summary/overview')return json({totalPatients:0,critici:0,rischiAlti:0,ricoverati:0,dimessi:0,allergieGravi:0,terapieTotali:0,terapieCompletate:0});
  if(path==='/patients/settings')return json({deleteEnabled:false});
  if(path==='/patients/diary-unread-count')return json({unreadCount:0});
  if(path==='/me/roster-order')return json({context:null,default:null,override:null,effective:{criterion:'name',direction:'asc'},source:'system',revision:null,canEdit:false,canEditDefault:false,temporary:false,reason:null});
  if(['/therapy-slots','/appointments'].includes(path))return json([]);
  if(path==='/consegne/overview')return json({scope:'admin',summary:{total:0,urgentActive:0,urgentTaken:0},recentPreview:[],urgentPreview:[],byOperator:{}});
  if(path==='/consegne')return json({items:[],hasMore:false,nextCursor:null,summary:{total:0,urgentActive:0,urgentTaken:0}});
  if(path==='/notes')return json({items:[],pageInfo:{hasMore:false,nextCursor:null},summary:{unread:0}});
  if(['/operators/directory/page','/operators/page'].includes(path))return json({items:[],pageInfo:{hasMore:false,nextCursor:null},summary:{total:0,active:0,matching:0,appointmentsToday:0}});
  state.unexpected.push(req.method()+' '+path);return json({error:'Unexpected guarded API'},500);
 });
 const page=await context.newPage();page.setDefaultTimeout(60000);page.on('console',m=>{if(m.type()==='error')state.errors.push(m.text());});page.on('pageerror',e=>state.pageErrors.push(e.message));page.on('response',r=>{if(r.status()>=400)state.httpErrors.push({status:r.status(),path:new URL(r.url()).pathname});});
 await page.goto((process.env.APP_URL||'http://127.0.0.1:7517')+'/#/posti-letto');await page.getByRole('button',{name:/Supervisore Sintetico/}).click();await page.getByRole('button',{name:/Gestione posti letto/}).click();await expect(page.locator('.rooms-grid .room-card')).toHaveCount(2);return {context,page,state};
}
async function check(name,fn){await fn();outcomes.push({name,status:'PASS'});console.log('PASS '+name);}
async function finish(ctx,name){for(const k of ['clinicalWrites','unexpected','external','pageErrors'])expect(ctx.state[k],k).toEqual([]);expect(ctx.state.httpErrors).toEqual([]);expect(ctx.state.errors).toEqual([]);await ctx.context.tracing.stop({path:out+'/trace/'+name+'.zip'});const video=ctx.page.video();await ctx.context.close();await video.saveAs(out+'/video/'+name+'.webm');await video.delete();}
try{
 const ctx=await setup(1280,720),{page,state}=ctx;
 if(before){await check('Baseline actual SPA repeats ambiguous2roomedit2delete4bed commands',async()=>{await expect(page.getByRole('button',{name:'Modifica camera',exact:true})).toHaveCount(2);await expect(page.getByRole('button',{name:'Elimina camera',exact:true})).toHaveCount(2);await expect(page.getByRole('button',{name:'Modifica letto',exact:true})).toHaveCount(4);await page.screenshot({path:out+'/screenshots/baseline-ambiguous-actions.png'});});await finish(ctx,'baseline');}
 else{
  await check('426 unique exact actionnames/title across2rooms and4beds',async()=>{for(const n of ['101','102']){for(const action of ['Modifica camera','Elimina camera']){const label=action+' '+n,button=page.getByRole('button',{name:label,exact:true});await expect(button).toHaveCount(1);await expect(button).toHaveAttribute('title',label);}for(const bed of ['A','B']){const label=`Modifica letto ${JSON.stringify(bed)} della camera ${JSON.stringify(n)}`,button=page.getByRole('button',{name:label,exact:true});await expect(button).toHaveCount(1);await expect(button).toHaveAttribute('title',label);}}await page.screenshot({path:out+'/screenshots/resource-actions.png'});});
  await check('426 room editor retains original target while renaming, no write oncancel',async()=>{await page.getByRole('button',{name:'Modifica camera 101',exact:true}).click();await expect(page.getByRole('heading',{name:'Modifica camera 101',exact:true})).toBeVisible();await page.getByLabel('N° camera *',{exact:true}).fill('103');await expect(page.getByRole('heading',{name:'Modifica camera 101',exact:true})).toBeVisible();await page.screenshot({path:out+'/screenshots/room-original-target.png'});await page.getByRole('button',{name:'Annulla',exact:true}).click();expect(state.allowedMockMutations).toEqual([]);});
  await check('426 bed heading/tooltip exact target, keyboard trap Escape and focusreturn',async()=>{const label='Modifica letto "B" della camera "102"',opener=page.getByRole('button',{name:label,exact:true});await opener.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:label,exact:true});await expect(dialog).toBeVisible();await expect(dialog.getByLabel('Stato',{exact:true})).toHaveValue('libero');await expect(dialog.getByLabel('Note',{exact:true})).toHaveValue('');await dialog.getByRole('button',{name:'Salva',exact:true}).focus();await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'Chiudi '+label,exact:true})).toBeFocused();await page.screenshot({path:out+'/screenshots/bed-exact-target.png'});await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(opener).toBeFocused();expect(state.allowedMockMutations).toEqual([]);});
  await check('426 trash vsedit distinct icons/style/gap, confirmation/cancel neverdelete',async()=>{const edit=page.getByRole('button',{name:'Modifica camera 101',exact:true}),remove=page.getByRole('button',{name:'Elimina camera 101',exact:true});expect(await edit.locator('svg').innerHTML()).not.toBe(await remove.locator('svg').innerHTML());await expect(remove).toHaveClass(/icon-btn--danger/);const geometry=await page.locator('.room-card__actions').first().evaluate(node=>{const [a,b]=node.querySelectorAll('button');return {gap:b.getBoundingClientRect().left-a.getBoundingClientRect().right,colorA:getComputedStyle(a).color,colorB:getComputedStyle(b).color};});expect(geometry.gap).toBeGreaterThanOrEqual(12);expect(geometry.colorA).not.toBe(geometry.colorB);await remove.click();const dialog=page.getByRole('alertdialog',{name:'Eliminare la camera 101?',exact:true});await expect(dialog).toBeVisible();await expect(dialog).toContainText('La camera 101 verrà eliminata');await expect(dialog.getByRole('button',{name:'Elimina camera 101',exact:true})).toBeVisible();await page.screenshot({path:out+'/screenshots/delete-confirm-exact-target.png'});await dialog.getByRole('button',{name:'Annulla',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(remove).toBeFocused();expect(state.allowedMockMutations).toEqual([]);});
  await check('426 reload restores labels without any persisted write',async()=>{await page.reload();await page.getByRole('button',{name:/Supervisore Sintetico/}).click();await page.getByRole('button',{name:/Gestione posti letto/}).click();await expect(page.getByRole('button',{name:'Modifica camera 102',exact:true})).toBeVisible();expect(state.allowedMockMutations).toEqual([]);});
  await finish(ctx,'desktop');const mobile=await setup(390,844);
  await check('426 mobile action/context remains accessible without horizontal overflow',async()=>{await expect(mobile.page.getByRole('button',{name:'Modifica camera 101',exact:true})).toBeVisible();expect(await mobile.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const label='Modifica letto "A" della camera "101"';await mobile.page.getByRole('button',{name:label,exact:true}).click();await expect(mobile.page.getByRole('dialog',{name:label,exact:true})).toBeVisible();await mobile.page.screenshot({path:out+'/screenshots/mobile-bed-context.png'});await mobile.page.keyboard.press('Escape');expect(mobile.state.allowedMockMutations).toEqual([]);});await finish(mobile,'mobile');
 }
 writeFileSync(out+'/test-results/browser-results.json',JSON.stringify({outcomes,states,before,applicationCommit:process.env.SOURCE_COMMIT,fixtureTransport:'Guarded before-wire synthetic facility/auth/clinical endpoints; local actualViteReactcompiler or actualdeployedcompiledSPA. Reload is mockonly, no realpatient/roomwrites.'},null,2));
}catch(e){for(const [i,c]of contexts.entries()){const p=c.pages()[0];if(p)await p.screenshot({path:out+'/screenshots/failure-'+i+'.png'}).catch(()=>{});await c.tracing.stop({path:out+'/trace/failure-'+i+'.zip'}).catch(()=>{});}writeFileSync(out+'/test-results/failure.json',JSON.stringify({message:e.message,stack:e.stack,outcomes,states},null,2));throw e;}finally{for(const c of contexts)await c.close().catch(()=>{});await browser.close();}
