import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyBrowser} from './browser-guards.mjs';
const root='artifacts/task-validation/423-document-empty-state',read=p=>JSON.parse(readFileSync(root+'/'+p,'utf8').replace(/^\uFEFF/,'')),sha=b=>createHash('sha256').update(b).digest('hex'),frozen=read('frozen-source.json'),app=frozen.applicationCommit;
assert.equal(execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),app);
const before=read('root-rerun/source-before.json'),after=read('root-rerun/source-after.json');assert.deepEqual(before,after);assert.equal(after.head,app);assert.equal(after.status,'');assert.deepEqual(after.untracked,[]);assert.equal(after.files.length,1551);
const qaBytes=readFileSync(root+'/independent-qa/manifest.json'),qa=JSON.parse(qaBytes);assert.equal(qa.head,app);assert.match(readFileSync(root+'/independent-qa/validation-report.md','utf8'),/^Verdict: READY FOR CODEX QA\r?$/m);for(const f of qa.files)assert.equal(sha(readFileSync(root+'/independent-qa/'+f.path)),f.sha256);
assert.equal(sha(qaBytes),'fd55dcaa1a8170a38a7d0b136683fc4ab1fe7f44ed1ca8d6bea3443e9df1c7b4');assert.equal(qa.files.length,519);
const adoption=read('qa-adoption-policy.json');assert.equal(adoption.applicationCommit,app);assert.equal(adoption.qaManifestSha256,sha(qaBytes));assert.equal(adoption.files,519);
const input=read('independent-qa/input-receipt.json');assert.equal(input.candidate,app);assert.equal(input.baseline,frozen.base);assert.equal(input.contractNativeValid,true);assert.equal(input.contractSHA256,sha(readFileSync(root+'/independent-qa/task-contract.md')));assert.equal(input.contractSHA256,sha(readFileSync(root+'/task-contract.md')));assert.match(readFileSync(root+'/independent-qa/contract-validation.log','utf8'),/^CONTRACT VALIDO:/m);
const fresh=read('independent-qa/fresh-issue.json');assert.equal(fresh.issue.number,423);assert.equal(fresh.issue.body,read('original-issue.json').issue.body);assert.deepEqual(fresh.comments,[]);assert.deepEqual(input.originalCriteria,fresh.issue.body.split('\n').filter(l=>l.startsWith('- [ ] ')).map(l=>l.slice(6)));assert.equal(input.originalCriteria.length,4);
const diff=read('independent-qa/diff-review.json');assert.equal(diff.head,app);assert.equal(diff.baseline,frozen.base);assert.equal(diff.scopeExact,true);assert.equal(diff.diffCheck,true);assert.deepEqual(diff.findings,[]);assert.deepEqual(diff.scope.slice().sort(),frozen.scope.slice().sort());assert.ok(diff.files.every(f=>f.lines<500));
const qb=read('independent-qa/source-before.json'),qaAfter=read('independent-qa/source-after.json');assert.deepEqual(qb,qaAfter);assert.equal(qb.head,app);assert.equal(qb.status,'');assert.deepEqual(qb.untracked,[]);assert.deepEqual(before.files.map(f=>f.path),qb.files.map(f=>f.path));
const binding=read('root-rerun/source-git-binding.json');assert.equal(binding.applicationCommit,app);assert.equal(binding.sourceFiles,1551);assert.equal(binding.rootRawSha256,after.sourceSha256);assert.equal(binding.independentRawSha256,qb.sourceSha256);
const pre=read('root-rerun/pre-run.json');assert.equal(pre.applicationCommit,app);assert.equal(pre.qaManifestSha256,sha(qaBytes));for(const r of pre.records){assert.equal(sha(readFileSync(root+'/root-rerun/recipes/'+r.name)),r.sha256);assert.equal(sha(readFileSync(root+'/independent-qa/recipes/'+r.name)),r.sha256);}
assert.deepEqual(pre.records,qa.files.filter(f=>f.path.startsWith('recipes/')).map(f=>({name:f.path.slice(8),sha256:f.sha256})));
const plan=read('root-rerun/browser-plan.json');assert.deepEqual(plan,read('independent-qa/browser-plan.json'));assert.deepEqual(plan,[{recipe:'recipes/browser.mjs',folder:'browser03/run',cases:46}]);
const baselineProof='057dc6ca6374203d4a1c86d1e5c4b14b73810d48',baselineLog=execFileSync('git',['show',baselineProof+':artifacts/task-validation/425-chart-scroll/root-rerun2/commands01/full-regression.log'],{encoding:'utf8',maxBuffer:40e6});
const baselineFailures=[...new Set([...baselineLog.matchAll(/^✖ (.*?) \([\d.]+ms\)/gm)].map(m=>m[1]))].sort();assert.equal(baselineFailures.length,12);
const commandNames=['frontend-types','backend-types','frontend-tsc-build','vite-build','focused','security-scan','full-regression'];
for(const folder of ['root-rerun','independent-qa']){const c=read(folder+'/commands01/command-results.json');assert.deepEqual(c.records.map(r=>r.name),commandNames);assert.equal(c.baselineProof,baselineProof);assert.deepEqual(c.baselineFailures,baselineFailures);}
let cases=0;for(const r of read('root-rerun/browser-plan.json')){const own=read('root-rerun/'+r.folder+'/test-results/browser-results.json'),ind=read('independent-qa/'+r.folder+'/test-results/browser-results.json');verifyBrowser(own,app,r.cases);verifyBrowser(ind,app,r.cases);assert.deepEqual(own.outcomes,ind.outcomes);cases+=r.cases;}assert.equal(cases,46);
for(const f of ['root-rerun','independent-qa']){const c=read(f+'/commands01/command-results.json');assert.deepEqual(c.newFailures,[]);for(const r of c.records){if(r.name==='full-regression'){assert.equal(r.tests,1297);assert.equal(r.pass,1285);assert.equal(r.fail,12);assert.deepEqual(r.failures,c.baselineFailures);}else{assert.equal(r.exit,0);if(r.name==='focused'){assert.equal(r.tests,44);assert.equal(r.pass,44);}}}const security=read(f+'/security01/comparison.json');assert.deepEqual(security.newFindings,[]);assert.equal(security.changed.length,7);}
const baseline=read('independent-qa/baseline02/run/test-results/browser-results.json');assert.equal(baseline.applicationCommit,'3cd984a5a40f1fe5cdc368dbcc4bb629bd6d1510');assert.equal(baseline.outcomes.length,2);assert.ok(baseline.outcomes.every(o=>o.status==='PASS'));for(const s of baseline.states){for(const key of ['unexpected','external','clinicalWrites','allowedMockMutations','errors','pageErrors','httpErrors'])assert.deepEqual(s[key],[]);}
assert.equal(read('root-rerun/server-stop.json').listenerFree,true);assert.match(readFileSync(root+'/independent-qa/lane-handoff.md','utf8'),/^# RELEASED\r?$/m);
const receipt={applicationCommit:app,decision:'AUTHORIZED SCOPED APPLICATION PROMOTION',authority:'Direct human authorization plus NEW independent423QA2 and root byte-identical source-bound replay',scope:frozen.scope,originalCriteriaPassed:4,independentBrowserCases:cases,rootIndependentRerun:cases,sourceSha256:after.sourceSha256,independentRawSourceSha256:qb.sourceSha256,sourceFiles:1551,qaManifestSha256:sha(qaBytes),immutableQaFiles:qa.files.length,focusedEach:44,fullEach:{tests:1297,pass:1285,exactBaselineFailures:12,newFailures:0},productionPatientTestMutations:0,physicalHardware:false,backendChange:'None; frontend presentation only, no auth/schema/backend changes',persistenceProof:'Synthetic intercepted reload only; real DB not required by frontend scope',remainingGates:['Exact production deployment','Compiled online acceptance','Completed CI baseline delta','Canonical privacy/pinned synthetic proof'],at:new Date().toISOString()};writeFileSync(root+'/release-gate-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({applicationCommit:app,cases,decision:receipt.decision}));
