import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const root='artifacts/task-validation/423-document-empty-state',application=JSON.parse(readFileSync(root+'/frozen-source.json')).applicationCommit,baselineRun=37987185985,env=JSON.parse(readFileSync('C:/Workspace/ClinicOSHouse/.claude/settings.local.json','utf8')).env;
const gh=args=>{const r=spawnSync('gh',args[0]==='api'?args:[...args,'--repo','l2v-hub/ClinicOS'],{encoding:'utf8',maxBuffer:30e6,env:{...process.env,GH_TOKEN:env.GITHUB_TOKEN||env.GH_TOKEN}});assert.equal(r.status,0,'GitHub read failed safely');return r.stdout;};
const runs=JSON.parse(gh(['run','list','--commit',application,'--json','databaseId,name,status,conclusion'])),candidateRun=runs.find(r=>r.name==='AI Import E2E Gate')?.databaseId,secretRun=runs.find(r=>r.name==='Frontend Secret Scan')?.databaseId;if(!candidateRun||!secretRun){console.log('CI not yet present');process.exit(2);}
const metadata=JSON.parse(gh(['api',`repos/l2v-hub/ClinicOS/actions/runs/${candidateRun}`]));assert.equal(metadata.head_sha,application);const candidateAttempt=metadata.run_attempt;
if(existsSync(root+'/ci-rerun-receipt.json')){const rerun=JSON.parse(readFileSync(root+'/ci-rerun-receipt.json'));assert.equal(rerun.applicationCommit,application);assert.equal(rerun.run,candidateRun);assert.equal(candidateAttempt,2,'Only one bounded diagnostic rerun permitted');const initial=JSON.parse(readFileSync(root+'/ci-unexpected-failures.json'));assert.equal(initial.receipts[0].headSha,application);assert.equal(initial.receipts[0].failureBlocks.length,7);}else assert.equal(candidateAttempt,1);
const candidate=JSON.parse(gh(['run','view',String(candidateRun),'--attempt',String(candidateAttempt),'--json','attempt,headSha,status,conclusion,jobs'])),secret=JSON.parse(gh(['run','view',String(secretRun),'--attempt','1','--json','attempt,headSha,status,conclusion']));assert.equal(candidate.attempt,candidateAttempt);assert.equal(candidate.headSha,application);assert.equal(secret.attempt,1);assert.equal(secret.headSha,application);
if(candidate.status!=='completed'||secret.status!=='completed'){const progress={applicationCommit:application,candidateAttempt,checkedAt:new Date().toISOString(),candidateRun,candidateStatus:candidate.status,secretRun,secretStatus:secret.status,secretConclusion:secret.conclusion,jobs:candidate.jobs.map(j=>({name:j.name,status:j.status,conclusion:j.conclusion,activeSteps:j.steps.filter(s=>s.status!=='completed').map(s=>({name:s.name,status:s.status}))})),decision:'PENDING, not final CI receipt'};writeFileSync(root+'/ci-progress.json',JSON.stringify(progress,null,2));console.log(JSON.stringify(progress));process.exit(2);}
const failedStageNames=candidate.jobs.flatMap(j=>j.steps.filter(s=>s.conclusion==='failure').map(s=>`${j.name}: ${s.name}`)).sort();
if(secret.conclusion==='success'&&candidate.conclusion==='failure'&&JSON.stringify(failedStageNames)===JSON.stringify(['gate: Initialize containers'])){
 let log=gh(['run','view',String(candidateRun),'--attempt',String(candidateAttempt),'--log-failed']);for(const [key,value]of Object.entries(env))if(/TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL|CONNECTION_STRING|DATABASE_URL/.test(key)&&typeof value==='string'&&value.length>=8)log=log.replaceAll(value,'[REDACTED CONFIGURED CREDENTIAL]');assert.match(log,/Docker pull failed/);writeFileSync(root+'/ci-infrastructure.log',log);
 const receipt={applicationCommit:application,candidateAttempt,candidateRun,frontendSecretScanRun:secretRun,frontendSecretScanConclusion:secret.conclusion,decision:'BLOCKED EXTERNAL CI INFRASTRUCTURE; ISSUE MUST REMAIN OPEN',failedStage:'Initialize containers',failedSteps:failedStageNames,reason:'DockerHub pull unavailable before application checkout; same external condition already repeated three times for424, no unchanged retries',applicationTestVerdict:'Unavailable, not accepted baseline backend failure and not globally green',retryPolicy:'No workflow/env/credentials expansion or unchanged retry; resume when registry availability changes',at:new Date().toISOString()};writeFileSync(root+'/ci-blocker-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));process.exit(3);
}
if(secret.conclusion==='success'&&candidate.conclusion==='success'){
 assert.deepEqual(failedStageNames,[]);const receipt={applicationCommit:application,candidateAttempt,candidateRun,frontendSecretScanRun:secretRun,frontendSecretScanConclusion:secret.conclusion,decision:'COMPLETED CI WORKFLOWS VERIFIED',candidateConclusion:'success',newFailureNames:[],failedSteps:[],baselineRun,at:new Date().toISOString()};writeFileSync(root+'/ci-comparison.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));process.exit(0);
}
assert.equal(secret.conclusion,'success');const failureNames=(run,attempt)=>[...new Set([...gh(['run','view',String(run),'--attempt',String(attempt),'--log-failed']).matchAll(/not ok \d+ - ([^\r\n]+)/g)].map(m=>m[1].trim()))].sort(),baselineNames=failureNames(baselineRun,1),candidateNames=failureNames(candidateRun,candidateAttempt);assert.deepEqual(candidateNames,baselineNames);assert.deepEqual(baselineNames,['therapy reads and writes apply patient scope before loading clinical data']);assert.equal(candidate.conclusion,'failure');
const baseline=JSON.parse(gh(['run','view',String(baselineRun),'--attempt','1','--json','attempt,headSha,status,conclusion,jobs']));assert.equal(baseline.attempt,1);assert.equal(baseline.headSha,'b5f471cd2cd56839e7ebbd0d3daf0bbf04791468');const failedSteps=run=>run.jobs.flatMap(j=>j.steps.filter(s=>s.conclusion==='failure').map(s=>`${j.name}: ${s.name}`)).sort();assert.deepEqual(failedSteps(candidate),failedSteps(baseline));assert.deepEqual(failedSteps(candidate),['gate: Backend unit tests']);
const receipt={applicationCommit:application,candidateAttempt,baselineApplication:'b5f471cd2cd56839e7ebbd0d3daf0bbf04791468',baselineRun,candidateRun,workflow:'AI Import E2E Gate',candidateConclusion:candidate.conclusion,failedStage:'Backend unit tests',baselineFailureNames:baselineNames,candidateFailureNames:candidateNames,newFailureNames:[],failedSteps:failedSteps(candidate),baselineFailedSteps:failedSteps(baseline),downstreamImportTests:'Skipped, not claimed passing',frontendSecretScanRun:secretRun,frontendSecretScanConclusion:secret.conclusion,scope:'Frontend-only document archive presentation; backend/schema/auth/workflow unchanged. No new backend deployment or DB writes. Exact same single accepted422 failure in final attempt; initial6 additional failures and one bounded diagnostic retry preserved, no harness fix or global CI green claim'};writeFileSync(root+'/ci-comparison.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
