import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {verifyBrowser} from './browser-guards.mjs';
const root='artifacts/task-validation/423-document-empty-state',out=root+'/compiled-online',read=p=>JSON.parse(readFileSync(root+'/'+p)),sha=b=>createHash('sha256').update(b).digest('hex');
const deployment=read('deployment-receipt.json'),pre=read('compiled-online/pre-run.json'),gate=read('release-gate-receipt.json');assert.equal(pre.applicationCommit,deployment.applicationCommit);assert.equal(pre.applicationCommit,gate.applicationCommit);let cases=0;
for(const r of pre.records){assert.equal(sha(readFileSync(out+'/'+r.recipe)),r.compiledRecipeSha256);assert.equal(r.compiledRecipeSha256,r.localFrozenRecipeSha256);verifyBrowser(read('compiled-online/'+r.folder+'/test-results/browser-results.json'),pre.applicationCommit,r.cases);cases+=r.cases;}assert.equal(cases,gate.rootIndependentRerun);
for(const dep of pre.dependencies){assert.equal(sha(readFileSync(out+'/recipes/'+dep.name)),dep.sha256);assert.equal(sha(readFileSync(root+'/root-rerun/recipes/'+dep.name)),dep.sha256);}
const response=await fetch(pre.bundleUrl);assert.equal(response.status,200);const actual=sha(Buffer.from(await response.arrayBuffer()));assert.equal(actual,pre.bundleSha256Before);assert.equal(actual,deployment.vercel.bundleSha256);const html=await fetch('https://clinicos-eosin.vercel.app/');assert.equal(html.status,200);assert.equal(sha(Buffer.from(await html.arrayBuffer())),pre.htmlSha256Before);
for(const style of pre.styleAssets){const css=await fetch(style.url);assert.equal(css.status,200);assert.equal(sha(Buffer.from(await css.arrayBuffer())),style.sha256);}
const receipt={applicationCommit:pre.applicationCommit,decision:'COMPILED ONLINE ACCEPTANCE VERIFIED',cases,bundleUrl:pre.bundleUrl,bundleSha256Before:pre.bundleSha256Before,bundleSha256After:actual,productionPatientTestMutations:0,apiGuard:'Before-wire auth/facility/clinical fixtures and production static GET allowlist only',physicalHardware:false,realPersistence:false,at:new Date().toISOString()};writeFileSync(out+'/online-receipt.json',JSON.stringify(receipt,null,2));
mkdirSync(out+'/playwright-report',{recursive:true});writeFileSync(out+'/playwright-report/index.html',`<!doctype html><html lang="it"><meta charset="utf-8"><title>ClinicOS423 browser assertions</title><body><h1>#423 — ${cases} gruppi PASS</h1><p>Receipt delle asserzioni Playwright library, NON report del runner nativo. Commit ${pre.applicationCommit}, bundle SHA${actual}; fixture sintetiche, nessuna scrittura reale, viewport mobile emulato non hardware.</p><ul>${pre.records.map(r=>`<li><a href="../${r.folder}/test-results/browser-results.json">${r.folder}: ${r.cases} casi e guardie</a></li>`).join('')}</ul></body></html>`);console.log(JSON.stringify(receipt));
