import {writeFileSync} from 'node:fs';
import {browser,makeContext,openChart,finish,out,expect} from './qa-fixture.mjs';
const observations=[];
const settle=p=>p.evaluate(async()=>{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(r))));});
try{
  const ctx=await makeContext({viewport:{width:1150,height:1004},coarse:true}),page=ctx.page;await openChart(ctx);
  for(const viewport of [{width:390,height:844},{width:1280,height:720},{width:390,height:844}]){
    await page.setViewportSize(viewport);await settle(page);const metric=await page.locator('.main-area-clean').evaluate(e=>({measured:parseFloat(getComputedStyle(e).getPropertyValue('--ds-topbar-occlusion')),actual:e.querySelector('.compact-topbar').getBoundingClientRect().height,control:getComputedStyle(e).getPropertyValue('--ds-control-h')}));expect(Math.abs(metric.actual-metric.measured)).toBeLessThan(1);expect(metric.control.trim()).toBe('44px');observations.push({viewport,...metric});
    const button=page.getByRole('button',{name:'Stampa la scheda',exact:true});await button.scrollIntoViewIfNeeded();await button.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await expect(button).toBeFocused();const focus=await button.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2),s=getComputedStyle(e);return{top:r.top,headerBottom:document.querySelector('.compact-topbar').getBoundingClientRect().bottom,outline:s.outlineWidth,hit:!!h&&(h===e||e.contains(h))};});expect(focus.hit).toBe(true);expect(parseFloat(focus.outline)).toBeGreaterThanOrEqual(2);if(viewport.width===390)expect(focus.top).toBeGreaterThanOrEqual(focus.headerBottom);observations.push({viewport,focus});await page.screenshot({path:`${out}/screenshots/resize-${observations.length}-native-focus.png`});
    const rect=await button.boundingBox();await page.touchscreen.tap(rect.x+rect.width-3,rect.y+rect.height/2);await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await page.getByRole('button',{name:'Apri menu',exact:true}).click();await page.locator('.teams-sidebar').getByRole('button',{name:'Pazienti',exact:true}).click();const search=page.getByRole('searchbox',{name:'Cerca paziente per nome o codice fiscale'});await search.fill('Persona');const clear=page.getByRole('button',{name:'Cancella',exact:true});await expect(clear).toBeVisible();const box=await clear.boundingBox();await page.touchscreen.tap(box.x+3,box.y+box.height/2);await expect(search).toHaveValue('');await expect(page.locator('.patient-list-view')).toBeVisible();await page.screenshot({path:`${out}/screenshots/coarse-edge-clear-result.png`});
  await page.getByRole('button',{name:'Apri menu',exact:true}).click();await page.locator('.teams-sidebar').getByRole('button',{name:'Turno',exact:true}).click();await expect(page.getByRole('heading',{name:'Il mio turno'})).toBeVisible();await settle(page);const cleared=await page.locator('.main-area-clean').evaluate(e=>({metric:e.style.getPropertyValue('--ds-topbar-occlusion'),token:getComputedStyle(e).getPropertyValue('--ds-control-h')}));expect(cleared.metric).toBe('');expect(cleared.token.trim()).toBe('40px');observations.push({unrelatedDashboard:cleared});
  await finish(ctx,'adversarial');writeFileSync(`${out}/test-results/results.json`,JSON.stringify({observations,state:ctx.state,verdict:'PASS software only',realDevice:'EXTERNALLY UNVERIFIED AC3'},null,2));writeFileSync(`${out}/playwright-report/index.html`,'<!doctype html><h1>Independent adversarial software checks</h1><p>PASS: resize observer matches actual wrapping header, native focus unobscured, touch-emulated edge activation opens intended print dialog and clears search, cleanup restores unrelated route40pxcoarse token. AC3realdevice still UNVERIFIED.</p>');console.log('PASS independent dynamic resize/native focus/coarse edge activation/route cleanup');
}catch(error){writeFileSync(`${out}/test-results/preliminary-failure.json`,JSON.stringify({message:error.message,observations},null,2));throw error;}finally{await browser.close();}
