import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { TINETTI_ITEMS, TINETTI_PROVENANCE } from '../../../../frontend/src/lib/assessments/tinettiItems.ts';
import { TINETTI_SOURCE_SHA256, TINETTI_REFERENCE_SHA256 } from '../../../../frontend/src/lib/assessments/tinettiTypes.ts';
const directory = 'artifacts/task-validation/po-12-tinetti/frontend';
const backendDirectory = 'C:/Workspace/ClinicOSHouse-worktrees/po12-tinetti-backend/artifacts/task-validation/po-12-tinetti/backend';
const definitionBytes = readFileSync(`${backendDirectory}/definition-snapshot.json`);
const definition = JSON.parse(definitionBytes);
const expected = definition.groups.flatMap(group => group.items.map(item => ({ id: item.id, label: item.label, group: group.id, options: item.options.map(option => option.description) })));
assert.deepEqual(TINETTI_ITEMS, expected);
assert.equal(TINETTI_PROVENANCE, definition.provenance);
assert.equal(TINETTI_SOURCE_SHA256, definition.source.sha256);
assert.equal(TINETTI_REFERENCE_SHA256, definition.referenceSha256);
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
assert.equal(hash(readFileSync(`${directory}/baseline-ScalaTinettiTab.tsx`)), TINETTI_SOURCE_SHA256);
writeFileSync(`${directory}/definition-snapshot.json`, definitionBytes);
writeFileSync(`${directory}/backend-contract.snapshot.md`, readFileSync(`${backendDirectory}/backend-contract.md`));
writeFileSync(`${directory}/definition-parity.json`, JSON.stringify({ task:'PO-12-frontend', generatedAtUtc:new Date().toISOString(), itemCount:TINETTI_ITEMS.length, optionCount:TINETTI_ITEMS.reduce((n,item)=>n+item.options.length,0), exactLabelsDescriptionsGroupsAndProvenance:true, originalSourceSha256:TINETTI_SOURCE_SHA256, referenceSha256:TINETTI_REFERENCE_SHA256, backendDefinitionSha256:hash(definitionBytes), frontendItemsSha256:hash(readFileSync('frontend/src/lib/assessments/tinettiItems.ts')) },null,2)+'\n');
console.log('20 items and 48 descriptions exactly match the approved source definition.');
